- people/Amanieu.toml
- teams/libs.toml
> Add Amanieu to the libs team

- people/jonas-schievink.toml
Looks like a typo during import
> Fix my name

- people/Emilgardis.toml
- people/andre-richter.toml
- people/jamesmunns.toml
- people/jcsoo.toml
- people/paoloteti.toml
- people/thejpster.toml
- people/therealprof.toml
- teams/wg-embedded.toml
> update wg-embedded e-mails

- teams/production.toml
> Fix production team mailing list

- teams/community.toml
> Fix community mailing lists

- teams/community.toml
- teams/wg-localization.toml
> Add l10n wg

- people/matthewjasper.toml
> Give crater access to matthewjasper

- people/jturner.toml
- teams/community-survey.toml
It's supposed to be jonathandturner
> Remove jturner

- teams/community-rustbridge.toml
> add more members to the rustbridge team

- teams/core.toml
Removing nrc, as he retired from core team
> nrc retiring from core team

- teams/devtools.toml
See https://internals.rust-lang.org/t/tools-team-changes/9569
> Devtools restructure

- README.md
> Bors is now integrated with the team repo

- README.md
> Perf is now integrated with the team repo

- teams/core.toml
- teams/mods.toml
See https://internals.rust-lang.org/t/new-members-for-the-rust-core-team/9575
I'm not sure if I should add @skade here too (I'm not sure if we need to mark observers separately).
> Add self to core, remove from mod team

- people/Manishearth.toml
- teams/core-observers.toml
- teams/core.toml
r? @skade @steveklabnik @pietroalbini
I'm not sure if I've done the TOML stuff correctly, make sure you wait for Pietro to sanity-check the format before merging.
> Add skade as a core team observer

- people/cuviper.toml
> [cuviper] add IRC and allow bors.rust.review

- people/komaeda.toml
- src/permissions.rs
related: https://github.com/rust-lang/rust-central-station/pull/170
> add rustlings bors perms for komaeda

- teams/crates-io.toml
> Add myself to the crates-io team and help@crates.io

- teams/compiler.toml
- teams/lang.toml
> add links to compiler, lang team repositories

- people/gnunicorn.toml
- people/nellshamrell.toml
- teams/wg-governance.toml
cc @skade, @Manishearth, @nikomatsakis, @jonathandturner, and @arshiamufti
I need to add Nell and Benjamin but not sure what their contact info is to put under people
> Add the governance wg to team repo

- people/Aaronepower.toml
- people/cuviper.toml
- teams/release.toml
cc @rust-lang/release 
Will likely merge this after meeting today.
> Update release team permissions

- src/schema.rs
- src/static_api.rs
- src/validate.rs
- teams/libs.toml
Fixes https://github.com/rust-lang/rfcbot-rs/issues/268
r? @alexcrichton 
cc @SimonSapin @Centril
> Exclude members from rfcbot for the libs team

- teams/alumni.toml
- teams/cargo.toml
- teams/devtools.toml
- teams/wg-rustup.toml
It's been an honour and a privilege to collaborate on Cargo and Rustup,
but my interests and attention have been elsewhere recently so I feel
I'd be doing my teammates a disservice by continuing to occupy a team
slot.  I continue to wish the entire Rust project success and it's quite
possible that I might come back in the future.  Thank you, Dale.
cc @alexcrichton @ehuss @killercup @kinnison @Manishearth @nrc
> Alumni myself (dwijnand)

- teams/alumni.toml
> Add wycats to alumni

- teams/cargo.toml
Wycats is leaving, ehuss is a co-lead.
> Update Cargo team

- people/Turbo87.toml
- people/locks.toml
- teams/crates-io.toml
I vouch for these folks, they're Ember experts who have helped a lot with crates.io's frontend and have push permissions on crates.io's repo already, I just forgot about them when we moved to bors because they've been busy lately 😅
> Add folks who help us out with Ember stuff on crates.io

- src/permissions.rs
- teams/libs.toml
See also: https://github.com/rust-lang/rust-central-station/pull/204
cc @Amanieu
> Add hashbrown to homu

- teams/community.toml
- teams/crates-io.toml
Fixes https://github.com/rust-lang/www.rust-lang.org/issues/499
> Some text cleanup for the website

- teams/wg-learning.toml
Related to https://github.com/rust-lang/compiler-team/pull/70
/cc @nikomatsakis @davidtwco
> Add learning WG

- people/rbtcollins.toml
- teams/wg-rustup.toml
> Add myself to Rustup-WG

- people/RalfJung.toml
- src/permissions.rs
- teams/compiler.toml
I hope I did this right. Also see https://github.com/rust-lang/rust-central-station/pull/265.
Cc @oli-obk
> manage miri review permissions: t-compiler and RalfJung

- src/validate.rs
- teams/wg-triage.toml
The WG needs to be under the `operations` meta-team to be shown on the website.
> wg-triage: show it on the website

- teams/wg-async-await.toml
- teams/wg-learning.toml
- teams/wg-llvm.toml
- teams/wg-meta.toml
- teams/wg-mir-opt.toml
- teams/wg-nll.toml
- teams/wg-parallel-rustc.toml
- teams/wg-pgo.toml
- teams/wg-rfc-2229.toml
- teams/wg-rls-2.toml
- teams/wg-self-profile.toml
- teams/wg-traits.toml
> Fix compiler working group links :)

- people/Gankra.toml
- teams/alumni.toml
@Gankra recently changed GitHub username from `Gankro`.
> Rename Gankro to Gankra

- teams/alumni.toml
- teams/docs.toml
@rust-lang/docs I haven't done much core docs work in the past year (and change). I wish I had more time to dedicate to it, but I don't right now, and don't see that changing anytime soon. I'll still be working on some Rust projects in the community and will keep following along in #docs in Discord.
Was fun y'all 💞
> Move myself from the docs team to alumni

- people/Disasm.toml
- people/reitermarkus.toml
- teams/wg-embedded.toml
> Add user ids of new embedded-wg members

- people/Shnatsel.toml
- people/alex.toml
- people/tarcieri.toml
- teams/wg-secure-code.toml
Our charter can be found on our [coordination repo](https://github.com/rust-secure-code/wg#mission):
> Our mission is to make it easy to write secure code in Rust.
>
> We have the following goals for the Rust language and ecosystem:
>
> - Most tasks shouldn't require dangerous features such as unsafe. This includes FFI.
> - Mistakes in security code should be easily caught by machines or, failing that, humans aided by machines.
> - It should be clear to programmers how to perform security-sensitive tasks.
> - Security-critical code which is relied on by Rust programmers should be bug free.
> Add Secure Code WG

- people/smarnach.toml
- teams/crates-io.toml
> Add smarnach to crates.io team.

- people/amanjeev.toml
- people/mark-i-m.toml
- people/togiberlin.toml
- people/tshepang.toml
- teams/wg-learning.toml
Waiting for more members to answer here https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning
> Synchronize wg-learning with GitHub teams

- teams/lang.toml
As announced in [this internals thread][thread].
[thread]: https://internals.rust-lang.org/t/announcing-josh-triplett-as-co-lead-of-lang-team/10965
> add JoshTriplett as lang team lead

- teams/security.toml
Also remove Yehuda who I suspect is ok no longer being on this list.
> Add Pietro to security mailing list

- teams/community.toml
Unsure if this is the appropriate section, but it seemed correct.
> Create mailing list for all hands planning

- people/17cupsofcoffee.toml
- people/AlexEne.toml
- people/erlend_sh.toml
- people/kvark.toml
- people/ozkriff.toml
- people/repi.toml
- teams/wg-gamedev.toml
I've closed https://github.com/rust-lang/team/pull/74 since it was a pain to figure out what was wrong.
I just copied the format from the other working groups. I am not sure how to test that everything is fine.
I assumed the usernames are the github usernames.
Thank you,
Alexandru Ene
> added gamedev-wg

- teams/community-events.toml
- teams/community.toml
- teams/wg-localization.toml
Discussed with Florian, and I'd like to add myself to the community team.
r? @skade
> Add myself to community team

- teams/security.toml
cc @cuviper and @rust-lang/security
> Add cuviper to security team

- teams/libs.toml
* Enable sync with github
* Remove aturon who is no longer a member
* sort the members list
> Update libs team configuration

- teams/community.toml
> Add myself to all hands mailing list.

- teams/release.toml
- teams/wg-grammar.toml
cc @tmandry @eddyb
wg-grammar changes per @Centril's request and approval
> Makes tmandry a member of T-release and eddyb co-lead of wg-grammar

- people/v-thakkar.toml
- teams/wg-embedded.toml
Fix validation error following the output
> Rename nerdyvaishali to v-thakkar

- teams/community-content.toml
- teams/community-events.toml
- teams/community-rustbridge.toml
- teams/community-survey.toml
- teams/community.toml
- Remove Ashley from team and team lead positions
- Add fmoko to RustBridge email list
Hopefully this doesn't clash with the other comm team PRs... also @ashleygwilliams can you approve this? I'm not sure whether you've officially left the team completely.
> Community team updates

- teams/wg-governance.toml
Some people stepped back. And @XAMPPRocky has been quite involved.
r? @skade
> adjust governance wg membership

- teams/alumni.toml
> Add jonathandturner to alumni

- config.toml
- teams/devtools.toml
> Fixup devtools team github perms

- people/JohnTitor.toml
This is intended solely for rollup work at this point.
cc @Centril @tmandry
> Add r+ permission on rust-lang/rust to JohnTitor

- teams/libs.toml
> un-exclude @KodrAus from rfcbot

- teams/icebreakers-llvm.toml
Hi, I would like to follow this area. Even though I'm not wellversed with compilers, I hope I can learn some!
> add myself to icebreakers-llvm

- people/vertexclique.toml
- teams/icebreakers-llvm.toml
PR for LLVM ICE-breakers group.
> add vertexclique to LLVM ICE-breakers

- people/mmilenko.toml
- teams/icebreakers-llvm.toml
Saw a tweet about this. Hope to make time to contribute.
> Added mmilenko, i.e. myself to people, and the icebreakers-llvm team.

- people/niconii.toml
- teams/alumni.toml
- teams/mods.toml
Oops. Better implementation of #170.
r? @nrc or anyone else? Sorry sorry I forgot about the alumni team
> Move nicolette to alumni

- people/mark-i-m.toml
- teams/wg-learning.toml
I'd like to propose @mark-i-m as WG learning co-lead. Mark, please approve if you want to be part of lead group :).
> Add mark-i-m as co-lead and remove nikomatakis from learning wg

- people/SiavoshZarrasvand.toml
- teams/icebreakers-llvm.toml
I'm adding myself to people and llvm icebreakers.
> Add SiavoshZarrasvand

- people/vgxbj.toml
- teams/icebreakers-llvm.toml
Hi rustaceans, in response to the blog post, I would like to join the LLVM ice-breakers to have a try. I've contributed to LLVM before, and also interested in digging more about Rust and LLVM  :smile:
> Add @vgxbj to LLVM ice-breakers

- teams/alumni.toml
- teams/infra.toml
Both @TimNN and @erickt don't have time to contribute to infra anymore. Huge thanks for all the work you did for the project! @erickt is already in alumni, and I moved @TimNN there.
r? @aidanhs
> Remove erickt and TimNN from the infra team

- teams/wg-localization.toml
Add `vertexclique` to wg-localization.
> Add vertexclique to wg-localization

- teams/lang.toml
> Enable craterbot for the lang team

- teams/rustdoc.toml
As requested by @Dylan-DPC and @guillaumegomez -- adding myself to the rustdoc team.
> rustdoc: Add myself to rustdoc team

- people/SimonSapin.toml
I’m curious what lead to this one being used here.
> SimonSapin: use my other email address

- people/totsteps.toml
- teams/wg-triage.toml
according to the latest failure on master
> Rename gagan0723 to totsteps

- people/codesections.toml
- people/epage.toml
- people/matthiasbeyer.toml
- teams/wg-cli.toml
Please don't merge yet, this is a temp PR that we will discuss further as a group next week.
> Changing CLI group leaders and adding mailing list

- teams/wg-embedded.toml
> Add jonas-schievink as embedded WG member

- teams/libs.toml
> Remove @Kimundi from rfcbot polls

- teams/cargo.toml
Eric is the sole leader now. Boats hasn't been around for more than a year.
> Update Cargo team roster

- people/LukasKalbertodt.toml
- teams/libs.toml
cc @rust-lang/libs, as we discussed!
> Add @LukasKalbertodt to the libs team

- people/JOE1994.toml
- teams/icebreakers-llvm.toml
Followed [directions specified in rustc-guide](https://rust-lang.github.io/rustc-guide/ice-breaker/about.html#joining-an-ice-breaker-group) to join ICE-breaker group.
> add JOE1994 to LLVM ICE-breakers

- teams/core.toml
> Add pietro to the core team

- teams/wg-embedded.toml
> Add embedded repo to entry

- teams/crates-io.toml
@sgrif discussed this opportunity with me yesterday on Discord, and I've accepted!  @ashleygwilliams has been a great co-lead but has many other commitments as well.  Thanks for all your contributions so far Ashley!
r? @sgrif
> Replace ashleygwilliams with jtgeibel as co-lead on crates-io team

- teams/wg-cli.toml
Just want so subscribe to the mailing list
> Add my email to extra-emails list

- teams/wg-cli.toml
Ran the `cargo run add-person <username>` for my entry's generation in `people`, and added my email to the wg-cli extra-emails.
Hope I'm doing this right @spacekookie !
> Added myself to wg-cli's extra-emails (mailing list)

- teams/wg-cli.toml
Subscribing to the mailing list
> Add myself to wg-cli mailing list

- teams/icebreakers-cleanup-crew.toml
This is part of https://github.com/rust-lang/compiler-team/issues/207
> create ICEBreakers-Cleanup-Crew team

- teams/alumni.toml
- teams/libs.toml
Kimundi reached out over email and mentioned they'd like to be moved to
alumni status, so this is doing so.
> Move Kimundi to alumni status

- people/Turbo87.toml
- people/carols10cents.toml
- people/jtgeibel.toml
- people/locks.toml
- people/sgrif.toml
- people/smarnach.toml
- teams/crates-io.toml
As discussed in the meeting.
r? @jtgeibel (I can merge it after you approve it)
> crates-io: give r+ on the crates.io repo to the whole team

- people/detrumi.toml
- people/jackh726.toml
- people/skinny121.toml
- teams/wg-traits.toml
This is off the top of my head. I'm definitely overlooking people,
I'll fix it up in follow-up PRs. Sorry!
> extend wg-traits roster with folks who've been active recently

- teams/core.toml
- teams/infra-admins.toml
- teams/infra.toml
- teams/libs.toml
- teams/wg-rustup.toml
- teams/wg-security-response.toml
Follow-up from
https://internals.rust-lang.org/t/scaling-back-my-involvement-in-rust/11754
> Remove myself from a number of teams

- people/sinato.toml
- teams/icebreakers-cleanup-crew.toml
I like Rust. I have no deep knowledge of the compiler yet, but I will do my best
> Add sinato to Cleanup Crew ICE-breakers

- people/senden9.toml
- teams/icebreakers-cleanup-crew.toml
Add myself to the team & the icebreaker cleanup crew
> Add senden9 to the icebreakers cleanup crew

- people/pierreN.toml
- teams/icebreakers-cleanup-crew.toml
Looking for this as a good excuse to explore rustc and improve my rust skills !
> Add pierreN to Cleanup Crew ICE-breakers

- people/hellow554.toml
- teams/icebreakers-cleanup-crew.toml
https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aclose+label%3AI-ICE+commenter%3Ahellow554 (:
> add hellow554 to icebreakers group

- people/turboladen.toml
- teams/icebreakers-cleanup-crew.toml
> Add turboladen to Cleanup Crew ICE-breakers

- people/RobbieClarken.toml
- teams/icebreakers-cleanup-crew.toml
Adding myself to the cleanup crew. Thanks!
> Add RobbieClarken to Cleanup Crew ICE-breaker group

- people/RalfJung.toml
- teams/wg-unsafe-code-guidelines.toml
Also making myself co-lead. I think this matches @nikomatsakis' intent when he proposed I could be something like the UCG "shepherd/liaison/ambassador" to the lang team, or so.
> add myself to UCG

- people/danielhenrymantilla.toml
- teams/wg-secure-code.toml
> Add Yandros to the Secure Code WG

- people/KarlK90.toml
- teams/icebreakers-cleanup-crew.toml
> Add KarlK90 to ICE-Breaker cleanup crew

- people/jakevossen5.toml
- teams/icebreakers-cleanup-crew.toml
> add jakevossen5 to team - Cleanup Crew ICE-breakers

- people/sfackler.toml
> Add zulip-id for sfackler

- people/yaahc.toml
make it so I can use triagebot via zulip
> add zulip id to yaahc.toml

- teams/wg-learning.toml
> Add @chrissimpkins to wg-learning

- people/phansch.toml
I would love to try out the triagebot notification tool =)
> Add my Zulip id

- teams/alumni.toml
- teams/docs-rs.toml
- teams/docs.toml
- teams/rustdoc.toml
This PR should match the current state of the docs.rs and related teams
based on talking with jyn514 and QuietMisdreavus' farewell post.
https://quietmisdreavus.net/self/2020/02/17/rust-ghost-signing-off/
r? @pietroalbini @jyn514
> Add QuietMisdreavus as alumni

- people/spastorino.toml
> Add spastorino zulip-id

- teams/wg-governance.toml
@BatmanAoD Has been attending meetings and contributing with some frequency since I started.
> Sort governance member list and add BatmanAoD

- teams/alumni.toml
- teams/miri.toml
> miri: move solson back to the miri team

- teams/wg-traits.toml
> add yaahc to wg-traits

- teams/wg-governance.toml
@skade has asked to step back from the governance working group. Thanks for your efforts, @skade!
> Remove skade from governance group

- teams/crates-io.toml
> Add jtgeibel to help@crates.io

- teams/wg-mir-opt.toml
https://github.com/orgs/rust-lang/teams/wg-mir-opt
> Sync with the wg-mir-opt github team

- people/LeSeulArtichaut.toml
- teams/wg-learning.toml
> Add LeSeulArtichaut to WG-Learning + add Zulip ID

- people/BatmanAoD.toml
I'd like to try out the new notification infrastructure.
> Add BatmanAoD's Zulip ID

- src/main.rs
- src/schema.rs
> Fix clippy warnings

- teams/infra.toml
> add myself to the infra team

- teams/crates-io.toml
> Add JohnTitor to crates.io team

- people/almindor.toml
- people/burrbull.toml
- people/laanwj.toml
- teams/wg-embedded.toml
> Add missing embedded WG team members

- people/Aaron1011.toml
- teams/compiler-contributors.toml
Thanks for all your hard work, @aaron1011 and @jonas-schievink! <3
> add Aaron1011, Jonas to the compiler contributors

- people/Nashenas88.toml
- teams/wg-rustc-dev-guide.toml
> Add Nashenas88 to people

- teams/wg-prioritization.toml
cc @nikomatsakis @pnkfelix 
Related to https://github.com/rust-lang/compiler-team/pull/263
> Add Prioritization WG

- people/pichfl.toml
- src/validate.rs
- teams/web-presence.toml
> Add pichfl to the Web Presence mailing list

- people/deg4uss3r.toml
- teams/wg-cli.toml
Added myself (deg4uss3r) to `wg-cli.toml`
> Add member to wg-cli.toml

- people/calebcartwright.toml
- teams/wg-rustfmt.toml
> Add calebcartwright to rustfmt working group

- teams/compiler.toml
- teams/wg-parallel-rustc.toml
Thanks for all your hard work, @Zoxc! <3
> Zoxc is stepping back from the compiler team

- teams/libs.toml
With a 👶 on the way I haven't been able to keep up with FCPs for some time. I'm hoping I'll be back on board later this year 🤞
> remove @KodrAus from FCPs

- teams/compiler-contributors.toml
- teams/lang.toml
- teams/mods-discord.toml
- teams/reference.toml
- teams/release.toml
- teams/wg-grammar.toml
- teams/wg-prioritization.toml
Centril is taking a break from the project.
> Update some team memberships

- people/CrazyDebugger.toml
- teams/icebreakers-llvm.toml
Not sure whether this suffices.
r? @Mark-Simulacrum @pietroalbini
> Fix CI error caused by github user rename.

- teams/wg-cli.toml
> Subscribe myself to wg-cli ML

- people/crlf0710.toml
- teams/wg-triage.toml
> Add myself to wg-triage.

- config.toml
- teams/wg-embedded-infra.toml
First team, relates to https://github.com/rust-embedded/wg/issues/442, cc. @pietroalbini
> Added embedded-wg-infrastructure team

- people/RalfJung.toml
- teams/compiler-contributors.toml
@pietroalbini told me to give myself crater permissions. Looks like being in that team will also do the job, and the team description does apply to me I'd argue. ;)
> add myself to compiler-contributors

- teams/crates-io.toml
> crates.io: Add @pichfl as team member

- teams/alumni.toml
- teams/docs-rs.toml
Thanks for being involved in the project @Nemo157 and @Kixiron!
cc @jyn514
> Add Nemo157 and Kixiron to the docs-rs team

- people/lcnr.toml
- teams/wg-prioritization.toml
> Add Bastian Kauschke to wg-prioritization

- teams/wg-async-foundations.toml
> adds nell to wg-async-foundations team

- teams/alumni.toml
- teams/community-content.toml
- teams/twir.toml
As discussed on Community team mailing-list, add @nellshamrell to Community team (and move @nasa42 to alumni).
> Add nellshamrell to Community team.

- people/Elinvynia.toml
- teams/wg-triage.toml
> Add myself to wg-triage

- teams/crates-io.toml
> Add nellshamrell to crates-io team

- people/carols10cents.toml
I'd like to play with Nell's awesome ops bot too!!
> Add my discord ID and ops bot permissions

- src/permissions.rs
- src/validate.rs
> validate: ensure all people with a Discord permission have a Discord ID

- teams/community.toml
> adds nell to the community team

- people/smarnach.toml
@pietroalbini I would also like to play with the bot. :)
> Add discord ID and crates.io staging bot permissions for smarnach.

- people/JohnTitor.toml
- people/Turbo87.toml
- people/ashleygwilliams.toml
- people/carols10cents.toml
- people/ishitatsuyuki.toml
- people/joshtriplett.toml
- people/jtgeibel.toml
- people/locks.toml
- people/nellshamrell.toml
- people/pichfl.toml
- people/pietroalbini.toml
- people/sgrif.toml
- people/smarnach.toml
- people/steveklabnik.toml
- people/withoutboats.toml
- teams/crates-io.toml
> Grant crates-io-ops-bot.staging_crates_io to the whole crates.io team

- people/mbrubeck.toml
My current address is rejecting mail from the rust-mods list for some reason.
> Change email address for mbrubeck

- people/Azhng.toml
- people/ChrisPardy.toml
- people/arora-aman.toml
- people/blitzerr.toml
- people/dyncat.toml
- people/jenniferwills.toml
- people/logmosier.toml
- people/null-sleep.toml
- people/roxelo.toml
- teams/icebreakers-llvm.toml
- teams/wg-rfc-2229.toml
cc @aman-arora, @matthewjasper -- not sure which other names to include here =)
> update membership and sync with github

- people/arlosi.toml
- people/danielframpton.toml
- people/gdr-at-ms.toml
- people/kennykerr.toml
- people/luqmana.toml
- people/lzybkr.toml
- people/retep998.toml
- people/sivadeilra.toml
- teams/windows.toml
> Add windows group

- people/JamieCunliffe.toml
- people/Stammark.toml
- people/joaopaulocarreiro.toml
- people/vigoux.toml
- teams/aarch64.toml
This group contains all the people from ARM willing to help with AArch64 issues.
> Add AArch64 team

- people/Muirrum.toml
- teams/wg-triage.toml
> Add myself to Triage

- people/vgxbj.toml
- teams/icebreakers-llvm.toml
The user changed their GitHub username.
> Rename GitHub user dyncat to vgxbj

- people/LucioFranco.toml
- teams/wg-async-foundations.toml
@luciofranco is going to be working on a draft RFC regarding a "yield safe" lint
> add LucioFranco to wg-async-foundations

- people/eldruin.toml
- teams/wg-embedded.toml
> Add latest team member eldruin to embedded-wg

- teams/compiler-contributors.toml
> add lcnr as a compiler contributor

- teams/windows.toml
I was included originally for testing purposes.
> Remove me from windows ping group

- people/thalesfragoso.toml
- teams/wg-embedded.toml
> Add new embedded WG team member thalesfragoso

- src/schema.rs
Unblocks merging https://github.com/rust-lang/team/pull/376.
> Remove alumni from the all@ mailing list

- people/jyn514.toml
For https://github.com/rust-lang/rust/pull/73566
> Let myself queue perf runs

- teams/libs.toml
Hey all :wave:
I've been off for a while, but am back and caught up now so if @rust-lang/libs is happy I'm good to join the FCP process again 🙂
> Add @KodrAus back to rfcbot

- rust_team_data/src/v1.rs
- src/schema.rs
- src/static_api.rs
- src/validate.rs
- teams/infra.toml
- teams/release.toml
Fixes https://github.com/rust-lang/team/issues/383
> Add support for adding Zulip streams to the website

- teams/wg-rustc-dev-guide.toml
🎉 
cc @rust-lang/wg-rustc-dev-guide
> Add jyn514 to rustc-dev-guide

- people/jswrenn.toml
- teams/wg-safe-transmute.toml
> add jswrenn to the safe-transmute project group

- teams/wg-polymorphization.toml
Given that there is a little bit more work happening around polymorphisation recently and I've been asked about membership, I figured it would make sense to add the working group here for it.
cc @nikomatsakis @pnkfelix as compiler team leads
see also rust-lang/compiler-team#342
> Add polymorphization working group

- people/hargoniX.toml
- teams/wg-embedded-resources.toml
- teams/wg-embedded.toml
> Added hargoniX to the WG and eldruin and hargoniX to the resources team

- people/valgrimm.toml
I made another PR erroneously, this one is correct. Apologies.
> changed email address, please disregard other PR

- teams/leads.toml
Needed for https://github.com/rust-lang/core-team/issues/18
> Synchronize team leads with GitHub

- teams/wg-triage.toml
> Add LeSeulArtichaut to WG-Triage

- people/ebroto.toml
- teams/clippy.toml
cc @Manishearth as team lead.
cc @ebroto as new team member.
@ebroto I used the email, that was used in your latest Clippy commits. ~~Also you don't have set a name on GitHub, so your "real" name defaults to your GitHub name.~~ If you want me to change something in `people/ebroto.toml` before getting this merged, let me know!
Welcome to the Team! 🦀 ❤️
> Add ebroto as new Clippy team member and reviewer

- src/schema.rs
> Fix include-all-team-leads also including WG leads

- teams/cargo.toml
- teams/compiler.toml
- teams/lang.toml
- teams/libs.toml
- teams/reference.toml
- teams/wg-async-foundations.toml
- teams/wg-cli.toml
- teams/wg-diagnostics.toml
- teams/wg-ffi-unwind.toml
- teams/wg-governance.toml
- teams/wg-incr-comp.toml
- teams/wg-inline-asm.toml
- teams/wg-llvm.toml
- teams/wg-meta.toml
- teams/wg-mir-opt.toml
- teams/wg-nll.toml
- teams/wg-parallel-rustc.toml
- teams/wg-polonius.toml
- teams/wg-polymorphization.toml
- teams/wg-prioritization.toml
- teams/wg-rfc-2229.toml
- teams/wg-rls-2.toml
- teams/wg-rustc-dev-guide.toml
- teams/wg-safe-transmute.toml
- teams/wg-secure-code.toml
- teams/wg-self-profile.toml
- teams/wg-traits.toml
- teams/wg-triage.toml
- teams/wg-unsafe-code-guidelines.toml
Should be most of them, but I may have missed a couple
> Add zulip-stream data to teams

- teams/wg-incr-comp.toml
I've talked with Wesley and he is in better position to lead this group right now than me. So changing the team accordingly. Just in case, I continue as a member.
cc @rust-lang/wg-incr-comp
> Make wesleywiser co-lead of incr. comp. WG

- teams/libs.toml
I’ve been less involved lately, no need to block FCP reviews on me.
CC @rust-lang/libs
> Exclude myself (SimonSapin) from rfcbot for T-libs

- teams/wg-prioritization.toml
> Add jyn514 to Prioritization WG

- teams/wg-prioritization.toml
😁
r? @Mark-Simulacrum cc @spastorino
> Fix wrong Zulip stream for Prioritization WG

- people/am-1t.toml
- people/bawerd.toml
- people/djcarpe.toml
- people/frxstrem.toml
- people/hameerabbasi.toml
- people/jechasteen.toml
- people/mstallmo.toml
- teams/wg-prioritization.toml
Welcome @mstallmo @Stupremee @Camelid @jechasteen @frxstrem @bawerd @JamesPatrickGill @djcarpe @am-1t @hameerabbasi  :tada:
cc @spastorino
Depends on #431 and #432 for user files.
> Add people to the Prioritization WG

- teams/project-foundation.toml
As discussed in the group, ag_dubs/nikomatsakis will be driving the effort going forward, with pietro/skade helping as needed.
> adjust project_foundation to have me/ag_dubs as leads, few members

- teams/crates-io.toml
While I do care about policy, and want to help with that in the future, I haven't done any work on crates.io in a long time.
> Remove myself from the crates.io team

- people/senden9.toml
- teams/icebreakers-cleanup-crew.toml
Remove myself from the ICE breakers.
Will join again if I have more sparse time again :)
> Remove senden9 from icebreakers

- people/bIgBV.toml
- people/betamos.toml
- people/lbernick.toml
- teams/wg-async-foundations.toml
> Add @lbernick, @betamos, @bIgBV to wg-async-foundations

- teams/wg-rustc-dev-guide.toml
> Add Joshua Nelson as a Rustc Dev Guide WG lead

- teams/icebreakers-cleanup-crew.toml
I've added myself to this group at the very beginning as a way to test things out and never removed myself, so here I am :).
> Remove spastorino from cleanup crew

- people/m-ou-se.toml
- teams/library-reviewers.toml
@m-ou-se expressed interest in helping with standard library reviews, and has already been doing a ton of terrific work on the standard library. :)
> Add m-ou-se to library-reviewers

- teams/wg-traits.toml
@matthewjasper this should help with bors 😉
> Add matthewjasper to wg-traits

- people/Nashenas88.toml
- teams/wg-rustc-dev-guide.toml
I'm removing myself from wg-rustc-dev-guide since I haven't had time to delve into the compiler and be useful to this team. I've been spending most of my time assisting with rust-analyzer.
> Remove Nashenas88 from wg-rustc-dev-guide and people.

- teams/community-localization.toml
- teams/community.toml
- teams/web-presence.toml
- teams/website.toml
> Update my roster

- people/Manishearth.toml
- people/Xanewok.toml
- people/ibabushkin.toml
- people/matklad.toml
- src/permissions.rs
Initial round of reviewers for semverver as of https://github.com/rust-lang/rust-semverver/issues/137
Also initially adds me and @matklad for the vscode-rust repo.
> Setup bors permissions for semverver and vscode-rust

- teams/wg-compiler-performance.toml
This is just a sketch of who I know for sure is actively working in this area -- happy to expand this set. I was sparked to do this by wanting to add @wesleywiser with commit/write bit to rust-lang/rustc-perf.
r? @nikomatsakis 
cc @wesleywiser
> Adjust compiler performance group

- teams/libs.toml
> Add m-ou-se to libs

- people/workingjubilee.toml
- teams/library-reviewers.toml
- teams/project-portable-simd.toml
So that @workingjubilee can `r+` all the PRs!
> Add workingjubilee to library reviewers

- people/bjorn3.toml
- teams/compiler-contributors.toml
> Add bjorn3 to the compiler contributors

- people/AngelOnFira.toml
- people/logicsoup.toml
- people/patchfx.toml
- teams/wg-gamedev.toml
Discussed in https://github.com/rust-gamedev/wg/issues/96 (_"New WG members"_).
> wg-gamedev: Update members and leads

- teams/community-survey.toml
Since we're the ones coordinating the survey this year =)
cc @rylev 
r? @Manishearth
> update survey leads to the myself + ryan

- people/JohnTitor.toml
As per https://github.com/rust-lang/rust-semverver/issues/137
cc @JohnTitor 
> Add JohnTitor to semverver reviewers

- people/Elinvynia.toml
- teams/wg-triage.toml
Hello, unfortunately I don't have much time anymore to contribute, sorry to let you know so late, been extremely busy <3
> Remove myself from wg-triage

- people/alexcrichton.toml
Accidentally forgot to do this awhile back!
> Update Alex's email

- teams/rustdoc.toml
> Switch main discussion channel to zulip

- people/jackh726.toml
For #76814 and other wg-traits-related work
> Give myself perf permissions

- src/schema.rs
Discovered this while looking through the source code.
> src: fix include-project-group-leads = true not working

- people/nikomatsakis.toml
> update my email address

- teams/wg-prioritization.toml
@rylev [was interested in joining the WG](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2380062.20ICE.3A.20'index.20out.20of.20bounds.3A.20the.20len.20is.200.E2.80.A6/near/220603724)!
r? @spastorino
> Add Ryan Levick to the Prioritization WG

- teams/wg-rustc-dev-guide.toml
> Add Camelid to the dev-guide working group

- people/Nadrieril.toml
- people/cjgillot.toml
- teams/compiler-contributors.toml
Congratulations to @cjgillot and @Nadrieril! 🎉 
r? @pnkfelix
> Add cjgillot and Nadrieril to compiler contributors

- people/igaray.toml
- teams/wg-rustc-dev-guide.toml
> Add Iñaki Garay to the dev-guide working group

- teams/lang-docs.toml
@Gankra has been maintaining the nomicon and they can do some reviews when they have time.
> Add Gankra to the lang-docs team

- teams/core.toml
> Add accounting@rust-lang.org mailing list

- people/tmiasko.toml
- teams/wg-mir-opt.toml
> Add tmiasko to wg-mir-opt

- people/camelid.toml
- teams/rustdoc.toml
- Add myself as co-lead
- Add Nemo and Camelid as members
r? @GuillaumeGomez cc @rust-lang/rustdoc @camelid @Nemo157 
Welcome to the team!
> Rustdoc team changes

- teams/clippy.toml
Unfortunately I don't have enough time lately to be a maintainer of the project.
> Remove myself from the Clippy team

- teams/lang.toml
- teams/library-reviewers.toml
- teams/libs.toml
- teams/project-const-generics.toml
- teams/wg-async-foundations.toml
@withoutboats is stepping back from active team work for a while and requested that I open this PR. 
Thanks @withoutboats for everything you've done! ❤️
> move boats to alumni status

- people/jackh726.toml
- teams/compiler-contributors.toml
- teams/compiler.toml
cc @davidtwco @jackh726 
r? @pnkfelix
> Add David Wood to compiler team and Jack Huey to compiler-contributors

- people/henryboisdequin.toml
- teams/icebreakers-cleanup-crew.toml
- teams/icebreakers-llvm.toml
I would love to help out from time to time! I'm interested in working on the compiler and the LLVM.
> add henry to ice breakers

- teams/wg-rustc-dev-guide.toml
> Add rylev to Rustc Dev Guide

- teams/crates-io.toml
- teams/infra.toml
Hello all, now that I'm on the board of the Rust Foundation I need to cut back on my work with other teams. I have enjoyed working with the infra and crates-io team immensely!
> add nellshamrell to alumni for infra and crates-io

- people/JDuchniewicz.toml
> Add my zulip ID.

- teams/libs.toml
cc @rust-lang/libs 
Welcome @joshtriplett to the Libs team :tada:
> Add joshtriplett to libs

- teams/project-thir-unsafeck.toml
Things I forgot to include in #540.
> Add details about project-thir-unsafeck

- teams/project-edition-2021.toml
> Add project-edition-2021.

- teams/wg-const-eval.toml
cc @lcnr @rust-lang/wg-const-eval
> Add lcnr to wg-const-eval

- teams/wg-traits.toml
> Add spastorino to traits-wg

- people/JohnTitor.toml
- teams/library-reviewers.toml
See https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/libc/near/230416684
cc @rust-lang/libs
> Add @JohnTitor to library-reviewers.

- people/syphar.toml
- teams/docs-rs.toml
r? @pietroalbini cc @syphar @rust-lang/docs-rs
Welcome to the team!
> Add syphar to the docs.rs team

- people/camsteffen.toml
- people/giraffate.toml
- teams/clippy.toml
Cameron and Takayuki have been doing a lot of reviews on clippy and we've decided to invite them to the team!
r? @flip1995
cc @rust-lang/clippy
> Add camsteffen and giraffate to clippy

- teams/libs.toml
- teams/project-portable-simd.toml
It's been a pleasure working with you all! :wave: :heart:
> Remove KodrAus from Libs

- rust_team_data/src/email_encryption.rs
- src/github.rs
- src/permissions.rs
CI is failing because of Clippy, preventing changes from getting deployed.
> Make clippy happy.

- .github/workflows/main.yml
Closes #560, also, contains some tweaks to the config.
> Do not run Clippy on CI

- teams/core.toml
Thanks for everything you did as part of the Core Team @nikomatsakis!
> Move Niko to Core Team alumni

- teams/docs-rs.toml
Chase is mostly working on differential dataflow these days and doesn't have time for docs.rs. We'll miss you! You were really instrumental in getting docs.rs back on its feet when we were still putting out fires every other day :heart:
r? @kixiron cc @rust-lang/docs-rs
> Move Kixiron to docs.rs alumni

- teams/mods.toml
> Enable GitHub teams for the mod team

- people/ethanboxx.toml
- teams/icebreakers-cleanup-crew.toml
I haven't found myself engaging much with these notifications so have decided to leave the list.
> Remove ethanboxx from Cleanup Crew ICE-breakers

- people/AzureMarker.toml
- teams/libs.toml
- teams/wg-traits.toml
Welcome to the team, @yaahc! :heart:
cc @rust-lang/libs
(The second commit is unrelated, but needed to pass the checks. Apparently someone's github username was changed, which makes the CI fail.)
> Add Jane to libs.

- people/jsha.toml
- teams/rustdoc.toml
> Add jsha to the rustdoc team

- teams/compiler-contributors.toml
- teams/compiler.toml
> Add Aaron Hill as full compiler team member

- people/doc-jones.toml
- people/eminence.toml
- people/emmanuelantony2000.toml
- people/zeenix.toml
- teams/wg-async-foundations.toml
As agreed with @tmandry, adding myself, Andrew Chin, Emmanuel Antony and Doc Jones (I hope I got their Github username right) to the team.
cc @nikomatsakis
> Add myself & a few others to the WG

- people/hi-rustin.toml
- teams/wg-rustup.toml
> Add me to wg-rustup

- teams/crates-io.toml
:tada: 
r? @pietroalbini 
cc @Turbo87
> Add Turbo87 as a crates.io co-lead

- teams/wg-grammar.toml
I haven't had any bandwidth for OSS work lately, might as well make it official 😢
> remove myself from wg-grammar

- people/BoxyUwU.toml
- people/the8472.toml
- teams/compiler-contributors.toml
r? @pnkfelix 
cc @BoxyUwU @LeSeulArtichaut @the8472
@BoxyUwU and @the8472, I had to create profiles for both of you which I did based on your GitHub profiles. If you'd like me to change any of the info, feel free to leave a review or otherwise let me know. Thanks!
> Boxy, Léo Lanteri Thauvin and the8472 for compiler-contributors

- teams/project-const-generics.toml
cc @rust-lang/project-const-generics @BoxyUwU
> add BoxyUwU to project-const-generics

- teams/libs-api.toml
Based on Zulip discussion with @sfackler. Thanks for all your work on Rust libraries!
> Move sfackler to libs-api alumni

- teams/libs.toml
> Add cuviper to the library team.

- teams/wg-rustc-dev-guide.toml
I do not have enough time at the moment to devote to organizing the dev-guide.
r? @spastorino cc @rust-lang/wg-rustc-dev-guide
> Remove myself as co-lead of wg-rustc-dev-guide

- people/inquisitivecrystal.toml
- teams/wg-prioritization.toml
I've been helping out with prioritization tasks for a while, so I've asked to formally join the WG.
> Add inquisitivecrystal to wg-prioritization

- people/fee1-dead.toml
- teams/wg-const-eval.toml
They are working on const_trait_impl
cc @rust-lang/wg-const-eval
> Add @fee1-dead to wg-const-eval

- people/xFrednet.toml
- teams/clippy.toml
cc @rust-lang/clippy 
Welcome to the team @xFrednet! :tada: Please confirm that I used the right email. I grabbed it from your commits.
> Add xFrednet to the Clippy team

- people/dkhayes117.toml
- teams/wg-embedded.toml
> Add dkhayes117 as the latest member of the Embedded WG

- teams/community-survey.toml
> Update survey team for 2021 survey

- teams/project-portable-simd.toml
@Lokathor opened https://github.com/rust-lang/team/pull/591 a while ago because they weren't active anymore, but it slipped through the cracks. Reopening.
Thanks for your contributions!
> Lokathor is stepping down

- people/AngelOnFira.toml
Just adding my Discord ID to my page. I have 2FA enabled, and I never plan on getting rid of this account.
> Updating profile with Discord ID (AngelOnFira)

- teams/compiler-contributors.toml
- teams/icebreakers-cleanup-crew.toml
- teams/project-thir-unsafeck.toml
- teams/wg-prioritization.toml
- teams/wg-rustc-dev-guide.toml
- teams/wg-triage.toml
It's been a lot of fun. Thank you :heart:
> Remove myself from all groups

- teams/project-dyn-upcasting.toml
- teams/project-generic-associated-types.toml
- teams/project-impl-trait.toml
> create entries for the 3 active initiatives

- teams/wg-embedded.toml
> Make thejpster an active WG member again

- people/fee1-dead.toml
> Add my email

- teams/compiler-contributors.toml
As discussed internally within the compiler team.
cc @fee1-dead @wesleywiser @pnkfelix
> Add fee1-dead to compiler contributors

- people/jntrnr.toml
- people/rylev.toml
- teams/core.toml
See https://blog.rust-lang.org/2021/09/27/Core-team-membership-updates.html! :tada: :tada: :tada: 
Welcome @rylev @badboy @jntrnr and thanks @Manishearth for everything you did!
> Update the core team membership

- people/jntrnr.toml
Updating to my preferred name for the team listing
> Update name to preferred name

- teams/wg-async-foundations.toml
> Add spastorino to wg-async-foundations

- people/TaKO8Ki.toml
- teams/wg-prioritization.toml
I'm interested in joining the WG! This has been discussed in [this Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/Formally.20joining.20the.20wg-prioritization).
r? @apiraino
> Add TaKO8Ki to wg-prioritization

- people/guswynn.toml
- teams/wg-async-foundations.toml
> add guswynn to async-foundations

- people/diannasoreil.toml
- people/pierwill.toml
- teams/community-rustbridge.toml
- teams/community.toml
- teams/mods-discord.toml
- teams/wg-rustc-dev-guide.toml
> Add pierwill to wg-rustc-dev-guide

- teams/wg-rustc-reading-club.toml
adding rustc reading club to rustc teams.
cc: @wesleywiser   @pnkfelix
> Add wg rustc reading club

- teams/libs-contributors.toml
cc @the8472 @KodrAus
cc @rust-lang/libs
> Add The8472 and KodrAus to libs-contributors.

- teams/wg-security-response.toml
I'm stepping back from this WG to make more time for other things. ❤️
> remove nikomatsakis from wg-security-response

- teams/mods.toml
I am retiring from the moderation team.
> Remove mbrubeck from the moderation team.

- teams/mods.toml
The entire moderation team resigns, effective immediately. This resignation is
done in protest of the Core Team placing themselves unaccountable to anyone but
themselves.
As a result of such structural unaccountability, we have been unable to enforce
the Rust Code of Conduct to the standards the community expects of us and
to the standards we hold ourselves to. To leave under these circumstances
deeply pains us, and we apologize to all of those that we have let down. In
recognition that we are out of options from the perspective of Rust Governance,
we feel as though we have no course remaining to us but to step down and make
this statement.
In so doing, we would offer a few suggestions to the community writ large:
* We suggest that Rust Team Members come to a consensus on a process for …
> mod team resignation

- teams/mods-discourse.toml
- teams/mods.toml
Given the unexpected and unprecedented resignation of the moderation team, the venue mods team (a sub team of the moderation team) is stepping in temporarily to help moderate GitHub and Discourse
> Add technetos and khionu as mods

- people/yoshuawuyts.toml
> add zulip ID to yoshuawuyts

- people/17cupsofcoffee.toml
@AngelOnFira noticed that my email is wrong at the moment (.com instead of .net).
> Update 17cupsofcoffee.toml (fixes #667)

- teams/community-ctcft.toml
This PR creates a new community-ctcft team as a community team subteam
> Create community-ctcft team

- people/yoshuawuyts.toml
> update email for @yoshuawuyts

- people/tmiasko.toml
- teams/compiler-contributors.toml
> Add tmiasko to compiler-contributors

- teams/wg-incr-comp.toml
> Add try and perf permissions to wg-incr-comp

- teams/wg-incr-comp.toml
r? @pnkfelix 
cc @Aaron1011 @cjgillot @pierwill
> Update wg-incr-comp to reflect who's been active recently

- teams/community-content.toml
- teams/community-events.toml
- teams/community.toml
- teams/core.toml
- teams/website.toml
As discussed in early summer, 2021 was my last year on the Rust project.
> Remove skade (Florian Gilcher) from all teams

- teams/rustdoc.toml
Welcome to the team @notriddle!
> Add notriddle to the rustdoc team members

- teams/devtools.toml
Thanks for having me! I'll be around :)
> Remove @killercup as devtools lead

- teams/compiler-contributors.toml
- teams/compiler.toml
Congrats @cjgillot!! 🎉 
r? @pnkfelix
> Add cjgillot as full compiler team member

- teams/wg-rustup.toml
cc: @kinnison I have settled into my new job and I think I can have some time to work on rustup.
> Add me back to rustup team

- teams/project-async-crashdump-debugging.toml
- teams/wg-async.toml
See also https://github.com/rust-lang/wg-async/pull/267
> Rename wg-async-foundations to wg-async

- teams/community-survey.toml
Adds @yaahc to the survey team. 👏🎉
> Add yaahc to the survey team

- teams/project-negative-impls.toml
> add @pnkfelix, who is liaison for negative impls initiative

- teams/core.toml
- teams/wg-rust-by-example.toml
- teams/wg-security-response.toml
https://blog.rust-lang.org/2022/01/31/changes-in-the-core-team.html
> Remove myself from the teams

- teams/core.toml
https://blog.rust-lang.org/2022/01/31/changes-in-the-core-team.html
Thanks, Pietro!
> Remove Pietro from the core team position.

- people/weihanglo.toml
- teams/cargo.toml
cc @rust-lang/cargo @weihanglo
> Add Weihang Lo to the Cargo team

- teams/community-ctcft.toml
Would be useful to have! (cc @rust-lang/community-ctcft)
> add ctcft mailing list

- docs/toml-schema.md
- src/main.rs
- src/permissions.rs
- src/schema.rs
- src/validate.rs
- teams/wg-rustfmt.toml
- tests/static-api/_expected/v1/permissions/bors.crates_io.review.json
- tests/static-api/_expected/v1/permissions/bors.crates_io.try.json
- tests/static-api/_expected/v1/teams.json
- tests/static-api/_expected/v1/teams/leads-permissions.json
- tests/static-api/people/user-6.toml
- tests/static-api/teams/leads-permissions.toml
Refs https://github.com/rust-lang/team/pull/610#issuecomment-950419071
cc @Mark-Simulacrum
> Support ability to manage separate permissions for team leads

- people/kraj.toml
- teams/risc-v.toml
@kraj requested to be added to the risc-v notification group.
> Add kraj to the risc-v notification group

- people/compiler-errors.toml
- teams/compiler-contributors.toml
Congrats @compiler-errors! 🎉 
cc @pnkfelix
> Add compiler-errors to compiler-contributors

- people/JakobDegen.toml
- teams/wg-mir-opt.toml
cc @oli-obk , looking forward to contributing here!
> Join the mir opt wg

- people/ChrisDenton.toml
- teams/libs-contributors.toml
Welcome, @thomcc and @chrisdenton! And thanks for all your contributions. :)
cc @rust-lang/libs
> Add thomcc and ChrisDenton to libs-contributors.

- config.toml
- teams/wg-rls-2.toml
.. and grant people in wg-rls-2 bors review permissions.
> Add rust-analyzer to list of repositories

- teams/wg-diagnostics.toml
cc @rust-lang/wg-diagnostics @compiler-errors
> Add compiler-errors to wg-diagnostics

- people/ouz-a.toml
- teams/cloud-compute.toml
cc @JoelMarcey
@ouz-a is a mentee of mine and we want someone without access to other team resources as a test-person for the dev-desktop. Makes sense to use someone who is regularly working with me, as we can quickly analyze any problems together.
> Give Oguz experimental access to cloud desktop

- people/SomeoneToIgnore.toml
- people/edwin0cheng.toml
- teams/wg-rls-2-triage.toml
Context: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rust-analyzer.20transition.20to.20rust-lang/near/279930477
> Create a triage subteam for the rust-analyzer working group

- people/Byron.toml
- teams/docs-rs.toml
Invited by @jyn514 via [this comment](https://github.com/Byron/crates-index-diff-rs/pull/15#issuecomment-1137904487).
> Add Byron to docs.rs team.

- people/tshepang.toml
- teams/wg-rustc-dev-guide.toml
> add tshepang to wg-rustc-dev-guide

- teams/wg-rustc-dev-guide.toml
I no longer really participate in rustc-dev-guide development. I might come back in the future though!
> rylev retire from rustc-dev-guide

- teams/infra.toml
As announced during today's infra team meeting, welcome @jyn514 to the Infrastructure Team! :tada:
> Add Joshua Nelson to the Infra Team

- people/Alexendoo.toml
- people/dswij.toml
- teams/clippy.toml
Welcome to the Clippy team @Alexendoo and @dswij. :tada: :paperclip:
cc: @rust-lang/clippy
---
@Alexendoo I've also added your Zulip user ID in this PR. If you don't want that, I can remove it again :upside_down_face:
> New clippy members 2022 edition (Alexendoo and dswij)

- people/diannasoreil.toml
signed off... by myself i guess?
> fix: change diannasoriel's name

- teams/types.toml
@Mark-Simulacrum, is there anything else I need to do here?
cc @rust-lang/types
> Enable T-types rfcbot integration

- people/Jarcho.toml
- teams/clippy.toml
Welcome to the Clippy Team @Jarcho :tada: :confetti_ball: :paperclips: 
cc: @rust-lang/clippy
---
@Jarcho, I've taken the email, listed on your GitHub page, hope that's alright with you :upside_down_face:
> Add Jarcho to the Clippy Team :paperclips: :confetti_ball:

- teams/cloud-compute.toml
cc @compiler-errors @JoelMarcey
> Add compiler-errors to demo cloud machine for experimentation

- people/sunfishcode.toml
- teams/libs-contributors.toml
Welcome, @sunfishcode! And thanks for all your contributions. :)
cc @rust-lang/libs @rust-lang/libs-contributors
> Add sunfishcode to libs-contributors.

- people/Dajamante.toml
- teams/cloud-compute.toml
Add @Dajamante to the cloud desktops.
We are creating an onboarding document for quickly getting new Rust contributors setup, and this is the first step :)
> Add Ai to the cloud desktops

- teams/wg-unsafe-code-guidelines.toml
Adds @JakobDegen to @rust-lang/wg-unsafe-code-guidelines. Welcome to the club. :)
> add JakobDegen to UCG

- teams/wg-unsafe-code-guidelines.toml
Some updates to @rust-lang/wg-unsafe-code-guidelines membership
- Adding @CAD97. Welcome onboard!
- Moving @avadacatavra to alumni (with her permission). Thanks for all your help!
> UCG membership updates

- teams/miri.toml
We have not heard from @solson in years, so this just reflects reality I think. I don't even know how to reach them... @solson if you are still around and reading this, please let me know if you have any objections. :)
@oli-obk any objections?
> move solson to Miri alumni

- people/Eh2406.toml
- people/ehuss.toml
- people/weihanglo.toml
Check if it is correct. Thanks!
> zulip-id for Cargo Team members

- people/saethlin.toml
- teams/miri.toml
Welcome @saethlin to @rust-lang/miri :)
> add saethlin to miri team

- teams/project-portable-simd.toml
I've been pretty active in this group from the beginning, although never was on this list. Someone pointed out that I should be, so I ran it by @workingjubilee who agreed.
> Add thomcc to project-portable-simd

- teams/miri.toml
> add Zulip group for Miri team

- docs/toml-schema.md
> Add docs about repo directory structure

- rust_team_data/src/v1.rs
- src/static_api.rs
- tests/static-api/_expected/v1/people.json
cc @pietroalbini
This is for unblocking https://github.com/rust-lang/simpleinfra/pull/110.
> Generate information about people in teams API

- people/deg4uss3r.toml
- teams/wg-cli.toml
Add ZulipID and update email in profile and WG-CLI
> Update My Profile Email and ZulipID

- teams/wg-mir-opt.toml
cc https://github.com/rust-lang/team/issues/826
> Add zulip team for wg-mir-opt

- teams/compiler-contributors.toml
Congrats @eholk! 🎉 
cc @pnkfelix
> Add eholk to compiler-contributors

- people/nellshamrell.toml
- teams/cloud-compute.toml
Give @nellshamrell access to the dev desktops
cc @pietroalbini
> Add Nell to dev desktops

- teams/wg-polymorphization.toml
> add zulip group for wg-polymorphization

- teams/project-keyword-generics.toml
> add lcnr to project-keyword-generics

- people/nbdd0121.toml
- teams/wg-ffi-unwind.toml
I have been working on unwinding related stuff for quite a while now but not formally in the WG.
@BatmanAoD
> Add myself to wg-ffi-unwind

- people/epage.toml
- people/pksunkara.toml
- teams/wg-cli.toml
- @spacekookie: through DM said they were ok to be removed
- @yoshuawuyts: through DM said they were ok to be removed
- @pksunkara: has been acting in the role of a member for a while
- @epage (myself): has been acting as the de facto leader for a while
- deg4uss3r: confirmed over email their continued involvement
- matthiasbeyer: confirmed over email their continued involvement
- Dylan-DPC: conmfirmed over discored their continued involvement
> Clean up WG-CLI's members

- people/jsha.toml
- teams/docs-rs.toml
> add jsha to the docs-rs team

- teams/docs-rs.toml
> Make syphar the docs.rs team lead

- people/bennyvasquez.toml
- teams/twir-reviewers.toml
> adds benny vasquez to the TWIR reviewer team

- rust_team_data/src/v1.rs
Needed for https://github.com/rust-lang/sync-team/pull/10
> Allow comparing bots

- people/albertlarsan68.toml
- teams/icebreakers-cleanup-crew.toml
- teams/windows.toml
Hello,
I would like to participate in the Rust Programming Language.
I do not have a powerful enough computer to contribute to rustc, but still want to help.
> Add albertlarsan68 to teams

- README.md
I just went through this process myself, and figured I should leave some basic suggestions to improve the clarity of the relevant parts of the process.
> Improve getting started advice in README

- people/jhpratt.toml
- teams/cloud-compute.toml
> Add myself to people, cloud-compute

- teams/crate-maintainers.toml
> Add chris to crate-maintainers.

- people/WaffleLapkin.toml
- teams/cloud-compute.toml
> Grant WaffleLapkin access to dev desktops

- teams/libs.toml
cc @the8472 @rust-lang/libs :tada:
> Add The 8472 to libs.

- teams/infra-admins.toml
- teams/infra.toml
Per https://blog.rust-lang.org/2022/07/12/changes-in-the-core-team.html I was moving out of all roles, just delayed infra for a while to ease transition
> Move myself out of infra too

- people/Byron.toml
as preparation for moving to zulip
> add zulip-ip for @Byron

- people/aDotInTheVoid.toml
- teams/rustdoc.toml
Welcome to the team! :partying_face: 
cc @aDotInTheVoid @rust-lang/rustdoc
> Add `@aDotInTheVoid` in the rustdoc team

- people/Nilstrieb.toml
- people/WaffleLapkin.toml
- teams/compiler-contributors.toml
Congratulations @nilstrieb and @wafflelapkin! 🎉 
r? @pnkfelix
> Add Nilstrieb and WaffleLapkin to compiler-contributors

- teams/wg-incr-comp.toml
- teams/wg-rustc-dev-guide.toml
> Move pierwill to hiatus

- src/data.rs
- src/schema.rs
- src/validate.rs
- teams/infra-bors.toml
- tests/static-api/_expected/v1/repos.json
- tests/static-api/_expected/v1/repos/some_repo.json
- tests/static-api/repos/test-org/some_repo.toml
This was breaking sync-team and preventing it from syncing the infra-bors team.
> Check that team is configured for GitHub if used as a repo team

- people/technetos.toml
This PR updates my first name to a preferred name.
> Update first name

- teams/cloud-compute.toml
Allowed by T-infra at https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/cloud.20dev.20desktops/near/319612253
cc @jyn514 @pietroalbini
> Add AlbertLarsan68 to `cloud-compute` team

- docs/toml-schema.md
- people/WaffleLapkin.toml
And also fix the "schema". BTW, is there any docs that describe how `zulip-id` and especially `discord-id` are used?
> Add ids for `WaffleLapkin`

- people/albertlarsan68.toml
- teams/bootstrap.toml
@albertlarsan68 Thank you for your contributions, and welcome!
(This includes https://github.com/rust-lang/team/pull/920 for convenience.)
> Add Albert Larson to the bootstrap team

- people/Muscraft.toml
- people/arlosi.toml
- teams/cargo.toml
> Add Muscraft and arlosi to the Cargo team

- people/chenyukang.toml
- teams/compiler-contributors.toml
Congrats @chenyukang!
r? @pnkfelix
> Add chenyukang to compiler-contributors

- src/github.rs
The current error message when a user is deleted is somewhat difficult to deal with:
```
[ERROR rust_team::validate] validation error: couldn't verify GitHub usernames: graphql error: Could not resolve to a node with the global id of 'MDQ6VXNlcjMzOTgzMzMy'.
```
The solution here is to go through the batch of 100 user IDs and query each one until it fails to determine which GitHub user was deleted.
> Display a more helpful error message for a removed user

- people/HKalbasi.toml
- teams/wg-rls-2-triage.toml
> Add HKalbasi to wg-rls-2-triage

- teams/interim-leadership-chat.toml
This will be for the purposes of ratifying a single RFC only.
> Add temporary "team" interim-leadership-chat to enable rfcbot

- repos/rust-lang/bors.toml
The bors rewrite is still very much an experiment. For now, allow @Kobzol or whoever else on that infra-bors team to merge their own PRs.
> Remove restriction on bors main branch while still an experiment

- teams/fuchsia.toml
> Update Fuchsia platform team members

- people/pitaj.toml
- teams/wg-triage.toml
> Add pitaj to triage team

- teams/clippy.toml
I haven't been contributing for a while now so I think it's time. It's been fun!
> Remove camsteffen from clippy team

- people/aliemjay.toml
- teams/types.toml
> Add aliemjay as a types team member

- people/durin42.toml
- teams/compiler-contributors.toml
Congrats @durin42! 🎉 
r? @pnkfelix
> Add durin42 to compiler-contributors

- teams/mods-discourse.toml
Thanks a bunch, @steffahn!
CC @technetos @khionu
> Add steffahn as discourse mod team member

- teams/wg-security-response.toml
> Add Manish to the Security Response WG

- people/ibraheemdev.toml
- repos/rust-lang/arewewebyet.toml
- teams/arewewebyet.toml
https://github.com/rust-lang/arewewebyet/issues/397#issuecomment-1484086231
Add a team responsible for https://www.arewewebyet.org/ and https://github.com/rust-lang/arewewebyet
> Add arewewebyet team

- teams/rustdoc.toml
[As discussed on zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Cloud.20compute.20.2F.20Dev.20desktop.20feedback/near/349396420)
> Give T-Rustdoc cloud compute access.

- teams/crates-io.toml
As discussed via email conversation with him on 2023-04-17 :)
> crates-io: Move `smarnach` to alumni

- teams/crates-io.toml
... as discussed in the last team meeting
r? @rust-lang/core
> crates.io: Alumnize `pichfl` and `locks`

- people/LawnGnome.toml
- people/mdtro.toml
- teams/crates-io.toml
> crates.io: Add new team members

- teams/wg-async.toml
Reopen the following https://github.com/rust-lang/team/pull/873/files approved by @tmandry 
cc @Mark-Simulacrum @rylev
the only change is that as a people I had already a toml file
> add vincenzopalazzo to async-wg

- people/clubby789.toml
- teams/bootstrap.toml
@clubby789 Welcome to the team!
cc @rust-lang/bootstrap
> Add clubby789 to T-bootstrap

- people/BoxyUwU.toml
- teams/types.toml
As per the T-types vote:
Welcome to the types team @boxyuwu
> Add boxy to T-types

- teams/wg-ffi-unwind.toml
- teams/wg-inline-asm.toml
- teams/wg-safe-transmute.toml
I was the liaison when these groups got started, and participated early
on, but have not been an active member for a while.
> Update WG memberships

- people/basil-cow.toml
- teams/archive/wg-traits.toml
> Rename maegamist to basil-cow

- teams/project-stable-mir.toml
> Add spastorino to stable mir project

- teams/ides.toml
This matches the description from
https://github.com/rust-lang/www.rust-lang.org/commit/d6514d98c141faa3faef27e8a569364158176661
> Update t-ides team description.

- teams/infra.toml
Welcome @Kobzol :tada: :heart:
> Add kobzol to the infra team

- teams/compiler-contributors.toml
as discussed on the T-compiler mailing list and then checked in with @saethlin 
r? @pnkfelix or @wesleywiser
> Add saethlin to compiler contributors

- people/Centri3.toml
- people/blyxyas.toml
- teams/clippy.toml
:drum: :drum: :drum: 
Welcome to the Clippy Team @blyxyas and @Centri3 :tada: :confetti_ball: :paperclips: 
---
@Centri3 Could you give me an email for your user file? The README includes a section on [how to encrypt it](https://github.com/rust-lang/team#encrypting-email-addresses), if you don't want it to be public :)
Once this PR is done, I'll also add you two to the reviewer rotation in the Clippy repo. Thank you for all the work you have already done in the past few months! :heart:
---
r? @flip1995 || @Manishearth 
cc: @rust-lang/clippy
> Add @blyxyas and @Centri3 to the Clippy Team :tada: :confetti_ball: :paperclips: 

- teams/compiler.toml
Congrats @davidtwco and thanks @pnkfelix for all your hard work over the years! 🥇 
r? @pnkfelix @davidtwco 
cc https://github.com/rust-lang/blog.rust-lang.org/pull/1126
> Rotate compiler team co-leads

- people/Enselic.toml
- teams/wg-triage.toml
Hello 👋 I was invited to wg-triage by @Dylan-DPC and will do my best to help triage Rust issues and PRs.
> Add Enselic to wg-triage

- teams/compiler-contributors.toml
Congrats @SparrowLii 🎉 
r? @davidtwco
> Add SparrowLii to compiler-contributors

- people/DianQK.toml
- teams/icebreakers-llvm.toml
Issues I am currently working on or have resolved:
https://github.com/rust-lang/rust/issues?q=assignee%3ADianQK
Related pull requests:
https://github.com/rust-lang/rust/pulls?q=is%3Apr+author%3ADianQK
Upstream related commits:
https://github.com/llvm/llvm-project/commits?author=DianQK&since=2023-01-01&until=2023-08-10
I'm also working toward joining the Compiler team contributors. ٩(๑•̀ω•́๑)۶
> add DianQK to LLVM ICE-breakers

- teams/compiler-contributors.toml
- teams/ides.toml
- teams/rust-analyzer.toml
I haven't been deeply involved with the project for some time now! I am still there to @matklad at me, ask any questions, do an occasional code review or even submit a small patch here and there, but I'd rather not get notified by `@ing` the team at this point!
> move matklad to alumni :-)

- docs/toml-schema.md
The schema documentation seemed a little out-of-date, so this is an attempt to update it. I was particularly confused by what some of the website fields meant.
> Update schema documentation.

- people/jyn514.toml
- teams/bootstrap.toml
- teams/docs-rs.toml
- teams/infra.toml
working on rust has not been healthy for me for a while. if i do work on it in the future, i want it to be because it's fun, not because i feel obligated, and having r+ permissions doesn't help with that.
> make my vacation permanent

- teams/mods.toml
This PR adds Oli to the moderation team :tada:
> Add Oli to mods

- teams/leadership-council.toml
- teams/mods-discord.toml
- teams/mods-discourse.toml
- teams/mods.toml
[Not a farewell, just a bye-for-now.](https://khionu.net/blog/2023-stepping-down-from-rust/)
> Remove myself (khionu) from mods and council

- teams/cargo.toml
See https://internals.rust-lang.org/t/cargo-team-changes/8651
> add matklad to cargo team alumni

- people/technetos.toml
- teams/leadership-council.toml
Follow up to #1058 
Welcome @technetos!
> Add @technetos to the leadership council

- teams/bootstrap.toml
> make `onur-ozkan` co-lead of bootstrap team

- teams/windows.toml
I no longer wish to receives pings to this group.
> Remove rylev from the windows marker team

- people/joshlf.toml
- teams/wg-secure-code.toml
> Add joshlf, the founder of wg-secure-code, to alumni

- teams/icebreakers-llvm.toml
- teams/wg-async.toml
- teams/wg-incr-comp.toml
- teams/wg-mir-opt.toml
I may need to do more cleanup but this is a good start.
> Remove me from groups that I am inactive

- config.toml
- teams/infra.toml
This is necessary to generate the permissions.json file for the test repo.
> Add try permissions to the infra team for the bors test repo

- people/TC.toml
- teams/wg-async.toml
> Add TC to the list of people + WG-async

- people/h1467792822.toml
- people/wain303009.toml
- repos/rust-lang/wg-binary-size.toml
- teams/wg-binary-size.toml
I haven't created a github repo for this yet. I don't know if I do that before or after.
CC @davidtwco, @h1467792822, @Kobzol, @m-ou-se, @nbdd0121, @nnethercote, @wain303009, @workingjubilee
> Add binary size working group

- repos/rust-lang/impl-trait-utils.toml
Fixes: https://github.com/rust-lang/infra-team/issues/79
> Add impl-trait-utils repo

- people/rami3l.toml
- teams/rustup.toml
> Add rami3l to wg-rustup

- teams/wg-async.toml
> Add @compiler-errors to wg-async

- people/mabezdev.toml
- teams/wg-embedded-hal.toml
- teams/wg-embedded-riscv.toml
Pending https://github.com/rust-embedded/wg/pull/702
> Add @mabezdev to rust embedded RISC-V and HAL team

- people/djc.toml
- teams/rustup.toml
> Add djc to wg-rustup

- repos/rust-lang/testing-devex-team.toml
I think I'd read somewhere that this, once merged, will also create the repo if it doesn't exist but please let me know if something additional/prior is needed to first get the repo created
> create new repo for testing-devex team

- teams/project-stable-mir.toml
cc @rust-lang/project-stable-mir
> Add oguz to project-stable-mir

- people/NobodyXu.toml
- repos/rust-lang/cc-rs.toml
Nobody had any objections to this, and we've confirmed it's okay.
CC @NobodyXu
> Give NobodyXu write permissions for `cc-rs`

- repos/rust-lang/rustc_codegen_cranelift.toml
For https://github.com/rust-lang/infra-team/issues/86
> Add rustc_codegen_cranelift repo

- people/jessebraham.toml
- teams/wg-embedded-riscv.toml
- teams/wg-embedded-triage.toml
Pending https://github.com/rust-embedded/wg/pull/715
> Add @jessebraham to Rust Embedded RISC-V and Triage teams

- people/antoyo.toml
- teams/wg-binary-size.toml
> Add antoyo to binary size WG

- people/hi-rustin.toml
- teams/crates-io.toml
@rust-lang/crates-io @hi-rustin has been quite active in the past couple of weeks, so I propose making him an active team member again :)
> crates.io: Make @hi-rustin and active team member again

- docs/toml-schema.md
There are some details about how branch protections work that I think are helpful to clarify.
> Add some clarifications on how branch protections work.

- repos/rust-lang/log.toml
I've been doing reviews for a while now, might as well make them useful.
/cc @KodrAus, the current maintainer of log
> Add Thomasdezeeuw as log maintainer

- teams/risc-v.toml
- teams/wg-embedded-riscv.toml
- teams/wg-embedded.toml
Embedded work group PR: https://github.com/rust-embedded/wg/pull/717
> Remove @Disasm from the EWG RISC-V team and the risc-v marker team

- repos/rust-lang/specification.toml
- teams/spec.toml
> Add rust-lang/spec repository.

- teams/archive/devtools-peers.toml
- teams/cargo.toml
- teams/devtools.toml
- teams/rustdoc.toml
- teams/rustup.toml
Citations:
**`devtools-peers`**
https://github.com/rust-lang/prev.rust-lang.org/pull/823 + https://github.com/rust-lang/prev.rust-lang.org/pull/932
**`cargo`**
https://github.com/rust-lang/prev.rust-lang.org/pull/823
**`devtools`**
https://github.com/rust-lang/prev.rust-lang.org/pull/124 ("Tooling and infrastructure team") + https://github.com/rust-lang/prev.rust-lang.org/commit/4a41e38969c735da56481a1adb23be0b57318672 + https://github.com/rust-lang/prev.rust-lang.org/pull/736 + https://github.com/rust-lang/prev.rust-lang.org/pull/823 + https://github.com/rust-lang/prev.rust-lang.org/pull/932 + https://github.com/rust-lang/team/commit/2e0e7821670c242249d39c3d84ecef063c11b3cc + https://github.com/rust-lang/team/pull/32
**`rustdoc`** …
> Add devtools alumni

- teams/mods-discord.toml
- teams/mods.toml
Citations:
**`mods-discord`**
https://github.com/rust-lang/team/pull/43 through https://github.com/rust-lang/team/commit/813666af13bcbdf09af52512c258606b67b49448
**`mods`**
https://github.com/rust-lang/prev.rust-lang.org/pull/124
> Add mod team alumni

- teams/compiler-contributors.toml
@fmease has been making valued contributions to the compiler's frontend and type system for a while now.
Congrats @fmease and well earned! 🎉
r? @wesleywiser
> compiler contributors: add fmease

- Cargo.toml
- rust_team_data/Cargo.toml
I have an upcoming PR that involves changing a dependency and I couldn't make sense of where in the dependencies list I was supposed to insert it.
> Sort dependencies in Cargo.toml

- repos/rust-lang/impl-trait-utils.toml
Add @compiler-errors and @traviscross as maintainers.
> Add maintainers for impl-trait-utils

- teams/twitter.toml
I haven't accessed the Twitter account in a while, and I'd rather not have access if I'm not actually helping. 
r? @m-ou-se
> Remove rylev from Twitter marker team

- repos/rust-lang/.github.toml
Starting with the (hopefully) easy stuff :)
> Add `.github` repository under automation

- people/tranquillity-codes.toml
- teams/wg-triage.toml
> Add tranquillity-codes to wg-triage

- repos/rust-lang/infra-team.toml
Repo: https://github.com/rust-lang/infra-team
Configuration extracted from GitHub:
```
name = "infra-team"
bots = []
[access.teams]
jdno = "admin"
```
> Add infra-team repository under automation

- repos/rust-lang/rustc-dev-guide.toml
Repo: https://github.com/rust-lang/rustc-dev-guide
Going through the repos one-by-one, sorted by recent activity :)
Configuration extracted from GitHub:
```
name = "rustc-dev-guide"
description = "A guide to how rustc works and how to contribute to it."
bots = []
[access.teams]
bots = "write"
wg-rustc-dev-guide = "maintain"
libs = "write"
spastorino = "maintain"
SimonSapin = "write"
bors = "write"
fee1-dead = "write"
TaKO8Ki …
```
> Add rustc-dev-guide repository under automation

- people/kupiakos.toml
- teams/wg-binary-size.toml
See https://github.com/rust-lang/wg-binary-size/issues/4. I've already talked with @tgross35
> Add kupiakos.toml, add to wg-binary-size

- repos/rust-lang/compiler-team.toml
Repo: https://github.com/rust-lang/compiler-team
Current permissions extracted from GH:
```
name = "compiler-team"
description = "A home for compiler team planning documents, meeting minutes, and other such things."
bots = []
[access.teams]
wg-prioritization = "write"
mods = "write"
types = "write"
wg-compiler-performance = "write"
Nadrieril = "write"
lqd = "write"
aliemjay = "write"
nikic = "write"
jdno = "admin"
camelid = "write"
flodiebold = "write"
hkmatsumoto = "write"
technetos = "write"
est31 = …
```
> Add compiler-team repository under automation

- repos/rust-lang/calendar-generation.toml
I need more people I can ask to approve these PRs.
> Add more permissions to calendar generation

- people/Turbo87.toml
less google, more better... :D
> people/Turbo87: Change email address

- repos/rust-lang/futures-rs.toml
Repo: https://github.com/rust-lang/futures-rs
CC @taiki-e
```
name = "futures-rs"
description = "Zero-cost asynchronous programming in Rust"
bots = []
[access.teams]
wg-async = "write"
withoutboats = "write"
MajorBreakfast = "write"
cramertj = "admin"
Nemo157 = "write"
traviscross = "write"
seanmonstar = "write"
vincenzopalazzo = "write"
jdno = "admin"
guswynn = "write"
aturon = "write"
eholk = "write"
taiki-e = "write"
alexcrichton = "write"
nrc = "write" …
```
> Add futures-rs repository under automation

- teams/twir.toml
To unblock https://github.com/rust-lang/team/pull/1218.
> Create a GitHub team for the twir team

- teams/wg-embedded-libs.toml
https://github.com/rust-embedded/wg/pull/729
> Add myself to `@rust-embedded/libs` team.

- repos/rust-lang/futures-rs.toml
Noticed in https://github.com/rust-lang/futures-rs/pull/2823#issuecomment-1897646263.
> Do not require approvals for futures-rs

- teams/libs-contributors.toml
cc @Nilstrieb @rust-lang/libs @rust-lang/libs-contributors
> Add Nilstrieb to libs-contributors.

- teams/infra.toml
I am no longer doing enough IMO to warrant being on the team. While I'd still like to contribute here and there, I'd feel better removing my name from the membership list.
> rylev retiring from infra

- src/data.rs
For example, the `spec` repo is located in a `specification.toml` file, which is not very intuitive. Upholding this property also makes sure that the repo names in a given organization are unique (until we implement archiving, which might put archives repos in a different directory).
> Make sure that repository name is the same as its TOML filename

- repos/rust-lang/libc.toml
- teams/crate-maintainers.toml
- teams/libs-api.toml
- teams/libs.toml
Suggested by https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/merge.20queue.20for.20libc/near/411972452
> Remove libc bors conf

- teams/community-survey.toml
I have discussed the leadership change with rylev and apiraino, and I think that there's no issue with having two leads. The more, the merrier :grin:
CC @rylev @apiraino
> Change leads of the community survey team to Kobzol and apiraino

- repos/rust-lang/rustwide.toml
Repo: https://github.com/rust-lang/rustwide
CC @pietroalbini
```toml
name = "rustwide"
description = "Execute your code on the Rust ecosystem."
bots = []
[access.teams]
jdno = "admin"
```
> Add rustwide repository under automation

- repos/rust-lang/wg-incr-comp.toml
Repo: https://github.com/rust-lang/wg-incr-comp
```
name = "wg-incr-comp"
description = "Home repo for the compiler team incremental compilation working group"
bots = []
[access.teams]
wg-incr-comp = "maintain"
compiler-contributors = "maintain"
BoxyUwU = "maintain"
WaffleLapkin = "maintain"
Nilstrieb = "maintain"
b-naber = "maintain"
TaKO8Ki = "maintain"
saethlin = "maintain"
nnethercote = "maintain"
chenyukang = "maintain"
Nadrieril = "maintain"
est31 = "maintain"
matthewjasper = "maintain"
fmease = "maintain"
tmiasko = "maintain"
lqd = "maintain"
tmandry = "maintain"
RalfJung = "maintain"
fee1-dead = "maintain"
apiraino …
```
> Add wg-incr-comp repository under automation

- repos/rust-lang/wg-security-response.toml
Repo: https://github.com/rust-lang/wg-security-response
```
name = "wg-security-response"
description = "Documentation for the Rust Security Response WG"
bots = []
[access.teams]
security = "write"
jdno = "admin"
Manishearth = "write"
```
> Add wg-security-response repository under automation

- repos/rust-lang/measureme.toml
- teams/compiler.toml
- teams/wg-compiler-performance.toml
Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/bors.20blocked.20in.20measureme.20repo/near/417653103).
> Remove bors configuration for measureme

- config.toml
- docs/toml-schema.md
- teams/crates-io.toml
see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/team.20repo.20integration/near/412316069
/cc @pietroalbini
> Add `crates-io-admin` permission

- repos/rust-lang/project-stable-mir.toml
Discussed [here](https://github.com/rust-lang/team/pull/1288).
> Remove bors from project-stable-mir

- repos/rust-lang/libc.toml
Requested [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/merge.20queue.20for.20libc/near/417544359).
> Do not require approvals for libc

- repos/rust-lang/rfcs.toml
Repo: https://github.com/rust-lang/rfcs
https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 mentions putting this under team leads, so far I just kept access to the teams that had it before, let me know what is the preferred way.
CC @ehuss
Fixes: https://github.com/rust-lang/team/issues/1096
```
name = "rfcs"
description = "RFCs for changes to Rust"
bots = []
[access.teams]
libs = "write"
rfcbot = "write"
all = "write"
lang = "write"
bots = "write"
core = "admin"
alexcrichton = "write"
LawnGnome = "write"
Alexendoo = "write"
technetos = …
```
> Add rfcs repo under automation

- repos/rust-lang/polonius.toml
Repo: https://github.com/rust-lang/polonius
```toml
name = "polonius"
description = "Defines the Rust borrow checker."
bots = []
[access.teams]
wg-polonius = "write"
core = "admin"
lqd = "write"
ecstatic-morse = "write"
lcnr = "admin"
estebank = "admin"
jdno = "admin"
amandasystems = "write"
```
> Add polonius repository under automation

- repos/rust-lang/negative-impls-initiative.toml
Repo: https://github.com/rust-lang/negative-impls-initiative
```toml
name = "negative-impls-initiative"
description = "Lang team negative impls initiative"
bots = []
[access.teams]
lang = "write"
initiative-negative-impls = "write"
jdno = "admin"
```
> Add negative-impls-initiative repository under automation

- repos/rust-lang/project-ffi-unwind.toml
Repo: https://github.com/rust-lang/project-ffi-unwind
```toml
name = "project-ffi-unwind"
bots = []
[access.teams]
lang = "write"
core = "write"
wg-ffi-unwind = "write"
cratelyn = "write"
jdno = "admin"
CAD97 = "write"
chorman0773 = "write"
acfoltzer = "write"
gnzlbg = "write"
bjorn3 = "write"
BatmanAoD = "write"
nbdd0121 = "write"
```
> Add project-ffi-unwind repository under automation

- repos/rust-lang/project-safe-transmute.toml
Repo: https://github.com/rust-lang/project-safe-transmute
```toml
name = "project-safe-transmute"
description = "Project group working on the \"safe transmute\" feature"
bots = []
[access.teams]
lang = "write"
wg-safe-transmute = "write"
libs = "write"
jdno = "admin"
lcnr = "write"
estebank = …
```
> Add project-safe-transmute repository under automation

- repos/rust-lang/async-fundamentals-initiative.toml
Repo: https://github.com/rust-lang/async-fundamentals-initiative
```toml
name = "async-fundamentals-initiative"
bots = []
[access.teams]
jdno = "admin"
```
> Add async-fundamentals-initiative repository under automation

- repos/rust-lang/rust-enhanced.toml
Repo: https://github.com/rust-lang/rust-enhanced
CC @ehuss
```toml
name = "rust-enhanced"
description = "The official Sublime Text 3 package for the Rust Programming Language"
bots = []
[access.teams]
jasonwilliams = "admin"
jdno = "admin"
jhasse = "write"
steveklabnik = "write"
```
> Add rust-enhanced repository under automation

- repos/rust-lang/compiler-team-prioritization.toml
Repo: https://github.com/rust-lang/compiler-team-prioritization
```toml
name = "compiler-team-prioritization"
description = "Home repository for the compiler team \"prioritization group\""
bots = []
[access.teams]
wg-prioritization = "write"
b-naber = "write"
flodiebold = "write"
lqd = "write"
jdno = "admin"
Nilstrieb = "write"
BoxyUwU = "write"
tmiasko = "write"
SparrowLii = "write"
nnethercote = "write"
nikomatsakis = …
```
> Add compiler-team-prioritization repository under automation

- people/kulp.toml
- people/ojeda.toml
- people/pvdrz.toml
- teams/wg-bindgen.toml
Except Ojeda, everyone else used to have access to the repo.
Also, fix the repo URL.
> Add a few people to wg-bindgen.

- teams/wg-mir-opt.toml
I'm starting to put some of the optimizations into mir. :)
Sometimes I need the perf permission too.
cc @oli-obk
> Add myself to wg-mir-opt

- people/Young-Flash.toml
- teams/rust-analyzer-contributors.toml
cc rust-analyzer team lead @Veykril
> add Young-Flash to rust-analyzer contributors team

- repos/rust-lang/libtest-next.toml
Transfer of an existing repo was initiated
> Add libtest-next for eRFC #3558

- repos/rust-lang/initiative-template.toml
Repo: https://github.com/rust-lang/initiative-template
```toml
name = "initiative-template"
description = "A template for lang-team initiatives"
bots = []
[access.teams]
lang = "maintain"
tmandry = "maintain"
scottmcm = "maintain"
jdno = "admin"
nikomatsakis = "maintain"
```
> Add initiative-template repository under automation

- repos/rust-lang/book.toml
I'm the only maintainer of the book right now, but it turns out https://github.com/rust-lang/team/pull/1198 made it so that I can't merge my own PRs 😢
> Give Carol permission to merge her own PRs to the book

- people/joboet.toml
- teams/libs-contributors.toml
Welcome, @jhpratt and @joboet! 🎉
cc @rust-lang/libs @rust-lang/libs-contributors
> Add new libs-contributors.

- people/chriskrycho.toml
- repos/rust-lang/book.toml
I'm pleased to announce that @chriskrycho has agreed to join me as a co-author of TRPL 🎉
> Give Chris Krycho permission to maintain the book

- repos/rust-lang/bors.toml
Some contributions are starting to come in, so it's nice to have CI checks. Let's not require approvals for now though.
> Add branch protections for bors

- teams/wg-llvm.toml
For details see discussion in https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/Lead
cc @nagisa @nikic @cuviper
> Update wg-llvm.toml to make nikic the lead

- teams/wg-llvm.toml
I intend to add myself to the `wg-llvm`.
But I often say things that are confusingly wrong. It's okay if I am not a good fit at this time. :3
r? @nikic
> Add myself to wg-llvm

- teams/book.toml
Suggested [here](https://github.com/rust-lang/team/pull/1198#issuecomment-1892511450).
> Add book team

- repos/rust-lang/gcc.toml
- repos/rust-lang/gccjit.rs.toml
> Add gcc and gccjit.rs repos

- repos/archive/rust-lang/compiler-rt.toml
- repos/archive/rust-lang/crates-io-cargo-teams.toml
- repos/archive/rust-lang/crates-io-ops-bot.toml
- repos/archive/rust-lang/gedit-config.toml
- repos/archive/rust-lang/highfive.toml
- repos/archive/rust-lang/hoedown.toml
- repos/archive/rust-lang/jemalloc.toml
- repos/archive/rust-lang/kate-config.toml
- repos/archive/rust-lang/libtest.toml
- repos/archive/rust-lang/lld.toml
Batch of 10 already archived repos.
- https://github.com/rust-lang/compiler-rt
<details>
```toml
name = "compiler-rt"
description = "No longer used, use https://github.com/rust-lang/llvm-project instead"
bots = []
[access.teams]
core = "admin"
jdno = "admin"
TimNN = "write"
pattern = "rust-*"
```
</details>
- https://github.com/rust-lang/crates-io-cargo-teams
<details>
```toml
name = "crates-io-cargo-teams"
description = "the home of the crates io team"
bots = [] …
```
> Add a batch of 10 archived repositories

- repos/archive/rust-lang/lldb.toml
- repos/archive/rust-lang/llvm.toml
- repos/archive/rust-lang/mailgun-mailmap.toml
- repos/archive/rust-lang/meeting-minutes.toml
- repos/archive/rust-lang/nano-config.toml
- repos/archive/rust-lang/prev.rust-lang.org.toml
- repos/archive/rust-lang/rls.toml
- repos/archive/rust-lang/rust-central-station.toml
- repos/archive/rust-lang/rust-gha.toml
- repos/archive/rust-lang/rust-guidelines.toml
Another batch of already archived repositories.
- https://github.com/rust-lang/lldb
<details>
```toml
name = "lldb"
description = "No longer used, use https://github.com/rust-lang/llvm-project instead"
bots = []
[access.teams]
cuviper = "admin"
tromey = "write"
jdno = "admin"
```
</details>
- https://github.com/rust-lang/llvm
<details>
```toml
name = "llvm"
description = "No longer used, use https://github.com/rust-lang/llvm-project instead"
bots = []
[access.teams]
core = "admin"
rust-lang-owner = …
```
> Add another batch of 10 archived repositories

- repos/archive/rust-lang/rust-playpen.toml
- repos/archive/rust-lang/rust-roadmap-2017.toml
- repos/archive/rust-lang/rust-wiki-backup.toml
- repos/archive/rust-lang/rustfix.toml
- repos/archive/rust-lang/subteams.toml
- repos/archive/rust-lang/vscode-rust.toml
- repos/archive/rust-lang/wg-governance.toml
This finishes the port of all the currently archived repositories.
- https://github.com/rust-lang/rust-playpen
<details>
```toml
name = "rust-playpen"
description = "A web interface for running Rust code"
bots = []
[access.teams]
core = "admin"
jdno = "admin"
```
</details>
- https://github.com/rust-lang/rust-roadmap-2017
<details>
```toml
name = "rust-roadmap-2017"
description = "Tracking Rust's roadmap"
bots = []
[access.teams]
mods = "write"
core = "admin"
libs = "write" …
```
> Add yet another batch of 7 archived repositories

- repos/archive/rust-lang/atom-ide-rust.toml
- repos/archive/rust-lang/foundation-faq-2020.toml
- repos/archive/rust-lang/ghost-code-initiative.toml
**These repositories are not yet archived!**
I added them for archivation based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and/or what I thought was an obsolete repository.
- https://github.com/rust-lang/atom-ide-rust
<details>
```toml
name = "atom-ide-rust"
description = "Rust IDE support for Atom, powered by the Rust Analyzer or Rust Language Server"
bots = []
[access.teams]
jdno = "admin"
aergonaut = "write"
mehcode = "write"
alexheretic = "write"
aminya = "maintain"
```
</details>
- https://github.com/rust-lang/foundation-faq-2020
<details>
<summary>Extracted from …
> Add a batch of 3 repositories for archival

- teams/project-stable-mir.toml
Unfortunately I'm not having time for this anymore and moving me to alumni reflects better the current status.
r? @oli-obk
> Move spastorino to alumni on SMIR

- src/validate.rs
It turns out that [we were allowing multiple Zulip group definitions and simply taking the last one we processed](https://github.com/rust-lang/team/pull/1411#discussion_r1533504776). This ensures that a Zulip user group can only be defined once.
> Ensure Zulip user group definitions are unique

- teams/crate-maintainers.toml
intend to be a proud maintainer of https://github.com/rust-lang/ferris-says and I would really like merge rights for that ✨
cc @Amanieu
> add lcnr to crate-maintainers

- repos/archive/rust-lang/rust-reach-www.toml
- repos/archive/rust-lang/rust-semverver.toml
- repos/archive/rust-lang/rustc-timing.toml
- repos/archive/rust-lang/web-presence-team.toml
**These repositories are not yet archived!**
Repositories were selected based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and usage statistics.
- https://github.com/rust-lang/rust-reach-www
<details>
```toml
name = "rust-reach-www"
description = "the website for the rust reach program"
bots = []
[access.teams]
jamesmunns = "write"
deg4uss3r = "write"
aidanhs = "write"
japaric = "write"
spacekookie = "write"
avadacatavra = "write"
rahul-thakoor = "write"
jdno = "admin"
``` …
> Add a batch of 4 repositories for archival #4

- teams/compiler-contributors.toml
Congrats @jieyouxu!
r? @davidtwco
> Add jieyouxu to compiler-contributors

- repos/archive/rust-lang/project-rfc-2229.toml
- repos/archive/rust-lang/rfc-leadership-council.toml
- repos/archive/rust-lang/rust-marketing.toml
- repos/archive/rust-lang/rust-memory-model.toml
**These repositories are not yet archived!**
Repositories were selected based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and usage statistics.
- https://github.com/rust-lang/project-rfc-2229
<details>
```toml
name = "project-rfc-2229"
description = "A repository tracking the planning for implementation and evaluation of RFC 2229."
bots = []
[access.teams]
wg-rfc-2229 = "write"
est31 = "write"
Azhng = "write"
Nilstrieb = "write"
tmiasko = "write"
b-naber = "write"
fmease = …
```
> Add a batch of 4 repositories for archival #3

- repos/rust-lang/blog.rust-lang.org.toml
> blog: Add `ci-checks`

- teams/types.toml
jackh726 = senior lead
lcnr = junior lead
Congratulations, @lcnr!
cc @rust-lang/types
> rotate types team leadership

- people/hdhoang.toml
> adding my zulip-id

- teams/wg-rustc-dev-guide.toml
"that's already enough" ~ @spastorino
> Add Boxy to the dev guide repo

- people/FractalFir.toml
- people/d-sonuga.toml
- people/ding-young.toml
- people/mav3ri3k.toml
- people/s7tya.toml
- people/suaviloquence.toml
- people/tiif.toml
- teams/gsoc-contributors.toml
The only remaining contributor missing is shenmu, from who we haven't heard back yet.
> Add more members to the GSoC contributors team

- people/shannmu.toml
- teams/gsoc-contributors.toml
Finally found the last contributor's GH a ccount.
> Add `shannmu` to `gsoc-contributors`

- teams/rustdoc-contributors.toml
- teams/rustdoc.toml
We discussed about it in the [rustdoc team meeting on zulip](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.202024-05-13/near/438428274).
We already have @Nemo157, @aDotInTheVoid, @notriddle and myself on board (from the likes on the comments).
cc @rust-lang/rustdoc @fmease
> Promote fmease from the rustdoc-contributors team to the rustdoc team

- people/nastevens.toml
Adding my Zulip ID - see https://rust-lang.zulipchat.com/#narrow/stream/436762-wg-embedded/topic/Current.20member.20roster.20of.20wg-embedded/near/439067597
> Add Zulip ID for nastevens

- teams/spec.toml
@JoelMarcey has been doing a lot of the spec team leadership work, so passing on the team lead hat to him to reflect that. :)
cc @rust-lang/spec
> Make Joel team lead of the spec team.

- teams/rust-for-linux.toml
One more -- thanks Vincenzo!
Cc: @vincenzopalazzo
> Add Vincenzo to Rust for Linux ping group

- teams/spec.toml
Joel Marcey, the owner of the spec work, proposed that I join the team, and the team confirmed his nomination with unanimous consent.
Correspondingly, in this commit, we add me (TC) to the spec team.
cc @JoelMarcey @m-ou-se @pnkfelix @ehuss
> Join the spec team

- teams/lang-docs.toml
TC has volunteered to help with some lang-docs work.
> Add TC to lang-docs

- people/Urgau.toml
- teams/compiler-contributors.toml
Congrats @Urgau! 
r? @davidtwco
> Add Urgau to compiler-contributors

- people/thejpster.toml
- teams/wg-embedded-cortex-m.toml
- teams/wg-embedded-tools.toml
- teams/wg-embedded.toml
* remove both my accounts from wg-embedded, because https://github.com/rust-embedded/wg/pull/763 apparently doesn't do this automatically
* change my e-mail address to a non-generic one
> Remove thejpster

- teams/rust-for-linux.toml
> Add Matthew to the Rust for Linux ping group

- people/roife.toml
- teams/rust-analyzer-contributors.toml
> Add roife to rust-analyzer contributors team

- people/DropDemBits.toml
- teams/rust-analyzer-contributors.toml
> Add DropDemBits to rust-analyzer-contributors team

- teams/lang.toml
Please join us in welcoming TC as a new member of the Rust language design team. TC has been a valuable contributor to the Rust project, serving as the lead of the lang-ops team and overseeing the Rust 2024 edition.
TC has authored or co-authored several influential RFCs, including [RFC 3498] on revising capture rules, [RFC 3617] on precise capturing, [RFC 3484] on extern blocks, and [RFC 3513] on gen blocks.
He has also contributed to numerous projects, including high profile projects like *async fn in traits* and *type alias impl trait*, and to less prominent efforts like improvements to match ergonomics. He looks for opportunities to unblock owners who are driving important work but need help to get that work over the finish line. During meetings, TC consistently looks to clarify …
> Welcoming TC to the Rust language team

- teams/wg-binary-size.toml
Discussed at https://github.com/rust-lang/team/pull/1487#issuecomment-2202309264
> Grant try and perf permissions to wg-binary-size

- people/oskgo.toml
- teams/wg-triage.toml
Hello. I was invited by @Dylan-DPC and would like to help!
> Add oskgo to wg-triage

- people/tgross35.toml
- teams/libs-contributors.toml
Welcome @tgross35!
cc @rust-lang/libs @rust-lang/libs-contributors
> Add tgross35 to libs-contributors

- people/jannic.toml
- teams/wg-embedded-triage.toml
Ref https://github.com/rust-embedded/wg/pull/779
> Add Jannic to wg-embedded-triage team

- people/obi1kenobi.toml
So that I can be pinged automatically in topics like https://rust-lang.zulipchat.com/#narrow/stream/435869-project-goals/topic/Begin.20resolving.20.60cargo-semver-checks.60.20blockers.20.28goals.23104.29
> Add Predrag Gruevski's Zulip ID to obi1kenobi.toml

- repos/rust-lang/infra-team.toml
Add an homepage to the repository team to provide more context 👍
> add infra-team repo homepage

- teams/rust-for-linux.toml
In order to test changes to the RFL CI job, if needed.
Cc: @Kobzol
>  Grant try permissions to Rust for Linux marker team

- teams/crate-maintainers.toml
> Add tgross35 to crate-maintainers

- people/BlackHoleFox.toml
- teams/apple.toml
I help maintain and answer questions about Apple-specific parts of `cc-rs` and contribute/review Apple-specific contributions to `rustc` and `std` too.
Myself joining the group was prior discussed here https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/I'd.20like.20to.20contribute.20more.20.28to.20Apple-specific.20stuff.29/near/434264127
> Add myself to the Apple marker team

- people/jongiddy.toml
- teams/crate-maintainers.toml
> Add jongiddy as a mantainer for flate2-rs

- repos/rust-lang/cmake-rs.toml
- repos/rust-lang/libm.toml
As requested in [zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/compiler-builtins.20crates.2Eio/near/462509221)
> Add branch protection to cmake and libm

- people/lolbinarycat.toml
- teams/wg-triage.toml
> add lolbinarycat to the triage team

- people/liwagu.toml
- teams/ospp-contributors.toml
She is an OSPP mentee
cc @Kobzol
> Add Liwa Gu

- teams/compiler-contributors.toml
Congrats @tgross35!
r? @davidtwco
> Add tgross35 to compiler-contributors

- teams/compiler-contributors.toml
Congrats @camelid!
r? @davidtwco
> Add camelid to compiler-contributors

- people/lukas-code.toml
- teams/compiler-contributors.toml
Congrats @lukas-code!
r? @davidtwco
> Add lukas-code to compiler-contributors

- people/Zalathar.toml
- teams/compiler-contributors.toml
Congrats @Zalathar!
r? @davidtwco
> Add Zalathar to compiler contributors

- teams/archive/wg-rfc-2229.toml
cc @nikomatsakis @matthewjasper @rust-lang/wg-rfc-2229
> Archive wg-rfc-2229.

- people/alex-semenyuk.toml
- teams/wg-triage.toml
> Add alex-semenyuk to wg-triage team

- teams/libs-contributors.toml
Welcome @ibraheemdev!
cc @rust-lang/libs @rust-lang/libs-contributors
> Add ibraheemdev to libs-contributors

- people/ChayimFriedman2.toml
- teams/rust-analyzer-contributors.toml
> Add myself to rust-analyzer-contributors

- teams/archive/twitter.toml
- teams/twitter.toml
Superseded by the social-media team.
> Archive twitter marker team.

- teams/rustup.toml
We'd like to add @ChrisDenton to the rustup team.
cc @rbtcollins @rami3l
> teams: add ChrisDenton to t-rustup

- teams/project-const-generics.toml
@camelid has been doing a lot of work on `min_generic_const_args` lately. r? @lcnr
> Add camelid to project-const-generics

- teams/wg-macros.toml
@tgross35 is doing a tremendous amount of work around the macros subsystem at the level of design. 
We had a full open discussion on stuff that was already studied by Trevor.
So with this PR, I am proposing to add him to the wg team
cc @rust-lang/wg-macros
> macros: add Trevor to the wg-macros

- people/rmsyn.toml
- teams/wg-embedded-riscv.toml
Per https://github.com/rust-embedded/wg/pull/795
> Add @rmsyn to embedded WG riscv team

- teams/bootstrap.toml
@jieyouxu is now part of Bootstrap Team!
> add jieyouxu to Bootstrap Team

- people/jkelleyrtp.toml
This will make project goals pings notify @jkelleyrtp in https://rust-lang.zulipchat.com/#narrow/channel/435869-project-goals/topic/Ergonomic.20ref-counting.20.28goals.23107.29
> add jonathan kelley's zulip id to enable project goals pings

- people/bdillo.toml
- teams/twir-reviewers.toml
We have a new This Week in Rust editor!
> adds bdillo as a new twir reviewer

- people/berkus.toml
- people/nchong-at-aws.toml
- teams/wg-embedded-cortex-a.toml
https://github.com/rust-embedded/wg/pull/655
https://github.com/rust-embedded/wg/pull/801
https://github.com/rust-embedded/wg/pull/687
> Embedded WG: Add berkus and nchong to cortex-a, retire andre-richter

- repos/rust-lang/miri.toml
> Miri: allow self-approval

- people/samueltardieu.toml
- teams/clippy-contributors.toml
Welcome to the regular Clippy contributors @samueltardieu :tada: :confetti_ball: :paperclips: 
---
r? @flip1995 || @Manishearth 
cc: @rust-lang/clippy @rust-lang/clippy-contributors
> Add @samueltardieu as a Clippy contributor :paperclip: :tada:

- teams/fuchsia.toml
> Retire @djkoloski from Fuchsia team

- teams/emscripten.toml
- teams/wasi.toml
- teams/wasm.toml
Hello there! I'd love to contribute here. I am already member of Rust team.
> Adding myself (burakemir) to wasm,wasi,emscripten notification group.

- repos/rust-lang/blog.rust-lang.org.toml
Requested [here](https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/main.20rust.20blog.20policy/near/481347022).
> Add permissions for the release team to merge blog PRs

- teams/compiler.toml
cc rust-lang/blog.rust-lang.org#1430
Congrats to @ChrisDenton, @m-ou-se, @rcvalle and @workingjubilee!
> compiler: add new team members

- repos/rust-lang/stdarch.toml
Related to https://github.com/rust-lang/stdarch/pull/1683
Discussed in [zulip](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Merge.20queue.20for.20stdarch)
> rename stdarch ci-check

- teams/project-trait-system-refactor.toml
> add lqd to the trait-system-refactor-initiative

- teams/spec.toml
> Add niko to spec team

- teams/cargo.toml
cc @rust-lang/cargo @Rustin170506
> Add Rustin to the cargo team

- teams/rust-analyzer-contributors.toml
- teams/rust-analyzer.toml
> Add @ChayimFriedman2 to rust-analyzer main team

- repos/rust-lang/cc-rs.toml
> Add required ci check for cc-rs

- repos/rust-lang/rust-clippy.toml
> Clippy: make the changelog workflow mandatory

- people/marcoieni.toml
- teams/infra-admins.toml
- teams/infra.toml
The validation is complaining about the case change on this username. I didn't even know it was possible to change your username like that.
> Fix marcoieni username change

- teams/release.toml
I haven't been active on the release team in awhile. It's time to reflect that.
cc @Mark-Simulacrum @rust-lang/release
> Move tmandry to release-team alumni

- repos/rust-lang/discord-mods-bot.toml
Change perms from write to maintain and change team from mods-discord to mods only
> Update discord-mods-bot repo perms

- people/1c3t3a.toml
As a follow-up to https://github.com/rust-lang/team/pull/1661 :)
cc @nikomatsakis.
> Add my Email and Zulip ID

- people/LFS6502.toml
- teams/wg-triage.toml
> Add LFS6502 (myself) to people and wg-triage

- repos/rust-lang/crates.io.toml
r? @rust-lang/team-repo-admins
> crates.io: Adjust `ci-checks` list

- .github/workflows/dry-run.yml
> Fix cargo build in dry run workflow

- people/ZuseZ4.toml
- people/jdonszelmann.toml
- teams/compiler.toml
Congrats @Kobzol, @jdonszelmann and @ZuseZ4! 🎉 
r? @davidtwco
> Add new compiler team members

- teams/clippy.toml
I've decided to leave the Clippy team. Thank you for everyone who has been part of my journey to this point! :heart:
> Graduate `@xFrednet` from Clippy and Rust

- people/dianqk.toml
- teams/compiler.toml
- teams/icebreakers-llvm.toml
- teams/wg-llvm.toml
- teams/wg-mir-opt.toml
This is the pinyin abbreviation of the Chinese pen name (靛青 K) when I was a child. Typing `DianQK` might be a bit troublesome, so I lowercase it to `dianqk`.
For this, I added an English name: Quentin Dian, I feel this makes the problem worse, my Chinese name is Xutao Song. I think you can call me dianqk or any combination of the above.
> Lowercase `DianQK` to `dianqk`

- .github/workflows/dry-run.yml
See https://github.com/rust-lang/team/pull/1686#issuecomment-2735845578.
> Disable sending dry-run PR comments temporarily

- people/P1n3appl3.toml
- teams/fuchsia.toml
I'm no longer on the Fuchsia team.
(also updated my name/email)
> Remove P1n3appl3 from fuchsia maintainers

- .github/workflows/dry-run.yml
Hopefully shouldn't spam anymore after https://github.com/rust-lang/sync-team/pull/128.
> Re-enable dry run comments

- teams/clippy-contributors.toml
- teams/clippy.toml
From the clippy-contributors team. Welcome to the main team!
cc @rust-lang/clippy @samueltardieu
> Move samueltardieu to the Clippy team

- teams/wg-embedded-arm.toml
- teams/wg-embedded.toml
Per https://github.com/rust-embedded/wg/pull/824
> Add @jonathanpallant to wg-embedded-arm team

- teams/style.toml
It was fun while it lasted, but I'm having trouble finding the commitment that the team needs! I'm always around if you need T-compiler help.
> Remove compiler-errors from t-style

- teams/triagebot.toml
@Urgau has been doing a lot of great work on triagebot recently.
> Add Urgau to t-triagebot

- sync-team/src/github/api/mod.rs
- sync-team/src/github/api/read.rs
- sync-team/src/github/api/write.rs
- sync-team/src/github/mod.rs
This should unblock https://github.com/rust-lang/team/pull/1463.
> Sync GitHub App branch protection push allowances

- sync-team/src/github/mod.rs
This problem occurred in https://github.com/rust-lang/team/pull/1736.
> Change repository sync order to handle archiving

- sync-team/src/github/mod.rs
To make the rust-lang/rust branch protections closer to their original state. Should help if bors merges fail after the migration of rust-lang/rust under `team`.
> Do not require PRs for branches managed by homu

- people/PartiallyUntyped.toml
I've tried updating this GH user, a validation error came while I was doing unrelated changes in #1763
Can you check  @partiallyuntyped if everything correct?
> Update GH user

- teams/relnotes-interest-group.toml
I'm interested in commenting on the release notes.
> Add kobzol to relnotes-interest-group

- people/ernestkissiedu.toml
> update ernestkissiedu emai

- teams/compiler-fcp.toml
- teams/compiler.toml
Thanks for all of your work @jieyouxu!
r? @davidtwco
> Make jieyouxu a Compiler Maintainer

- repos/archive/rust-analyzer/WG-rls2.0.toml
- repos/archive/rust-analyzer/lsp-server.toml
- repos/archive/rust-analyzer/ra_vfs.toml
- repos/archive/rust-analyzer/rust-project.json-example.toml
- repos/archive/rust-analyzer/salsa.toml
- [WG-rls2.0](https://github.com/rust-analyzer/WG-rls2.0)
```toml
org = "rust-analyzer"
name = "WG-rls2.0"
description = "Home for rls2.0 working group"
bots = []
[access.teams]
Xanewok = "admin"
lnicola = "admin"
Veykril = "admin"
flodiebold = "admin"
matklad = "admin"
MissHolmes = "admin"
skade = "admin"
```
</details>
- [lsp-server](https://github.com/rust-analyzer/lsp-server)
```toml
org = "rust-analyzer"
name = "lsp-server"
bots = []
[access.teams]
triage = "triage"
Xanewok = "admin" …
```
> Backport archived Rust Analyzer repos

- repos/archive/rust-lang-nursery/clang.toml
- repos/archive/rust-lang-nursery/multirust-rs-binaries.toml
- repos/archive/rust-lang-nursery/rust-wasm.toml
- repos/archive/rust-lang-nursery/rustc-timing-archive.toml
- repos/archive/rust-lang-nursery/rustc-timing-scripts.toml
- [clang](https://github.com/rust-lang-nursery/clang)
```toml
org = "rust-lang-nursery"
name = "clang"
description = "No longer used, use https://github.com/rust-lang/llvm-project instead"
bots = []
[access.teams]
alexcrichton = "admin"
dtolnay = "admin"
aidanhs = "admin"
jdno = "admin"
nrc = "admin"
aturon = "admin"
huonw = "admin"
sfackler = "admin"
erickt = "admin"
steveklabnik = "admin"
KodrAus = "admin"
tromey = "write"
nikomatsakis-admin = "admin"
```
</details>
- …
> Backport archived rust-lang-nursery repos (batch 1)

- repos/archive/rust-lang-nursery/rustc-timing.toml
- repos/archive/rust-lang-nursery/taskcluster-crater.toml
- repos/archive/rust-lang-nursery/thanks.toml
- repos/archive/rust-lang-nursery/unix-socket.toml
- [rustc-timing](https://github.com/rust-lang-nursery/rustc-timing)
```toml
org = "rust-lang-nursery"
name = "rustc-timing"
description = "Data for timing rustc"
bots = []
[access.teams]
aidanhs = "admin"
erickt = "admin"
KodrAus = "admin"
nikomatsakis-admin = "admin"
alexcrichton = "admin"
nrc = "admin"
steveklabnik = "admin"
huonw = "admin"
aturon = "admin"
jdno = "admin"
arielb1 = "write"
sfackler = "admin"
dtolnay = "admin"
edunham = "admin"
```
</details>
- …
> Backport archived rust-lang-nursery repos (batch 2)

- teams/docker.toml
cc @Kobzol
cc @rust-lang/docker
> chore(docker): Add Kobzol as a member

- teams/wg-diagnostics.toml
- teams/wg-llvm.toml
- teams/wg-prioritization.toml
Updating repository links for some compiler WGs 
r? @ehuss 
thanks
> Update repository links for some compiler WGs 

- teams/wg-secure-code.toml
> Add myself to wg-secure-code

- teams/compiler.toml
- teams/project-negative-impls.toml
- teams/project-vision-doc-2025.toml
Unfortunately I don't have time for this initiative :( and while I was making this change used the opportunity to remove me from t-compiler meeting pings (as I have them calendarized) and to remove me from negative impls as I'm not working on this right now.
> Step down from vision doc

- teams/rustlings.toml
This was changed in Zulip recently.
> Change Rustlings Zulip stream name

- people/0xPoe.toml
- teams/cargo.toml
- teams/crates-io.toml
- teams/rustup.toml
People always ask me about my name, so I figured it was time for a new one. 😆
cc @rust-lang/team-repo-admins
> Update my account information

- people/gstjepan2.toml
- teams/wg-triage.toml
> Added my account information

- teams/infra.toml
Hi :3
r? @jdno (or @shepmaster)
> Add jieyouxu to infra team

- repos/rust-lang/rustlings.toml
Context: https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Rustlings.20Domain
> Update rustlings homepage URL

- repos/archive/rust-analyzer/bonsai.toml
- repos/archive/rust-analyzer/escape-from-rust.toml
- repos/archive/rust-analyzer/mini-rowan.toml
- repos/archive/rust-analyzer/minimal-rust.toml
- repos/archive/rust-analyzer/minirust.toml
- repos/archive/rust-analyzer/renamer.toml
- repos/archive/rust-analyzer/rust-analyzer-wasm.toml
- repos/archive/rust-analyzer/rust-threadpool.toml
- repos/archive/rust-analyzer/teraron.toml
- [bonsai](https://github.com/rust-analyzer/bonsai)
```toml
org = "rust-analyzer"
name = "bonsai"
bots = []
[access.teams]
skade = "admin"
Xanewok = "admin"
lnicola = "admin"
flodiebold = "admin"
MissHolmes = "admin"
Veykril = "admin"
matklad = "admin"
```
</details>
- [escape-from-rust](https://github.com/rust-analyzer/escape-from-rust)
```toml
org = "rust-analyzer"
name = "escape-from-rust"
bots = []
[access.teams]
lnicola = "admin"
Veykril = "admin"
skade = "admin" …
```
> Backport rust-analyzer repos for archival

- teams/wg-llvm.toml
This should allow me to receive ping messages.
Note: This will also remove @dlrobertson and @nikomatsakis.
r? @nikic
> Add the WG-llvm zulip group under automation

- people/PLeVasseur.toml
- teams/project-vision-doc-2025.toml
> Add PLeVasseur to vision doc team

- people/cyrgani.toml
- people/shard77.toml
- people/simbleau.toml
- teams/wg-triage.toml
> Add `shard77`, `cyrgani` and `simbleau` to people and wg-triage team

- repos/archive/rust-analyzer/VsCode-themes.toml
Repo: https://github.com/rust-analyzer/vscode-themes
Decided to archive it, as per [#t-compiler/rust-analyzer > Rust-analyzer org repository access and status](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/Rust-analyzer.20org.20repository.20access.20and.20status/with/515313182).
<details>
```toml
org = "rust-analyzer"
name = "VsCode-themes"
description = "VsCode themes for rust-analyzer"
bots = []
[access.teams]
MissHolmes = "admin"
matklad = "admin"
Xanewok = "admin"
flodiebold = "admin"
davidbarsky = "admin"
lnicola = "admin"
Veykril = "admin"
skade = "admin"
```
</details>
> Add `vscode-themes` under automation and archive it

- src/validate.rs
From https://github.com/rust-lang/team/pull/1861#pullrequestreview-2892136497
It's the second time that this got me :-)
r? @jackh726
> Suggest removing team leads when archiving a team

- teams/bootstrap.toml
- teams/mentors.toml
[#t-infra/bootstrap > stepping down from T-Bootstrap](https://rust-lang.zulipchat.com/#narrow/channel/326414-t-infra.2Fbootstrap/topic/stepping.20down.20from.20T-Bootstrap/with/523501689)
> remove myself from the project

- repos/rust-lang/compiler-builtins.toml
> Enable `rustbot` in `compiler-builtins` repository

- repos/rust-lang/rust-forge.toml
Companion PR to https://github.com/rust-lang/rust-forge/pull/885.
> Add required CI check to Forge

- repos/rust-lang/rust-forge.toml
part of rust-lang/rust-forge#873 I think
> Add the dev guide wg to the forge toml

- teams/wg-gcc-backend.toml
> Add dev desktop permissions to wg-gcc-backend

- repos/rust-lang/bors.toml
https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Migrating.20bors.20try.20to.20new.20bors
> Add `infra-admins` to the `bors` repo

- teams/compiler.toml
Congrats @yaahc!
r? @davidtwco
> Add yaahc to compiler team

- teams/goals.toml
> Remove spastorino from project goals team

- .github/workflows/main.yml
Discussed on Zulip: https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/sync-team.20race.20condition/with/530498875.
> Change cron to only run once per day

- people/purplesyringa.toml
- teams/cloud-compute.toml
I wanted to work on some LLVM features to improve unwinding support on Windows but don't really have enough compute to play around with LLVM. @ChrisDenton told me I could ask for a dev desktop here.
> Add purplesyringa to cloud-compute

- people/zeenix.toml
> Update my info

- teams/spec.toml
We don't really have a true editor right now. So just leveling everything back up.
> t-spec: Remove Joel as editor

- teams/project-vision-doc-2025.toml
This better reflects the activity of the team.
> Update Vision Doc team membership

- people/xizheyin.toml
- teams/wg-triage.toml
I am willing to help the team with issue/pr triage. As suggested by @Dylan-DPC , I submit this PR.
> Add xizheyin to wg-triage

- README.md
In particular https://forge.rust-lang.org/infra/team-maintenance.html#rules-for-changes-to-team-repo.
> Backlink to more team repo docs

- teams/wg-bindgen.toml
I have not contributed for over a year now, so am placing self on alumni to better reflect reality.
> remove tshepang from wg-bindgen

- teams/wg-embedded.toml
Per https://github.com/rust-embedded/wg/pull/831
> Add @robamu to embedded arm team

- people/Osintedx.toml
- people/theemathas.toml
- teams/wg-triage.toml
> Add `Osintedx` and `theemathas` to WG-triage

- teams/community.toml
As per discussion here https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/All.20Hands.20old.20mailing.20list/with/536908173
> Remove old All Hands mailing list

- teams/rustdoc.toml
I've been meaning to do this for a while as I haven't really been finding the time to contribute anymore.
cc @rust-lang/rustdoc
> move Nemo157 to rustdoc alumni

- people/ranger-ross.toml
> Added zulip-id and email for ranger-ross

- teams/leadership-council.toml
cc @rust-lang/leadership-council @Kobzol
> Add Kobzol to the leadership-council

- people/jonathanpallant.toml
- src/validate.rs
And change Zulip ID for `jonathanpallant`, as per https://github.com/rust-lang/team/issues/1987#issuecomment-3315934193.
Fixes: https://github.com/rust-lang/team/issues/1987
> Ensure that Zulip user IDs are unique

- Cargo.lock
- Cargo.toml
- src/static_api.rs
- tests/snapshot.rs
Fixes: https://github.com/rust-lang/team/issues/1985
> Make the output of the static API deterministic

- people/amanjeev.toml
- teams/wg-rustc-dev-guide.toml
Hey good folks of Rust lang team!
I am back!
> Re-add Amanjeev Sethi to dev guide team

- repos/rust-lang/www.rust-lang.org.toml
https://github.com/rust-lang/www.rust-lang.org/pull/2205
> Change default branch of www.rust-lang.org to `main`
