people/Dylan-DPC.toml
people/codesections.toml
people/epage.toml
people/matthiasbeyer.toml
teams/wg-cli.toml

This PR adds a bunch of members from the CLI-WG as regular members.
Don't merge this yet before everybody has had a chance to update
their information to their liking.
Pinging @killercup retroactively

Initially adding contributers to the cli-wg

---

people/alercah.toml
people/brson.toml
teams/alumni.toml
teams/reference.toml

Per their requests, this should stop them from getting mail from the `all@` mailing list:
- clear the e-mail fields from their people files
- in the case of @alercah, move from reference to alumni (I believe this is correct)
(cc @brson, @alercah, @steveklabnik)

stop brson, alercah from getting mail

---

people/Khionu.toml
people/notriddle.toml
teams/mods-discord.toml
teams/mods-discourse.toml
teams/mods.toml

This adds a subteam to the mod team for Discord moderation. It also moves the mod team off the old Google Group and onto using a regular Rust mailing list, so as to centralize everything into the teams repo.
r? @rust-lang/moderation

Add discord moderation subteam, fix mods mailing list

---

people/marioidival.toml
people/projektir.toml
teams/docs.toml
teams/rust-by-example.toml

Add missing information of Rust By Example on team references
[old site](https://prev.rust-lang.org/en-US/team.html#Documentation-peers)
https://github.com/rust-lang/rust/blob/master/src/tools/publish_toolstate.py#L24

Add Rust By Example

---

rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/cargo.toml
teams/compiler.toml
teams/core.toml
teams/crates-io.toml
teams/devtools.toml
teams/docs.toml
teams/ides.toml
teams/infra.toml
teams/lang.toml
teams/libs.toml
teams/mods.toml
teams/release.toml
teams/rustdoc.toml

This PR adds the data needed to integrate rfcbot with the repo in the Team API. The actual integration still needs to be done.
cc @Centril @anp

Add rfcbot data to the Team API

---

teams/devtools.toml

Dale stepped down, so Eric will be representing Cargo, and Daniel will represent Rustup
r? @killercup

Add kinnison and ehuss to devtools

---

teams/compiler.toml

This is presently an alias for compiler@rust-lang.org -- except that it includes only active members. It will be used to make membership decisions only.

add a compiler-private mailing list

---

people/CAD97.toml
teams/wg-grammar.toml

Looks like we probably want to add at least @eddyb as well, potentially @matklad

Add self to wg-grammar

---

people/Xanewok.toml
people/flodiebold.toml
people/lqd.toml
people/matthewjasper.toml
people/nikic.toml
people/nnethercote.toml
people/scalexm.toml
people/tmandry.toml
people/wesleywiser.toml
people/zackmdavis.toml
teams/compiler-contributors.toml
teams/compiler.toml

Contributors are added to the compiler-team mailing list, as well.
One question mark: I would like to tweak how the github teams are setup, but I'm not sure if that is controlled by this repository. I *think* I would prefer to have @rust-lang/compiler include the contributors, and to have some subteam to distinguish "full members" (I believe that is what I specified in the RFC). 
cc @rust-lang/compiler 

create the "compiler contributors team" and populate it

---

people/ehuss.toml

Since they often do docs submodule updates and they are helpful with reviewing libstd docs improvements.

Grant ehuss rust-lang/rust r+ rights

---

people/mgattozzi.toml
teams/community-events.toml
teams/community-rustbridge.toml
teams/community-survey.toml
teams/wg-governance.toml
teams/wg-wasm.toml

I haven't contributed in a while for some of these groups and I'm
scaling down my contributions to open source for a variety of personal
reasons including mental health. This commit removes every reference to
me in the repo.

Remove mgattozzi from working groups and teams

---

config.toml
docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/release.toml

This PR is the first step of the synchronization of GitHub teams with the team repo. This adds all the relevant fields to the schema and the API, and "enables" synchronization for the release team (chosen because it's already synchronized so no accidental changes will be applied to GitHub).
After the PR is merged the next steps are sending a PR to the central station adding the synchronization tool (already working in a local branch), creating a bot account to do the work and then enabling synchronization for all teams. The last step will require coordination with the team leads to make sure no unwanted changes are applied.
cc #2

Add GitHub teams in the schema and the API

---

teams/infra.toml

This adds all people with full access to the infra to the `admin@` mailing list (and related ones).
cc @aidanhs @Mark-Simulacrum 
r? @alexcrichton 
closes https://github.com/rust-lang/team/pull/82

Add people with full access to the admin infra mailing lists

---

README.md

It's finally running :tada: 
cc https://github.com/rust-lang/team/issues/2

Add GitHub teams sync to the README

---

teams/cargo.toml

Changes to the teams that are going to be applied:
```
rust-lang/cargo: user wycats is not in the team anymore, removing them...
rust-lang/cargo: user dwijnand is not in the team anymore, removing them...
rust-lang/cargo: user Xanewok is not in the team anymore, removing them...
rust-lang-nursery/cargo: user ehuss is missing, adding them...
rust-lang-nursery/cargo: user nrc is missing, adding them...
rust-lang-nursery/cargo: user Eh2406 is missing, adding them...
rust-lang-nursery/cargo: user withoutboats has the role maintainer instead of member, changing them...
rust-lang-nursery/cargo: user carols10cents is not in the team anymore, removing them...
rust-lang-nursery/cargo: user matklad is not in the team anymore, removing them...
rust-lang-nursery/cargo: user aturon is not in the team …
```

Sync the cargo team with GitHub

---

teams/compiler-contributors.toml
teams/compiler.toml

Changes to the teams that are going to be applied:
```
rust-lang/compiler: user michaelwoerister has the role maintainer instead of member, changing them...
rust-lang/compiler: user jseyfried is not in the team anymore, removing them...
rust-lang/compiler: user arielb1 is not in the team anymore, removing them...
rust-lang-nursery/compiler: user cramertj is missing, adding them...
rust-lang-nursery/compiler: user nrc is not in the team anymore, removing them...
rust-lang/compiler-contributors: user davidtwco is missing, adding them...
rust-lang/compiler-contributors: user flodiebold is missing, adding them...
rust-lang/compiler-contributors: user lqd is missing, adding them...
rust-lang/compiler-contributors: user matklad is missing, adding them...
rust-lang/compiler-contributors: user …
```

Sync the compiler and compiler-contributors teams with GitHub

---

people/birkenfeld.toml
people/flip1995.toml
people/matthiaskrgr.toml
people/mcarton.toml
people/mikerite.toml
people/phansch.toml
people/yaahc.toml
teams/alumni.toml
teams/clippy.toml

We don't use the clippy "team" much for anything special, but folks with review should be on it, they all deserve it :)
This also moves @birkenfeld to alumni since he's been inactive for two years, but he's free to rerequest r+ whenever he wishes.
This also adds @yaahc to the team/reviewers, she's been doing excellent work on the cargo side lately and should be a part of this.
r? @oli-obk

Move clippy reviewers to team, add Yaah, remove Georg

---

people/otavio.toml
teams/wg-rustfmt.toml

This will create a new `wg-rustfmt` team in the `rust-lang` GitHub organization with nrc, otavio, scampi and topecongiro. Then we should configure the rustfmt repo to authorize the team instead of individual members.
@topecongiro is the list of the members of the wg still accurate? otavio doesn't have write perms on the rustfmt repo anymore.

Synchronize wg-rustfmt with GitHub teams

---

teams/wg-embedded-resources.toml

Hopefully this satisfies the requirements of
https://github.com/rust-lang/rust/pull/64119

Added embedded-resources subteam

---

docs/toml-schema.md
src/schema.rs
teams/compiler-contributors.toml

This PR includes compiler team members on the `compiler-contributors` team on GitHub. This allows them to be mentioned along with the contributors, and to publish packages on crates.io owned by the contributors team.

Include compiler team members on @rust-lang/compiler-contributors

---

teams/rust-by-example.toml

This will create a new `rust-by-example` team in the `rust-lang` GitHub organization with steveklabnik and marioidival. Then we should configure the rust-by-example repo to authorize the team instead of individual members.
r? @steveklabnik

teams/rust-by-example: synchronize with GitHub

---

teams/crates-io.toml

This PR will synchronize the `crates-io` Rust team with the `@rust-lang/crates-io` GitHub team. Differences that are going to be fixed once the PR is merged:
```
user Turbo87 is missing, adding them...
user smarnach is missing, adding them...
user steveklabnik is missing, adding them...
user locks is missing, adding them...
user wycats is not in the team anymore, removing them...
```
r? @sgrif

Synchronize crates-io with GitHub

---

teams/core.toml

This can be changed in the future, but I believe these concerns are best handled in the team with easiest access to legal advice, as competently answering such request might involve it.

Add privacy@rust-lang.org, forwarding to core

---

teams/security.toml

This adds the security team to the governance section of the website and enables synchronization with GitHub's `@rust-lang/security`.
Fixes https://github.com/rust-lang/security-team/issues/4
r? @alexcrichton

Add website and GH sync for the security team

---

rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs

Infra work for https://github.com/rust-lang/team/pull/123

Add Marker teams setup

---

teams/icebreakers-llvm.toml

We've [discussed on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta) about adding icebreakers-llvm as a team with minimal everything (no github, no website) as can be seen on the toml file, instead of doing this as a working group.
From what we've quickly seen on team repo by doing what I've done in the PR this group would end included in `all@`. What would be the best way to avoid that?.
/cc @nikomatsakis @pietroalbini @Mark-Simulacrum (this is also related to https://github.com/rust-lang/triagebot/issues/169)

Add icebreakers-llvm team

---

teams/crates-io.toml
teams/infra-admins.toml

As we discussed in the last crates.io meeting, this PR:
* Adds all team members to `crates-io@rust-lang.org`, while keeping the existing list of members in `help@crates.io`
* Moves `admin@crates.io` with the other infra-admins mailing lists, updating its membership to be infra team members with "sensitive access".
r? @sgrif

Change crates.io mailing lists

---

teams/wg-gamedev.toml

The gamedev WG has a channel on the official Rust Discord - figured it'd be a good idea to add it here too :)

Add gamedev working group discord link

---

teams/rustdoc.toml

cc #146
I checked the Rustdoc team listings for the rust-lang and rust-lang-nursery orgs, and it looks like they've gone out of sync. I've updated the rust-lang one manually, but i don't have Maintainer status on the rust-lang-nursery one, so i'm counting on this update to fix that for me.

add github team sync to rustdoc team

---

teams/reference.toml
teams/wg-gamedev.toml

Some occurrences of "Rust" were not capitalized

fixed types in Reference and Gamedev wg TOML files

---

people/ecstatic-morse.toml
teams/compiler-contributors.toml

They're working to make compile-time evaluation more expressive by enabling `if`, `match` and other control flow in constants. As one of their first major contributions, they implemented a dataflow analysis to validate the bodies of `const`s and `const fn`s (rust-lang/rust#64470).
Congratulations @ecstatic-morse, and thanks!
cc @rust-lang/compiler

add escstatic-morse to compiler contributors

---

people/nasa42.toml

I'd prefer to publicise my Gmail email address for Rust team discussions.

Update nasa42's email

---

people/smarnach.toml

@sgrif This change gives me `bors r+` permissions for crates.io.

Give smarnach bors permissions on crates.io.

---

teams/docsrs-ops.toml

This team (synchronized with GitHub) is a marker team as it doesn't
represent any team in our structure, but it's used to grant people
involved with docs.rs operations access to some parts of our infra.

create the docsrs-ops marker team

---

people/jryans.toml
teams/icebreakers-llvm.toml

I am interested in following the issues Rust hits with LLVM and hopefully helping out with some where possible.

Add jryans to LLVM ICE-breaker group

---

teams/wg-security.toml

We noticed this in the core team triage, the team isn't a decisionmaking team and should be classified as a WG.

Make the security team a WG

---

teams/compiler.toml

This PR makes official what has been true for some time, by adding @pnkfelix as the @rust-lang/compiler team co-lead. Felix was a "founding member" of the compiler team when it first started, and was involved with Rust long before that. For the last year or so, he's been taking over an increasingly large share of "compiler team leadership", including running the weekly triage meeting and generally tending to the quality of the compiler as a whole. So many thanks to @pnkfelix for all that he does, and congratulations! 🎉

add pnkfelix as compiler team co-lead

---

teams/alumni.toml
teams/lang-shepherds.toml
teams/lang.toml

This synchronizes @rust-lang/lang as defined on team with the github repository.
This will cause
* @huonw
* @solson
to be removed, and @scottmcm to be added.
I'm also removing the shepherds subteam, as it is not really the way we're operating anymore. (I've discussed this with the participants / lang-team already.)
cc https://github.com/rust-lang/wg-governance/issues/21

sync lang team

---

teams/wg-security-response.toml
teams/wg-security.toml

Followup to https://github.com/rust-lang/team/pull/165
This PR changes the name of the website to be "Security WG", to reflect the WG name. I sort of feel like the name is too vague though, as our scope is just responding to vuln reports. Maybe let's rename ourselves to "Security Response WG"? @rust-lang/wg-security

wg-security: update names on the website

---

teams/infra.toml

This PR removes @ashleygwilliams from the infra team, as she doesn't have the time anymore to contribute to infra. Thanks Ashley for all you did!
Now that the members list reflects the actual memberships, this PR also enables synchronization with GitHub.
r? @aidanhs

infra: remove Ashley and synchronize with GitHub

---

people/jyn514.toml
teams/docs-rs.toml
teams/docsrs-ops.toml
teams/rustdoc.toml

This PR officially creates a new team, the Docs.rs Team, by formally splitting off the responsibilities from the existing Rustdoc Team. While some feature development may have some overlap between these two products, they wind up having totally separate responsibilities in the end.
This creates the following structure:
* Rustdoc Team (parent team: Dev-Tools)
* @GuillaumeGomez (lead)
* @QuietMisdreavus
* @ollie27
* @kinnison
* Docs.rs Team (parent team: Dev-Tools)
* @QuietMisdreavus (lead)
* @onur
* @pietroalbini
* @jyn514
One open question i'd like to pose is what team the Docs.rs team should be child of. I placed it under Dev-Tools since it's splitting off from Rustdoc, and that's where Rustdoc is currently placed, but it doesn't ultimately seem like the right place for it. The best …

spin off docs.rs team from rustdoc team

---

people/acfoltzer.toml
teams/wg-ffi-unwind.toml

For now, we have to use the wg- prefix because team repo has to be
taught about project groups.
cc @BatmanAoD @acfoltzer

add ffi-unwind project group

---

teams/core.toml

This excludes "observers", and is analogous to `lang-private` and other such lists.

create a `core-private` mailing list

---

people/valgrimm.toml
teams/wg-governance.toml

This PR 
* Adds @valgrimm to the governance wg, as they've been quite active lately 🎉 
* Replaces @skade as lead with @XAMPPRocky and myself, as @skade has been busy of late and we've been kind of carrying that ball

Wg governance update

---

teams/wg-cli.toml

I'm no longer an active member in the CLI working group, so it doesn't make sense to keep this.

Remove myself from the CLI-WG roster

---

people/BatmanAoD.toml

Since 'batmanaod' is already visible as the name of my GitHub profile, and since other team members have their real names listed, I would like to use my real name as well.

Use my real name on the Rust website

---

docs/toml-schema.md
people/Mark-Simulacrum.toml
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs

This will be used by triagebot for authentication; we also provide a mapping
from Zulip ID to the GitHub user ID which is the canonical "identifer" of a
person in the Rust organization.

Add zulip ID field to people

---

people/ehuss.toml
teams/cargo.toml

It looks like I don't have r+ any more on rust-lang/rust, but it would
still be pretty useful to have. I think Cargo folks in general should
probably have r+ anyway to do things like submodule updates as well.

Give the Cargo team r+ rights on rust-lang/rust

---

teams/core.toml

While looking through github's teams I noticed that the core team permissions aren't synced between rust-lang/team and GitHub. I'm not sure if this is intentional, but it seems like an oversight.

Sync Core Team Permissions

---

people/RalfJung.toml
teams/miri.toml

Cc @oli-obk 
t-compiler also has Miri r+ rights, and I guess there is no good reason to change that. Still, saying that Miri is a subteam of t-compiler is kind-of arbitrary. Does it matter much?
I was not sure about the `repo` key, as Clippy doesn't have it.

add Miri team consisting of Oli and me

---

teams/miri.toml

I *think* this is what @XAMPPRocky [asked me to do](https://github.com/rust-lang/team/pull/262#discussion_r384749112), but it is not clear at all to me. https://github.com/rust-lang/team/issues/146 lists a dozen things to do and most of them make no sense as the team doesn't exist yet and I have no admin powers.

teams/miri: add github clause

---

teams/lang.toml

For quite some time now, eddyb has narrowed their focus to compiler team projects (as well as targeted involvement in specific areas, like compile team evaluation). This PR makes that official by moving eddyb to alumni status in the lang team. We'll miss you, @eddyb! ❤️

remove eddyb from active lang team duty

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/alumni.toml

This PR adds support for declaring team alumni, which will be properly shown on the website. Team alumni will be automatically included in the `alumni` team. Team alumni will be included in the API.
r? @XAMPPRocky

Add support for declaring team alumni

---

teams/community-content.toml
teams/community-localization.toml
teams/crates-io.toml

`#crates-io` and `#content` were renamed, `#localization` was archived.

Update Discord channels

---

teams/web-presence.toml

This adds the web-presence@rust-lang.org mailing list, and it intentionally doesn't include any other information. Memberships, leads and presence on the website will be added later.
r? @Manishearth

Add mailing list for the Web Presence team

---

teams/reference.toml

As requested by @XAMPPRocky...
The docs team is no more, so https://github.com/rust-lang-nursery/reference/ is probably under T-Lang's responsibility (spec and all...).
These days, most work & reviewing is being done by myself and @ehuss.

reflect reality wrt. the reference

---

teams/compiler.toml

They're not active in compiler team development anymore. Thanks to both of you for everything. ❤️ 
cc @cramertj, @michaelwoerister

move cramertj and michaelwoerister to alumni

---

src/main.rs

Rather than random HashSet order. This matches the sorting done in dump-permission and makes it somewhat easier to visually scan and diff.

Return dump-team and dump-list in sorted order

---

people/Areredify.toml
people/MarkMcCaskey.toml
teams/wg-traits.toml

Recognizing active folks:
* Promoting @jackh726 to co-lead, since they've been doing a lot of great work organizing and mentoring
* Adding @flodiebold, @Areredify, and @MarkMcCaskey in recognition of their contributions
Yay! 🎉

update wg-traits roster

---

teams/core-observers.toml

This will create a core-observers GitHub team, allowing to give permissions to them without granting individual access.

Create core-observers GitHub team

---

people/taiki-e.toml
teams/wg-async-foundations.toml

@taiki-e has been maintaining pin-utils, and is also the author of the pin-project crate.

Add @taiki-e to wg-async-foundations

---

teams/alumni.toml
teams/community-content.toml
teams/twir.toml

We should let people know not to use the `alumni.toml`.

Add alumni team deprecation notice and fix changes from #337

---

people/fmoko.toml
teams/alumni.toml
teams/community.toml

I'm retiring from the community team, this change formalizes that.
The future of the RustBridge team (which I lead) is currently unclear, so I'm not touching it yet, that'll go in a separate PR.
cc @rust-lang/community

Move fmoko to alumni

---

people/jtgeibel.toml
people/pietroalbini.toml

Following the instructions for [obtaining a discord user id], I looked up values for our `discord-id`s.
[obtaining a discord user id]: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-

Add discord ID for jtgeibel and pietroalbini

---

teams/wg-const-eval.toml

...with @oli-obk and @RalfJung as co-leads and myself as a member. I don't think this implies any additional level of commitment from the two leads, it's just a reflection of seniority.
We might need to block this on me reviving rust-lang/compiler-team#201? Not sure what the process is here.
r? @XAMPPRocky 
(since they requested this on Zulip)

Add `wg-const-eval` team

---

people/apiraino.toml
people/o0Ignition0o.toml
teams/wg-prioritization.toml

Adds @apiraino, @o0Ignition0o and @mark-i-m to the Prioritization WG.
cc @spastorino for approval.

Add members to the Prioritization WG

---

teams/website.toml

This is mostly to get a GitHub team we can synchronize permissions with. We'll add it to the website along with the Web Presence team in the future.
r? @Manishearth

Add website team

---

teams/wg-embedded.toml

James Munns stepped down from the embedded WG leadership and Adam Greig
will take over.
CC https://github.com/rust-embedded/wg/pull/463

Reflect embedded WG leadership change

---

teams/mods.toml

This was never intended to be permanent, it was a transition thing as I was setting up the discourse/discord moderation.

Remove Manishearth from mods-all

---

people/denisvasilik.toml
people/tblah.toml
teams/risc-v.toml

cc @denisvasilik @Disasm
On https://github.com/rust-lang/rust/pull/72973 @nikomatsakis  suggested creating a RISC-V group (similar to the ARM and Windows groups). 

Add RISC-V group

---

people/jyn514.toml
teams/rustdoc.toml

* @jyn514 has been contributing a lot (even more recently) on rustdoc since they started working on `docs.rs`.
* @Manishearth has been contributing to rustdoc for years, the list of their contributions is already quite huge.
I think they will both bring a lot more of new things into rustdoc.
Do you approve their integrations @rust-lang/rustdoc?

Add jyn514 and Manishearth to the rustdoc team

---

teams/wg-diagnostics.toml

Manage diagnostics working group here like other WGs based on the discussion on Zulip. Member list is taken from the current GitHub team + me, the leads are from https://rust-lang.github.io/compiler-team/working-groups/diagnostics/.
cc @rust-lang/wg-diagnostics

Add diagnostics working group

---

people/rust-timer.toml

This should be sufficient to start working towards automated anti-perf sensitive
rolling up.

Grant rust-timer try permissions on rust-lang/rust

---

src/permissions.rs
teams/wg-traits.toml

As a preliminary for getting bors set up in the chalk repo.

Update wg-traits review permissions

---

people/lenary.toml
teams/risc-v.toml

I work on the RISC-V LLVM backend, at lowRISC (we are the official maintainers). It is useful to be tagged on bugs which may need upstream fixes, or reviews around expected functionality of the backend - this allows me to prioritise fixes.
I'm not sure who I should be cc'ing on this PR.

Add @lenary to RISC-V team

---

teams/clippy.toml

@flip1995 has been doing a lot of great maintenance work in Clippy, organizing reviewers, helping grow new reviewers, etc. I'd like to promote them to being Clippy co-lead.
@oli-obk has stated they don't have bandwidth to give clippy leadership justice; retiring them back to being a "normal" team member. Thanks for everything, Oli!
cc @rust-lang/clippy

Add flip1995 as Clippy co-lead, move Oli back to a regular team member

---

teams/rustdoc.toml

I am not really in a position to continue as an active member of the rustdoc team for now.  I have limited free software time and it's all focussed on rustup.  This was agreed with @GuillaumeGomez and @Manishearth as likely the best path for now.

teams/rustdoc: Retire Kinnison (for now)

---

teams/inside-rust-reviewers.toml

This PR adds the `inside-rust-reviewers` marker team, which is composed by all team leads and project group leads. This is part of the work needed to address https://github.com/rust-lang/core-team/issues/18.
I chose to create a dedicated "reviewers" marker team instead of creating a `project-group-leads` team because that allows adding extra people as reviewers without having to change the CODEOWNERS file on the blog.

Add the inside-rust-reviewers marker team

---

teams/rustdoc.toml

Left over from https://github.com/rust-lang/team/pull/182, I noticed it in https://github.com/rust-lang/rust/issues/75619#issuecomment-677641995.

Note that rustdoc does not manage docs.rs

---

teams/clippy.toml

cc @flip1995 
Refer to https://github.com/rust-lang/rust-clippy/issues/5943#issuecomment-693735771
Moving from Discord to Zulip was discussed at https://github.com/rust-lang/rust-clippy/issues/5943 and new stream in Zulip has been already created.

Replace Discord with Zulip in clippy team

---

teams/libs.toml

I _think_ this should add a @BurntSushi checkbox to FCPs without returning them to the `r?` rotation?
cc @Mark-Simulacrum @BurntSushi

Add BurntSushi back to FCP list

---

people/KodrAus.toml
people/calebzulawski.toml
people/hsivonen.toml
people/workingjubilee.toml
teams/project-portable-simd.toml

Adds the Portable SIMD project group team.
Links
- https://github.com/rust-lang/rfcs/pull/2977
- https://github.com/rust-lang/libs-team/issues/4

Add the portable SIMD project group team

---

teams/release.toml

I have been shifting my focus to other efforts lately, and I now have a conflict during the Release team's weekly meeting, so I think it's best if I no longer be considered an official Release team member.

Remove myself from Release team

---

src/main.rs
src/schema.rs
src/static_api.rs

Found in #452, opening in another PR not to block this minor fix.

Fix `clippy::stable_sort_primitive` warnings

---

people/gnzlbg.toml
people/malbarbo.toml
teams/libc.toml

So, we now need to use bors on libc as the number of GHA jobs is large (https://github.com/rust-lang/libc/pull/1918#issuecomment-707140018). And as suggested in #444, I set up libc team to give us bors permission.
I'm not sure, but I think it's worth adding the GitHub team as well for the repository perms.
Closes #444
cc @joshtriplett and @pietroalbini

Set up libc team to give members bors perms

---

teams/lang-docs.toml

It should've been `t-lang/doc`, sorry for the trouble.

Fix Zulip stream name

---

teams/library-reviewers.toml

Member list is taken from: https://github.com/rust-lang/highfive/blob/4420ccbffd38c700dbcfd3fb943f8b5ab53ee10d/highfive/configs/rust-lang/rust.json#L7-L9
The current list in this commit all already have at least these permissions.
- via libs team: dtolnay, KodrAus, LukasKalbertodt, sfackler, withoutboats
- via lang team: cramertj, joshtriplett
- via infra team: kennytm, Mark-Simulacrum, shepmaster
However, I am hoping to add another standard library reviewer who is not already in one of the other teams with review permission.

Add library-reviewers team with rust-lang/rust review permission

---

src/data.rs
src/schema.rs
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/alumni.json
tests/static-api/_expected/v1/teams/wg-test.json
tests/static-api/people/user-4.toml
tests/static-api/people/user-5.toml
tests/static-api/teams/alumni.toml
tests/static-api/teams/wg-test.toml

There are some members of the Rust project that retired from one team but are still active in other teams. Before this commit they were listed in the "alumni" page, as they were marked as alumni of the team they retired of, but that didn't feel right as they haven't fully left the project.
This PR excludes members that are active in any team from being listed in the alumni team, even if they are alumni of one team.

Avoid including "partial alumni" in the alumni team

---

teams/library-reviewers.toml

The other (sub)teams are listed on the website, but this one was missing a `[website]` section in the config.
cc @dtolnay

Add library reviewers to website.

---

teams/compiler-contributors.toml

Please welcome @cuviper to the @rust-lang/compiler-contributors group! @cuviper has been helping out with the compiler on various issues for some time, especially when it comes to diagnosing and investigating problems around LLVM.

add cuviper to compiler contributors

---

teams/infra.toml

@sgrif did a lot of great work on infrastructure in the past, especially around crates.io, but she doesn't have the time to dedicate to the infra team anymore. Thanks Siân, you'll be missed!
cc @rust-lang/infra

Move sgrif to infra alumni

---

teams/infra.toml
teams/operations.toml
teams/release.toml
teams/wg-triage.toml

The operations team was supposed to be an umbrella for the infrastructure and release teams, but it never had any actual use, meeting or role. This removes the team, putting both infra and release as top-level teams on the website.

Remove the operations team

---

teams/core.toml

This should spread the burden out a little on noticing these emails.

Include all core team members on trademark@

---

src/permissions.rs
tests/static-api/_expected/v1/permissions/bors.vscode_rust.review.json
tests/static-api/_expected/v1/permissions/bors.vscode_rust.try.json

Step no. 3 of https://forge.rust-lang.org/infra/docs/bors.html#adding-a-new-repository-to-bors.
Step no. 2: https://github.com/rust-lang/vscode-rust/pull/868

Add vscode-rust to list of bors repos

---

src/permissions.rs
tests/static-api/_expected/v1/permissions/bors.semverver.review.json
tests/static-api/_expected/v1/permissions/bors.semverver.try.json

Step no. 3 of https://forge.rust-lang.org/infra/docs/bors.html#adding-a-new-repository-to-bors.
Step no. 2: https://github.com/rust-lang/rust-semverver/pull/134

Add semverver to list of bors repos

---

teams/library-reviewers.toml
teams/libs.toml

Unfortunately, working as part of the libs team does not currently fit into my life :( 
So I'm already leaving after less than a year. It was a great experience though and I hope to maybe come back some day! And I'm certainly not leaving the Rust community, so you'll see me around. 
Regarding the PRs that I am currently assigned to: I can still review those, but I can't promise how quickly that will happen, so feel free to reassign. (Also, by then I won't be able to merge.) The PRs that I'm the author of I will continue to update, so no change there.
PS: I would not have added myself to the alumni list, but @KodrAus said that I should. If anyone disagrees I can of course change that.
CC @rust-lang/libs

Remove myself from the libs team

---

teams/crates-io.toml

A huge thanks to @ashleygwilliams, @withoutboats, @joshtriplett, and
@ishitatsuyuki for their contributions as founding members of the team.
I look forward to future collaboration with all of you.

Move several crates-io members to alumni status

---

teams/all.toml

This PR adds the **`@rust-lang/all`** GitHub team, which will be useful to grant access to everyone in the Rust Team to a repository.

Add a rust-lang/all github team

---

src/main.rs
src/permissions.rs

It shows their name, GitHub username, email (if present), and all of the
teams (including WGs) that they're a member of.
It's like `dump-team`, but for people.
The output looks like this:
-- Camelid --
github: @camelid
teams:
- icebreakers-cleanup-crew
- icebreakers-llvm
- wg-prioritization
- wg-triage
bors permissions:
(none)
or, for someone on more teams and with an email:
-- Pietro Albini --
github: @pietroalbini
email:  pietro@pietroalbini.org
teams:
- all
- core
- crates-io
- docs-rs
- infra
- infra-admins
- inside-rust-reviewers
- leads
- project-foundation
- release
- website
- wg-rustfix
- wg-security-response
bors permissions:
- crater
- review
- crates-io
- review
- rust
- review
- team
- review
or, for someone on no teams (rustbot's not actually in the teams data, I
created an …

Add a command to show information about a person

---

teams/compiler-contributors.toml
teams/compiler.toml

promote lcnr to compiler team member as announced in https://blog.rust-lang.org/inside-rust/2020/12/14/changes-to-compiler-team.html
r? @wesleywiser

promote lcnr to compiler team member

---

teams/core.toml

There is urgent need for a @rust-lang.org email address for @ashleygwilliams in order to unblock some work for setting up the Rust Foundation. This is a hacky way to set it up until the Infrastructure Team makes a decision on how and whether to support such aliases.

Add an email alias for Ashley

---

src/main.rs
src/permissions.rs

Now it shows other permissions like `perf` and `crater` in addition to
bors permissions.
For example:
-- Pietro Albini --
github: @pietroalbini
email:  pietro@pietroalbini.org
teams:
- all
- core
- crates-io
- docs-rs
- infra
- infra-admins
- inside-rust-reviewers
- leads
- project-foundation
- release
- website
- wg-rustfix
- wg-security-response
bors permissions:
- crater
- review
- crates-io
- review
- rust
- review
- team
- review
other permissions:
- crater
- perf

show-person: Show other permissions as well

---

teams/core.toml

There is urgent need for a @rust-lang.org email address for me in order to unblock some work for setting up the Rust Foundation. This is a hacky way to set it up until the Infrastructure Team makes a decision on how and whether to support such aliases.

Add an email alias for me

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
README.md
rust_team_data/Cargo.toml
rust_team_data/src/email_encryption.rs
rust_team_data/src/lib.rs
src/main.rs

There are cases (especially for the foundation) where we want the members of a mailing list not to be public. This commit implements optional encryption support to temporarily address the problem while the infra team works on a more permanent approach.
Another PR to [rust-lang/sync-team](https://github.com/rust-lang/sync-team) will need to be opened before we can start using encrypted email addresses.

Add optional email encryption support

---

teams/rustdoc.toml

It's `rustdoc`, not `t-rustdoc`.

Fix rustdoc Zulip stream

---

teams/wg-mir-opt.toml

This is so that members of the WG don't have to ask others for try and perf runs

add `try` and `perf` permissions to wg-mir-opt

---

teams/compiler-contributors.toml

Per [RFC 2689](https://rust-lang.github.io/rfcs/2689-compiler-team-contributors.html#alumni-status), @michaelwoerister has asked to be moved out of alumni status into the compiler-contributor team. 
Welcome back @michaelwoerister! 
r? @pnkfelix

Add @michaelwoerister to compiler-contributors

---

teams/project-const-generics.toml

We've had an active const generics project group for some time, but we never created an entry in the team repo for it!
As of opening this PR, the repo doesn't exist, so the link is dangling, but we should create one (based on the [project group template], with this group as write access).
[project group template]: https://github.com/rust-lang/project-group-template/

create the const generics project group

---

people/lenary.toml
teams/risc-v.toml

I no longer work on the RISC-V LLVM target, and I cannot help to triage RISC-V issues any longer.

Remove lenary from RISC-V

---

people/apiraino.toml
teams/wg-prioritization.toml

We've talked with @wesleywiser about this and we are all in agreement that Antonio have been doing a great job, so adding him to leads.
cc @rust-lang/wg-prioritization

Add apiraino as a co-lead of wg-prioritization

---

people/killercup.toml
teams/clippy.toml

For clippyups and such
Want to make sure @rust-lang/compiler is okay with this; the cargo team also has this bit, and I realized today that @\yaahc wouldn't be able to approve a clippyup.

Add rust review perms for clippy

---

teams/project-thir-unsafeck.toml

Couldn't find a better name than "THIR Unsafety Checker Project Group" 🙄
The group should probably also have write access to the [project-thir-unsafeck](https://github.com/rust-lang/project-thir-unsafeck/) repo.
r? @pnkfelix @wesleywiser cc @nikomatsakis

Create the "THIR Unsafety Checker Project Group"

---

people/albins.toml
people/amandasystems.toml
teams/wg-polonius.toml

@amandasystems changed their username from the previous `@albins`, so this PR updates the information in the team repo to match what's currently in their GitHub profile.
Merging the PR right now to unblock the team repository validation, if you want to tweak the data we can send a followup PR!

Rename albins to amandasystems

---

teams/wg-rustfmt.toml

cc @calebcartwright @topecongiro 
We've been unable to reach @topecongiro for a while, and it would be nice if Caleb had all the perms so that he can make progress on https://github.com/rust-lang/rust/issues/82385 . He's been doing a lot of the rustfmt work for quite a while now.
@topecongiro, let me know when you get back and we can discuss this.
r? @rust-lang/devtools

Add Caleb as co-lead of rustfmt

---

people/CraftSpider.toml
teams/rustdoc.toml

CraftSpider has been doing great work on Rustdoc, especially the JSON
backend, and has already been contributing some reviews.
Welcome to the team!
r? @GuillaumeGomez cc @craftspider @rust-lang/rustdoc

Add CraftSpider to the Rustdoc team

---

teams/core.toml

This is currently managed via the Mailgun UI directly; we will want to move this to a more comprehensive solution eventually, but this should be OK for the time being.

Remove privacy@ from team repository management

---

teams/compiler-contributors.toml
teams/compiler.toml

Per [RFC 2689](https://rust-lang.github.io/rfcs/2689-compiler-team-contributors.html#alumni-status), @michaelwoerister has asked to be moved out of the compiler-contributor team and back into the compiler team as a full member (which was his previous status).
r? @pnkfelix

Add @michaelwoerister to compiler team

---

teams/compiler.toml

Follow up to https://github.com/rust-lang/team/pull/579.

Remove mw from alumni list.

---

teams/wg-nll.toml

I've noticed that the `wg-nll` team only contained Niko and Felix, but there were a few more members. 
This PR adds the people I could definitely remember being active in the WG, basically the `WG-nll` user group on zulip
(screenshot: 
but I could be missing others. Please let me know if I've forgotten anyone you remember @nikomatsakis and @pnkfelix, and I'll add them.
I know the working group is winding down and its best days are behind us: it's more of a gesture for posterity's sake.

Update the `wg-nll` team

---

teams/release-publishers.toml

I'll add via rust-lang-owner this team to the relevant crates once this merges.

Add release-publishers to facilitate making releases

---

people/vigoux.toml
teams/arm.toml

As requested on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/242906-t-compiler.2Farm/topic/Not.20part.20of.20arm.20team.20anymore

Remove 'vigoux' from the arm team.

---

teams/compiler-contributors.toml
teams/compiler.toml

Moving @varkor to compiler team alumni but also adding them to
compiler-contributors as they've indicated they would still like to
review PRs as time permits them.
Thanks @varkor!
https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-06-24.20.2354818/near/243799203
r? @pnkfelix

Move varkor to compiler team alumni

---

teams/libs-api.toml

As discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/t-libs-api.20stream).
I think it wouldn't make sense to link to `t-libs`, which the overall libs team already has a link to, and the info about the Library API team is rendered on the same page just below.

Remove non-existent Zulip stream for libs-api team

---

people/Veykril.toml
people/lnicola.toml
teams/wg-rls-2.toml

r+ permission is needed only to sync the rust-lang/rust submodule.
@lnicola @Veykril @flodiebold please let me know if you're ok with this (cc @matklad)

Add more people to wg-rls-2 and give them r+ permission

---

teams/crates-io.toml

Ready to merge whenever we've resolved the privacy policy implications of CCing zendesk!

Update help@crates.io receivers

---

teams/wg-const-eval.toml
teams/wg-polonius.toml

Remove me from const-eval but add me to the Polonius team.
I haven't been useful to const-eval in a long time, but hope to be moderately useful elsewhere.
cc @lqd

Update status of ecstatic-morse

---

teams/release.toml

It's been quite a while since I've been able to help with anything release-related, since I've mostly been focusing on rust-analyzer, so update the team memberships to reflect that.

Remove myself from the release team

---

people/eddyb.toml

I'm not sure how my personal gmail ended up in here, must've been migrated from an older dataset. Hopefully this applies to the team mailing lists, too.

Fix my name and email to be the ones I use on GitHub.

---

config.toml
teams/wg-compiler-performance.toml

Updates the perf team in three ways:
* Adds @michaelwoerister as member
* Adds measureme to bors list
* Adds bors permission for measureme to perf team

Update perf team

---

teams/project-async-crashdump-debugging.toml

Follow-up to https://github.com/rust-lang/infra-team/issues/52#issuecomment-921857020.

Add team for async-crashdump-debugging initiative.

---

teams/clippy.toml

Citing myself [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202021-09-21/near/254214758):
> I think it is time to admit this to myself: I haven't participated in clippy in any meaningful way in the last two years and should probably step down. I still want to help when there are any kind of impl questions wrt rustc APIs, linting logic, MIR linting, or on code crimes I have committed in clippy, but me being part of the team does not help anyone.

Remove oli-obk from clippy team

---

people/hkmatsumoto.toml
teams/wg-prioritization.toml

Discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/Hirochika.20Matsumoto.20wants.20to.20join)
@hkmatsumoto also review if I picked the correct usernames/ID, thanks.
cc: @spastorino

Add Hirochika Matsumoto to wg-prioritization

---

teams/wg-traits.toml

Not active enough with wg-traits for it to make sense for me to receive pings to the wg-traits @ on github

Move yaahc to wg traits alumni

---

teams/wg-rustc-dev-guide.toml

I noticed that the description for the rustc-dev-guide working group [on this page](https://www.rust-lang.org/governance/teams/compiler) does not match the others. This fixes that by starting the sentence with "Mak*ing*..."
I also propose to change the description to read:
> Making the compiler easier to learn by maintaining and improving the Rustc Dev Guide
I believe this more accurately reflects our work.
Thoughts, @rust-lang/wg-rustc-dev-guide?

Edit team description for `wg-rustc-dev-guide`

---

teams/devtools.toml

r? @Manishearth or @killercup 
Think this was mentioned in passing at the last Dev tools meeting but seems like the right thing to do either way given the move from Discord to Zulip

add dev tools zulip info

---

people/ayazhafiz.toml
teams/icebreakers-cleanup-crew.toml
teams/icebreakers-llvm.toml

Adding @ayazhafiz (myself) to these notification groups as described
in [the dev guide](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html).
Please let me know if there is anything missing here. Thanks!

Add ayazhafiz to llvm and cleanup-crew notification groups

---

teams/docs-rs.toml

They haven't been active in 3+ years. I very much appreciate their work originally building docs.rs, but the team list should reflect reality.
cc @onur
cc @pietroalbini , I know you have strong opinions on this

Move onur to docs.rs alumni

---

teams/rustdoc.toml

I don't want to keep up with FCPs and I also don't want to block them (@Manishearth has suggested a few times that the minimum work required for being a member is "responding to FCPs in a timely manner").
Additionally, I don't want people to assign me on PRs.

Leave the Rustdoc team

---

people/hkratz.toml
people/inflation.toml
people/thomcc.toml
teams/macos.toml

The MCP for creating a Macos [notification group](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) (rust-lang/compiler-team#470) was accepted. This PR creates the notification group with the initial group members.
cc @inflation @shepmaster @thomcc

Add macos notification group

---

teams/wg-async-foundations.toml

This updates the membership list of @rust-lang/wg-async-foundations according to the new [membership criteria](https://rust-lang.github.io/wg-async-foundations/CHARTER.html) in our charter.
Thanks to everyone who has helped out with the working group – whether it was compiler work, vision doc, documentation, or other contributions. You're always welcome back!
This is partially based on my recollection, which may be wrong. If you feel that you do meet the criteria but were moved to alumni, please ping me on Zulip or comment on this PR and we'll get it sorted. Thanks!

Update wg-async-foundations membership according to charter

---

teams/wg-allocators.toml
teams/wg-embedded-infra.toml
teams/wg-gamedev.toml
teams/wg-rustc-reading-club.toml

Another formatting cleanup to make these descriptions consistent.
I did
```sh
cd team/
rg description | grep "\.\"$"
```
Also edited the description for teams `embedded-infra`, to remove the somewhat awkward "etc."

Remove end stop punctuation in team descriptions

---

teams/compiler.toml

Seems that I got lost when the website got restructured. There are
others missing, but I don't know whether they asked to be removed, so
I'm not adding them.

Add myself to compiler team alumnis

---

teams/wg-incr-comp.toml

I think we can safely remove this since it's currently a 404 on the [compiler team page](https://www.rust-lang.org/governance/teams/compiler).
cc @wesleywiser

Remove wg-incr-comp repo from website

---

teams/fuchsia.toml

I was looking for this in response to https://github.com/rust-lang/rust/pull/93858#issuecomment-1041367498. Keeping track of the right people involved here will be easier than piecing together from LinkedIn who to ping.

Add a team for '@rustbot ping fuchsia'

---

teams/devtools.toml
teams/wg-debugging.toml

The compiler team is [creating a working group](https://github.com/rust-lang/compiler-team/pull/489) to focus our efforts on [improving the debugging experience in 2022](https://blog.rust-lang.org/inside-rust/2022/02/22/compiler-team-ambitions-2022.html#debugging-initiatives-). 
Since a wg-debugging already existed in the repo, I talked to @Manishearth and we decided it made the most sense to just move this over to the compiler team rather than have two different working groups. I've gone ahead and added folks we talked to who are planning to contribute to this effort. 
cc @pnkfelix @michaelwoerister @davidtwco 
Thanks for your prior work in this area @Manishearth!

Add compiler team wg-debugging

---

teams/devtools.toml
teams/rustfmt.toml
teams/rustup.toml

This originally started with the realization that some emails, e.g. recent ones from the Foundation, hadn't been received by some rustup and rustfmt folks because working group members are intentionally not included in the `all@rust-lang.org` distribution list.
Subsequent [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/301329-t-devtools/topic/email.20distribution.20lists) with the dev tools team led to an overwhelming consensus that both rustup and rustfmt should be proper subteams under devtools, especially when considering their nature and operating models relative to [RFC 2856](https://rust-lang.github.io/rfcs/2856-project-groups.html).
Let me know if there's any additional changes required to make the conversion.
cc @kinnison @rbtcollins @Manishearth

Convert rustup and rustfmt from working groups to teams

---

config.toml
teams/compiler.toml
teams/infra.toml

Right now all non-alumni team members have dev_desktop access.
The field is only relevant for the `all` meta-team.
We may use this field to disable access to users in the future
r? @pietroalbini 
This PR is used to enable https://github.com/rust-lang/simpleinfra/pull/79 to easily decide whether a user has access to the dev desktops, without requiring changes to the dev-desktops in the future (we can just modify the teams repo to switch flags to `false`)

Add a flag for whether a user has dev_desktop access.

---

teams/crates-io.toml
teams/docs-rs.toml
teams/website.toml

The time I have nowadays to contribute to Rust is less than what I had a couple years ago (now having a full time job), and realistically I can't contribute to six teams in my spare time. Being in so many teams resulted in me not being able to meaningfully contribute to any of them.
As I mentioned in [me leaving the Core Team](https://blog.rust-lang.org/2022/01/31/changes-in-the-core-team.html), from now on I'll focus just on leading the Infrastructure Team and being a member of the Release Team and the Security Response WG. I'm sad to leave the crates.io team, the docs.rs team and the website team, but I'm proud of everything we achieved in the past couple of years.

Leave the crates.io, docs.rs and website teams

---

config.toml
people/YuhanLiin.toml
people/jonathanpallant.toml
people/mathk.toml
people/newAM.toml
teams/wg-embedded-core.toml
teams/wg-embedded-cortex-a.toml
teams/wg-embedded-cortex-m.toml
teams/wg-embedded-cortex-r.toml
teams/wg-embedded-hal.toml
teams/wg-embedded-linux.toml
teams/wg-embedded-msp430.toml
teams/wg-embedded-resources.toml
teams/wg-embedded-riscv.toml
teams/wg-embedded-tools.toml
teams/wg-embedded-triage.toml

Adds the remainder of the embedded-wg teams based on membership [here](https://github.com/rust-embedded/wg#organization) per https://github.com/rust-embedded/wg/issues/442, towards moving team mailinglists over to central hosting.
cc. @pietroalbini

Adding embedded-wg team definitions

---

people/celinav.toml
teams/project-stable-mir.toml

As discussed in the [2022-03-25 T-compiler steering meeting](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bsteering.20meeting.5D.202022-03-25.20compiler-team.23488.2C.20.23498.html), this is the project group we are forming to deliver an external definition for stable MIR.
See also https://github.com/rust-lang/compiler-team/issues/498
I have a draft charter here: https://hackmd.io/WBVP4ROORRiJGGpEaLPc6g ; I expect it will go through some further revision with the help of my co-lead.

Add project-group for stable-mir

---

people/ytmimi.toml
teams/rustfmt.toml

I'm pleased to add Yacin to the rustfmt team!
He's been a highly active and productive contributor for quite some time, tackling rustfmt efforts both small and large. He's also been heavily involved with all of the other aspects of maintaining open source projects including helping users and answering questions, triaging issues and bugs, and doing code reviews.
@ytmimi thanks for all your efforts, and I look forward to the continued collaboration!

Add ytmimi to the rustfmt team

---

teams/wg-gamedev.toml

I've removed myself from leads and added Forest instead.
There have been a few instances whe people contacted me and all I did was redirect them to Forest / Ozkriff so there's no point of me just being the middleman :).
Now it's is closer to the real structure of the WG.

removed myself from leads and added Forest Anderson to leads

---

teams/rustfmt.toml

This moves some folks on the rustfmt team to alumni status to reflect the fact that they haven't been actively involved with the project for a couple years now.
@topecongiro @scampi - Thank you so much for your invaluable contributions! rustfmt wouldn't be anywhere near where it is today were it not for your tireless, and often thankless, efforts over the prior years. As I mentioned in our offline communications, you're more than welcome come back whenever!
cc @Manishearth

Move some rustfmt members to alumni

---

config.toml
teams/wg-rls-2.toml

Follow up to the repo move of the rust-analyzer repo to rust-lang, we want to now sync the team to github for access.
See https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rust-analyzer.20transition.20to.20rust-lang for context

Sync the `wg-rls-2` team with github

---

teams/crates-io.toml

Forgot to remove myself from `help@crates.io` in #727.

Remove myself from help@crates.io

---

teams/infra.toml

Following https://github.com/rust-lang/sync-team/pull/3 we now sync Zulip user groups with the Team repo. As a first real world test of this, I'd like to sync the infra team.

Add T-infra Zulip group

---

teams/rustdoc.toml

This moves @ollie27 from the rustdoc team to alumni status to reflect the fact that they haven't been actively involved with the project for some time now.
@ollie27 - Thanks a lot for your contributions and invaluable reviews on rustdoc! Thanks to you, rustdoc got much better. You're more than welcome to come back whenever you have time to contribute again! :)
cc @rust-lang/rustdoc

Move ollie27 to alumni

---

teams/clippy.toml

This moves inactive (regarding reviews) members of the Clippy team to alumni, so they can enjoy the well deserved (temporary) retirement.
Thanks to @mcarton and @killercup for the work you did for Clippy back in the early days! Enjoy your well deserved retirement.
Also thanks to @phansch for helping with reviews in recent years. Once you're ready to invest time into Clippy again, let us know and we will welcome you back.
Thanks to @mikerite for his ongoing involvement in Clippy and comments and thoughts on Clippy PRs. I also removed you from the team in this PR, mostly to get the reviewer and r+ rights synced. If you want to pick up reviewing Clippy PRs again, let us know and we can add you back to the team and reviewer rotation.
This was discussed on …

Clean up the Clippy team

---

teams/wg-nll.toml

The [types team](https://github.com/rust-lang/rfcs/pull/3254) is the likely successor of the work.
Note: I also added a `[[github]]` annotation to the wg defintion in the unlikely case that the wg is revived, since until now the permissions have been manually curated on GitHub.
cc @nikomatsakis @pnkfelix

Add GitHub info for wg-nll

---

teams/ides.toml

cc @Xanewok 
I'm not sure how active the IDEs team is now, but I am trying to clean up our GitHub teams, and the [IDEs](https://github.com/orgs/rust-lang/teams/ides) team is one of the few remaining that is not controlled by this repo. I believe we either need to merge this PR *or* archive the IDEs team description in this repo. Either way, we can then delete the IDEs GitHub team.

Add GitHub repo for IDEs team

---

teams/wg-unsafe-code-guidelines.toml

Currently the [unsafe code guidelines GitHub team](https://github.com/orgs/rust-lang/teams/wg-unsafe-code-guidelines) is out of sync with the team repo definition. This will create a team automatically on GitHub that's kept in sync. Once this is merged, we would delete the old team in favor of the newly synced team.
However, if this is merged, this will remove a few people from the GitHub team: @comex, @gereeter, @strega-nil, @Mark-Simulacrum, and @ehsanmok. If removing any of these folks is incorrect, we just need to add them to the members list. 
cc @nikomatsakis, @avadacatavra, @RalfJung

Add GitHub team for unsafe-code-guidelines wg

---

people/digama0.toml
teams/wg-unsafe-code-guidelines.toml

They have been contributing constructively for quite a while, it's about time we recognize that.
Cc @digama0 @rust-lang/wg-unsafe-code-guidelines

add digama0 to UCG WG

---

README.md

At least, I just ran this without setting any env var, and it worked fine...

add-person does not seem to need a GITHUB_TOKEN

---

teams/wg-grammar.toml

Currently the [wg-grammar GitHub team](https://github.com/orgs/rust-lang/teams/wg-grammar) is out of sync with the team repo definition. This will create a team automatically on GitHub that's kept in sync. Once this is merged, we would delete the old team in favor of the newly synced team.
However, if this is merged, this will remove a few people from the GitHub team: @nikomatsakis, @qmx, @ehuss, @petrochenkov. If removing any of these folks is incorrect, we just need to add them to the members list. 
cc @eddyb

Add GitHub team for grammar wg

---

people/MicahChalmer.toml
people/brotzeit.toml
people/chris-morgan.toml
people/da-x.toml
teams/emacs.toml
teams/vim.toml

This adds vim and emacs marker teams that mirror the teams in GitHub: [rust.vim](https://github.com/orgs/rust-lang/teams/rust-vim) and [rust-mode](https://github.com/orgs/rust-lang/teams/rust-mode). This is part of the effort to ensure we don't have any teams on GitHub that are not controlled by this repo. Here are some things we may want to consider perform merging:
* The use of marker teams is a bit odd. One could argue this should be a subteam of the IDEs team, but I'm not sure if that team is actually active right now. However, whether IDEs is active or not might not actually matter. cc @Xanewok 
* I've named the teams "vim" and "emacs" respectively instead of using the "rust.vim" and "rust-mode" names employed on GitHub. The new names are more understandable I believe, but they might …

Add vim and emacs marker teams

---

people/Xylakant.toml
people/justahero.toml
teams/crates-io-on-call.toml

Supersedes #750 
This marks the crates.io on-call team as a marker team since people should not be considered members of the project if they are just members of this team.

Add a crates.io on-call team

---

people/oli-obk.toml
people/scottmcm.toml
teams/lang.toml

Controls the `T-lang` Zulip group from the team repo.
Also adds Zulip info for @oli-obk and @scottmcm

Add T-lang Zulip group

---

teams/cloud-compute.toml

@fee1-dead currently has only single digit cores available and is working on https://github.com/rust-lang/rust/pull/96077 which requires frequent reruns of the entire test suite.
cc @JoelMarcey

Add fee1-dead to cloud desktops

---

people/listochkin.toml
teams/crates-io-on-call.toml

@listochkin is a Ferrous Systems employee who will help with the crates.io on-call rotation as part of Ferrous Systems's contract with the Rust Foundation.

Add listochkin to the crates.io on-call rotation

---

people/ashleygwilliams.toml
teams/community-rustbridge.toml
teams/community.toml
teams/core.toml
teams/infra-admins.toml
teams/infra.toml
teams/wg-wasm.toml

Should be merged after https://github.com/rust-lang/team/pull/795 (I based on top of it to avoid conflicts)
I'm retaining infra for now for a more gradual offboarding.

drop(aidanhs)

---

Cargo.lock
Cargo.toml
src/check_synced.rs
src/github.rs
src/main.rs
src/schema.rs
src/static_api.rs

Adds a `check_synced` command which checks that the contents of the team repo are synced remotely. Currently this only checks GitHub team membership but can be extended to more things (e.g., Zulip user groups). 
I needed this functionality for work on moving all GitHub team management to the team repo.

Check synced

---

src/check_synced.rs
src/github.rs

This is a small nit, but it allows us to see which users are correctly added to teams but just haven't yet accepted the invite.

Use warn instead of error for members who have not accepted the org invite

---

.gitignore
repos/team.toml
rust_team_data/src/v1.rs
src/data.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json
tests/static-api/repos/some_repo.toml

This is the start of being able to control GitHub repos from the team repo. 
This introduces one new configuration file type ("repo" located in the "repos" folder) as well as two new endpoint types: /v1/repos.json and /v1/repos/$REPO.json.
The ultimate idea is for this to be fed to sync-team so we can move away from having GitHub admins make changes that are not visible to the rest of the project. 
I've only tried to reproduce this repo in the configuration so far.

Add ability to encode and fetch repo information

---

repos/team.toml
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json
tests/static-api/repos/some_repo.toml

This adds support for protected branches to the repo definitions. The definitions look like this:
```toml
[[branch]] 
name = "master" 
ci-checks = ["CI"] 
```
No other fields than the ones above are supported. I believe all other branch options that rust-lang/team has set should be the default. They are:
* Require a pull request before merging
* Require 1 approval (no exceptions for admins or any specific teams or people)
* Dismiss stale pull request approvals when new commits are pushed
* All other options are the GitHub default
When this is merged the following can be added to sync-team:
* Ensuring the branch exists
* Ensuring the proper branch protection options are set for the branch
* Removing all other branch protections

Add branches to repo definitions

---

teams/cargo.toml

This creates and syncs a `T-cargo` Zulip group, which is like
Refs: 
- https://github.com/rust-lang/team/pull/809#issuecomment-1225514064
- [TOML schema reference](https://github.com/rust-lang/team/blob/master/docs/toml-schema.md)
cc @rust-lang/cargo

Add zulip-groups annotation for Cargo Team

---

teams/community.toml

The community@ list itself is handled by our infrastructure.

Remove old unused rust-community Google Groups

---

people/cjgillot.toml
people/davidtwco.toml
people/eddyb.toml
people/michaelwoerister.toml
people/nagisa.toml
teams/compiler.toml

This adds a Zulip user group for the compiler team. `T-compiler` already exists on Zulip, so the group will not be created, but there will be several changes in membership of that group:
The following people will no longer be on the `T-compiler` Zulip group:
* @arielb1
* @cramertj
* @varkor
Additionally, @cjgillot will be added to the user group.
Also, @michaelwoerister, @eddyb, @davidtwco, and @nagisa - please note I added your Zulip ID. 
r? @wesleywiser @pnkfelix

Add compiler team Zulip group

---

README.md

This is not yet widely known, so we should do what we can to advertise it.

Add that we sync Zulip user groups to readme

---

teams/twitter.toml

Adds @m-ou-se, @joshtriplett, @badboy, @pietroalbini, and myself to a new Twitter marker team which will be referenced in forge as the list of folks with access to https://twitter.com/rustlang. 
This list was decided by who has used that account to tweet in the last few months. Please let me know if I should add or remove anyone.
See https://github.com/rust-lang/rust-forge/pull/641 for more details.

Add Twitter marker team

---

people/Nemo157.toml
people/jsha.toml
people/notriddle.toml
teams/rustdoc.toml

Adds a Zulip group for rust-doc team to the team repo configuration.
`T-rustdoc` already exists on Zulip, so this is mostly a no-op, but there would be a slight change in membership: 
* @ollie27 would be removed from the user group (as they are now considered an alum)
* @notriddle would be added to the user group
cc @jsha and @Nemo157 whose Zulip ids have been added. 
r? @GuillaumeGomez

Add Zulip group for rustdoc

---

people/rcvalle.toml
teams/project-exploit-mitigations.toml

This PR adds the Exploit Mitigations Project Group (see rust-lang/compiler-team#545).

Add Exploit Mitigations Project Group

---

teams/lang.toml

Multiple times, people have gotten confused that `lang@` reaches us but
`lang-team@` does not. (This includes people *on* the team.) Add it as
an alias.

Add `lang-team@` as an alias

---

src/check_synced.rs
src/zulip.rs

This makes it a bit easier to know what's going on when things are not in sync.

Improve error messages when checking synced Zulip user groups

---

docs/toml-schema.md
src/schema.rs

This PR does the following:
* Removes the `extra-emails` field from Zulip user group configurations. This was unused and we don't want to encourage the use of email instead of Zulip ids as this is a more direct link.
* Adds an `excluded_people` field to the Zulip user group configuration. Sometimes it might make sense to exclude a certain member from a user group. They may not be on Zulip or the user group might be a subset of the included folks. 
This can be used for the async working group configuration which has a Zulip group that is a subset of the working group and for #805 to exclude one member who is not on Zulip.

Add option for excluding people from a Zulip user group

---

teams/wg-const-eval.toml

This adds a Zulip user group for wg-const-eval.
It also adds @ecstatic-morse to the alumni group (which was missed when they stepped down). 
@ecstatic-morse and @Centril will be removed from the Zulip user group since they are not in the working group. 
r? @oli-obk @RalfJung

Add Zulip user group for wg-const-eval

---

people/CAD97.toml
people/comex.toml
people/digama0.toml
teams/wg-unsafe-code-guidelines.toml

Cc @rust-lang/wg-unsafe-code-guidelines 
Cc https://github.com/rust-lang/team/issues/826

manage WG-UCG Zulip group

---

people/hawkw.toml
people/taiki-e.toml
teams/wg-async.toml

This adds the `WG-async` and `WG-async-sprint-planning` Zulip user groups so that they are automatically synced.
The `WG-async` is set to just the members of the working group. This would remove @hawkw, @csmoe, @gilescope, @Aaron1011, @cramertj, @betamos, @LucioFranco, @Nemo157, @nellshamrell, @Stupremee, and @withoutboats as these folks are not members of the working group. If the #WG-async user group is being used for more than just members, we can easily add folks back using the `extra-members` feature.
The `WG-async-sprint-planning` is set to the members of the working group plus @hawkw whose info has been added to the repo. This also adds @yoshuawuyts and @taiki-e to this user group as they had not yet been added.
r? @nikomatsakis @tmandry

Add Zulip config for async working group

---

people/jdno.toml
teams/infra-admins.toml
teams/infra.toml

I'm thrilled to welcome two new members of the infra team!
* @jdno is the foundation's infrastructure engineer, and will help the team with the maintenance and development of our infra as part of his day job! He will also join the infra-admins "team".
* @rylev has been doing a lot of work improving our team automation lately, and will continue improving it as part of the team.
I'll write a blog post announcing the changes in the coming weeks.

Add jdno and rylev to the infra team

---

.github/workflows/main.yml

Merging needs to be sync'd with deploying terraform changes (could be avoided with a multi-step deployment but doesn't seem worth it).

Adjust sync-team kickoff to use ephemeral credentials

---

people/JohnTitor.toml
people/igaray.toml
people/pierwill.toml
people/tshepang.toml
teams/wg-rustc-dev-guide.toml

We would need to check that all of us still want to belong to the team and add each one's zulip-ids. Can you guys please confirm by clicking your box and answering with your zulip-id, so I can fill it in the PR?.
Check https://github.com/rust-lang/team/issues/826 for instructions
cc

Add zulip-groups to rustc-dev-guide team

---

teams/style.toml

https://github.com/rust-lang/rfcs/pull/3309 has now been merged.
Also need to create the `T-style` and `I-style-nominated` labels.

Add the Rust Style Team

---

people/JohnTitor.toml
people/Turbo87.toml
people/Xylakant.toml
people/jonas-schievink.toml
people/jtgeibel.toml
people/justahero.toml
people/listochkin.toml
people/locks.toml
people/pichfl.toml
people/skade.toml
people/smarnach.toml
teams/crates-io-on-call.toml
teams/crates-io.toml

The crates.io team is slowly working on migrating to Zulip for our official communications. 
I want to be able to point to this repo to say "these are the IDs that should have access to the private crates.io streams on zulip", so I'm adding the Zulip IDs that I can find. This includes people on the crates.io team and the crates.io on-call team.
To find your Zulip ID, go to "Personal Settings" -> "Profile" and click the "Preview profile" button, you should see "User ID" there.
- me
- Pietro

Add more crates.io related zulip IDs

---

people/Amanieu.toml
people/acfoltzer.toml
people/chorman0773.toml
people/cratelyn.toml
people/gnzlbg.toml
teams/wg-ffi-unwind.toml

#826 for `wg-ffi-unwind`; also includes #842

`wg-ffi-unwind` zulip sync

---

teams/wg-prioritization.toml

This adds automatic syncing of the `wg-prioritization/alerts' Zulip user group with the membership of the wg-prioritization working group.
The user group is not currently very well synced with the working group. When this merges the following will happen:
These folks will join the user group: @camelid, @Dylan-DPC, @hkmatsumoto, @inquisitivecrystal, @lcnr, @pnkfelix, @TaKO8Ki.
The following folks will be removed (both of whom are not in the team repo, and so I don't know their GitHub handles): Xu Ran, Chris Dolby. 
r? @apiraino @wesleywiser

Add a wg-prioritization/alerts Zulip user group

---

repos/rust-lang/rust-analyzer.toml
rust_team_data/src/v1.rs
src/check_synced.rs
src/schema.rs
src/static_api.rs

This adds configuration for controlling the [rust-lang/rust-analyzer](https://github.com/rust-lang/rust-analyzer) repo. 
Not only do we want all repos to be controlled through this mechanism long term, but this will also make it a bit easier to change the wg-rls-2 name to rust-analyzer. 
r? @jonas-schievink @matklad

Add rust-analyzer repo

---

repos/rust-lang/team.toml

This was originally added just because the team repo happened to already allow permissions for these bots, but that is not needed.

The team repo actually doesn't use any bots

---

teams/cloud-compute.toml

As suggested by @simulacrum in https://github.com/rust-lang/team/pull/867#issuecomment-1286909457, add comment warding off people who already have access.

ward off people who already have access

---

teams/cloud-compute.toml
teams/compiler-contributors.toml

@oli-obk told me to give access to all compiler contributors and to remove members that have access through other teams.
infra: Mark-Simulacrum, pietroalbini
compiler: oli-obk
compiler-contributors: Mark-Simulacrum, bjorn3, compiler-errors, fee1-dead

Add compiler-contributors access to dev-desktop

---

people/alice-i-cecile.toml
teams/wg-triage.toml

As suggested by @Dylan-DPC in this [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/242269-t-release.2Ftriage/topic/New.20members/near/305355296).
~~I'm not entirely sure how to add myself to a specific subteam, so I'm leaving this in draft for the moment.~~

Add Alice Cecile as a triage team member

---

teams/regex.toml

This moves the regex team to appear right next to crate-maintainers on the website, to make it more obvious that crate-maintainers doesn't cover maintenance of `regex`.

Move regex team next to the crate-maintainers team on the website.

---

src/data.rs
src/main.rs
src/permissions.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/alumni.toml
tests/static-api/_expected/v1/people.json
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/alumni.json
tests/static-api/people/user-7.toml
tests/static-api/teams/alumni.toml

A follow up to #858. This adds members of archived teams that are no longer active anywhere else to the alumni team. It also adds some more validation that the alumni team is correct (and allows us to remove some from the explicit list of alumni since they are reflected elsewhere). Finally, there is some light refactoring to remove unnecessary use of `Result`.

More alumni

---

people/sdroege.toml
repos/rust-lang/pkg-config-rs.toml
repos/rust-lang/pkg-config.toml
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json

This adds configuration for the [`pkg-config` repo](https://github.com/rust-lang/pkg-config-rs). This largely mirrors the current config on GitHub with addition of granting the rest of the crate-maintainers team maintainer rights.  
This will also remove @sdroege's maintainer rights which might not be desired. I'll have to add support for adding individuals to repos if that's a requirement here. 
r? @m-ou-se @joshtriplett

Add pkg-config repo

---

repos/rust-lang/cc-rs.toml
repos/rust-lang/cfg-if.toml
repos/rust-lang/cmake-rs.toml
repos/rust-lang/compiler-builtins.toml
repos/rust-lang/glob.toml
repos/rust-lang/libc.toml
repos/rust-lang/libm.toml
repos/rust-lang/libz-sys.toml
repos/rust-lang/log.toml
src/main.rs

r? @m-ou-se 
cc @rust-lang/crate-maintainers 
Note: some of these repos used to give access to `libs` and/or `libs-contributors` . If anyone is missing access, it's just a PR away from giving it to them.

More crates-maintainers repos

---

teams/mods-discord.toml
teams/mods-discourse.toml

- Dianna/Liv left the Discord a long time ago
- Manish has been a Discord mod since the distinction was created
- Matt hasn't been active as a Discourse mod since last November

Cleaning up the mods teams

---

repos/rust-lang/compiler-builtins.toml

This crate is fairly low volume and only has a single maintainer (me). Currently I have no way of publishing a release because PRs also require an approval from someone other than the author.

Remove master branch protection on compiler-builtins

---

people/Darksonn.toml
people/Thomasdezeeuw.toml
people/carllerche.toml
people/chansuke.toml
repos/rust-lang/backtrace-rs.toml
repos/rust-lang/flate2-rs.toml
repos/rust-lang/getopts.toml
repos/rust-lang/socket2.toml
src/github.rs
src/main.rs

This finishes adding repo configurations for all of the repos indicated [in this list here](https://github.com/rust-lang/team/pull/861#issuecomment-1286670330). 
This adds @Darksonn @Thomasdezeeuw @carllerche @chansuke to the team repo, because they are individual contributors to the socket2 crate. 
This also includes some small improvements to the `add-repo` utility which I've been using to quickly add these configs. 
r? @m-ou-se 
cc @thomcc

Even more libs contributors

---

repos/rust-lang/bors.toml

This repository should contain the attempted rewrite of `homu` in Rust. I'm not sure if we want to use the `bors` bot for merging in this repository, but I guess why not, it's better to dogfood :laughing:

Add repository for `bors` implementation written in Rust

---

people/chriswailes.toml
people/maurer.toml
people/mgeisler.toml
people/stephenhines.toml
teams/android.toml

These user names are synchronized with the names the Android Platform Support document.

Add the Android team to the project

---

teams/crates-io.toml

We're already using `[[zulip-groups]]` in the file and have moved our private channels over. This PR should update the website to also link to Zulip instead of Discord.

crates.io: Switch from Discord to Zulip

---

teams/rustdoc.toml

@CraftSpider hasn't been very active in the last months. After discussing it with them and the team, they agreed to being moved to alumnis for the time being. Thanks **a lot** for all your work. We'd love to have you back on board in the future!
cc @rust-lang/rustdoc

Move CraftSpider to rustdoc team alumnis

---

teams/miri.toml

@jyn514 keeps telling me to submit this
cc @RalfJung @oli-obk 
The Miri team primarily works on a separate repo, but parts of the interpreter live in rust-lang/rust. So it seems like anyone on the team has reason to do perf ~and crater~ runs, and should be trusted to do so responsibly. Of course, this change only affects me currently.

Let t-miri use perf

---

teams/lang-advisors.toml
teams/lang.toml

This adds the lang advisors team as established by
https://github.com/rust-lang/rfcs/pull/3327 . All of the individual
people this commits adds have been approved by the entire lang team, and
all have confirmed that they want to be added. Welcome to @alexcrichton,
@Amanieu, @jackh726, @JakobDegen, @RalfJung, @simulacrum, and
@wesleywiser! Welcome as well to @cramertj who is moving from lang to
lang-advisors, and thank you for all you've done for the lang team!
This also adds Tyler Mandry (@tmandry) to the lang team. Welcome to the
team, Tyler!
We plan to make an Inside Rust blog post soon.

Updates to lang, and establish lang-advisors

---

people/Kobzol.toml
people/SparrowLii.toml
teams/wg-parallel-rustc.toml

As the parallel-rustc working group is restructured([MCP](https://github.com/rust-lang/compiler-team/issues/567) here), we should update the membership list accordingly.
cc @pnkfelix @cjgillot 
cc @nnethercote @bjorn3 @Kobzol

Update parallel-rustc WG's member list

---

teams/libs-api.toml
teams/libs-contributors.toml
teams/libs.toml

Last month, @yaahc notified the teams that she is stepping down. She will remain lead of the error handling project group and will continue to participate in reviews for error handling-related work. All of us are grateful for her contributions.
(@rust-lang/libs, @rust-lang/libs-api)

Move yaahc to T-libs and T-libs-api alumni, +libs-contributors

---

teams/compiler-contributors.toml
teams/wg-rustfix.toml

Unfortunately, due to competing life demands, I only have [one commit](https://github.com/rust-lang/rust/commit/14eb94fe7a3ca3a92d5d7e42744d105c0fc6d527) in the compiler in the last three years. :cry: :cold_sweat:  According to the text of [RFC 2689](https://github.com/rust-lang/rfcs/blob/master/text/2689-compiler-team-contributors.md), I should have been demoted to alumni status some time ago. I'm assuming this PR is the correct way to do that?

demote ZMD to alumni contributor

---

repos/rust-lang/bors.toml

This prevented merging PRs with the GitHub UI; using bors to merge PRs to bors doesn't make sense long-term since it can prevent fixing bors.

Remove bors from bors repo

---

people/KodrAus.toml
people/rylev.toml
people/tarcieri.toml
people/the8472.toml
people/thomcc.toml

These are the remaining users who should be reflected in one of the Zulip user groups but are not because we did not have their Zulip user id. 
cc @tarcieri @KodrAus @thomcc @the8472

Add Zulip ids for missing users

---

people/ozkanonur.toml
teams/bootstrap.toml

Infra has quite broad permissions. Create a subteam so that people can be recognized as a contributors without also having permission to bypass bors checks, etc.
Welcome, @ozkanonur! Thank you for your contributions and I look forward to continuing to work with you :)

Create a bootstrap sub-team of infra and add ozkanonur to it

---

people/diannasoreil.toml
people/mikerite.toml
people/shadows-withal.toml
teams/clippy.toml
teams/community-rustbridge.toml
teams/community.toml
teams/mods-discord.toml

The user https://github.com/mikerite has been deleted as far as I can tell (does not appear to be renamed). This is causing the check script to fail.
This will also require #930 to pass the checks.

Remove mikerite

---

teams/wg-parallel-rustc.toml

The work of the parallel compiler is very dependent on the perf tool, I hope to obtain the permission to use the tool

add perf permission for parallel-rustc wg

---

docs/toml-schema.md
repos/rust-lang/backtrace-rs.toml
repos/rust-lang/bors.toml
repos/rust-lang/cc-rs.toml
repos/rust-lang/flate2-rs.toml
repos/rust-lang/libc.toml
repos/rust-lang/project-exploit-mitigations.toml
repos/rust-lang/rust-analyzer.toml
repos/rust-lang/socket2.toml
repos/rust-lang/team.toml
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json
tests/static-api/repos/test-org/some_repo.toml

#937 has not landed yet because we need to support branch patterns for branch protections in repo configs (i.e., allow a config to protect many branches with the same protection). 
I added support for this in sync-team in sync-team#36. However, there is now an inconsistency in naming within the team repo. This is because we have logically moved from configuring *protected branches* to configuring *branch protection rules*.
This change to the team repo aligns the team repo with this naming. Repo configs no longer specify "branches" but rather "branch protections". 
Concretely, the following changes have been made:
* The repo configs now use "branch-protections" key instead of "branch"
* The repo configs' branch-protections specify a "pattern" and not a name "name" (since this supports * …

Switch from branches to branch-protections

---

docs/toml-schema.md
src/data.rs
src/schema.rs
teams/compiler.toml

This provides a way to get in touch with a team's members *and* the members of that team's subteams.

Add option to lists for including all subteam members

---

repos/rust-lang/cargo.toml

This should set up the rust-lang/cargo repo to be managed by the team sync. The main motivation here is to demote the Cargo team's access from Maintain to Write to remove the "Merge" button on PRs. I do not think any of us need any of the extra permissions afforded by the Maintain level. IIUC, this configuration should create a branch protection that only allows bors to push to master. 
I also believe this should still allow creating branches. If not, then this might interfere with the release process which creates a tag and branch.

Manage the cargo repo via teams

---

repos/rust-lang/cargo.toml

I was a bit too quick with merging #937. This moves cargo to using the correct configuration.

Move cargo to branch protections

---

teams/interim-leadership-chat.toml

Wesley Wiser is a member of leadership chat, but the original commit
missed them.

Add wesleywiser to interim-leadership-chat (missing in original commit)

---

rust_team_data/src/v1.rs
src/static_api.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json

**BREAKING CHANGE**
With https://github.com/rust-lang/sync-team/pull/38 merged no one is using these fields any more. Since these are duplicates of other fields, it would be much cleaner to remove these before some other user starts to depend on them.

Remove the branches field from repos API

---

people/kw-fn.toml
teams/project-error-handling.toml

The GitHub user `kw-fn` has deleted their account.  This should get CI working again.
cc @yaahc

Remove kw-fn

---

rust_team_data/src/v1.rs
src/main.rs
src/schema.rs
src/static_api.rs

This adds rfcbot as a bot so that it can receive the correct permissions to be able to add labels to a repo.

Add rfcbot as a bot.

---

teams/release.toml

This will be used for the governance RFC approval and representative selection.

Add mailing list for release + subteams

---

config.toml
teams/infra-admins.toml

This PR adds the `sync-team-confirmation` permission, which will allow `infra-admins` to confirm team repo changes before applying them [(context)](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/sync-team/near/341084416).

Add a new `sync-team-confirmation` permission

---

people/aliemjay.toml
teams/types.toml

Not all our members are compiler-contributors, compiler or other similar team members.
In https://github.com/rust-lang/rust/pull/109388#issuecomment-1476049002 @aliemjay was unable to run perf.

Give types team members access to perf, crater and dev-desktops.

---

teams/foundation-email-redirects.toml

These redirects were originally configured in the Mailgun interface manually. This commit brings them over to the team repo, to be managed with the rest of the aliases.

Import Foundation email redirects into the team repo

---

people/Sp00ph.toml
teams/cloud-compute.toml

@jyn514 [recommended](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Cloud.20compute.20questions/near/347918804) I just open this PR and state my reasons for wanted access here:
I often go weeks at a time where I only have access to a slow laptop, which routinely takes minutes for e.g. a stage 0 recompile of the stdlib after a 1 line change, and which also chokes when trying to use rust-analyzer on the stdlib or the compiler source. I believe access to the dev desktops would boost my productivity massively in those time periods. I would like to use them to work on the stdlib and maybe also move into working on the compiler itself. I would also like to (if this is deemed an appropriate use case) work on improvements of the LLVM codegen, since this would also speed up …

Add myself to people and cloud-compute

---

teams/infra-admins.toml

The infra-team is working on SSO for infrastructure services, which will be implemented using a Google Workspace. Setting this up requires a new alias.
cc @pietroalbini

Create alias for Google Workspace admin

---

people/Dirbaio.toml
people/eldruin.toml
people/romancardenas.toml
teams/wg-embedded-hal.toml
teams/wg-embedded-riscv.toml
teams/wg-embedded.toml

As has just been noted our embedded team representation wasn't up-to-date regarding the actual status. Also a few members didn't have their emails recorded so the Leadership council mail didn't get through.

Update Embedded WG memberships

---

teams/compiler-contributors.toml
teams/compiler.toml

that's a lot of compilers 😆 
As per the T-compiler vote: 
Welcome to the compiler team @compiler-errors

Move compiler-errors from compiler contributors to the compiler team

---

teams/interim-leadership-chat.toml

Per https://github.com/rust-lang/team/pull/1001, jntrnr has stepped back from leadership roles. :(

remove jntrnr from interim-leadership-chat.toml

---

repos/rust-lang/unsafe-code-guidelines.toml

Based on the discussion on zulip in:  <https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/Meeting.202023-05-23>.

Add rustbot and rfcbot to the unsafe-code-guidelines repo

---

teams/compiler-contributors.toml
teams/compiler.toml

I won't lie, it makes me a bit sad to step back from @rust-lang/compiler, but the reality is that I haven't been actively involved in compiler development for some time, so I think contributors is a better fit. It's so exciting to see how vibrant and active the team has become! 💜 you all.
r? @pnkfelix @wesleywiser

move myself from compiler to compiler contributors

---

teams/wg-prioritization.toml

Removing inactive members and moving to `alumni` section past members.
cc: @wesleywiser

Update WG-prioritization member list

---

people/heiher.toml
people/xen0n.toml
people/xiangzhai.toml
people/xry111.toml
teams/loongarch.toml

I would like to request the creation of a LoongArch group after the [initial support for LoongArch](https://github.com/rust-lang/rust/pull/96971) is merged. We are currently preparing to promote the loongarch64-unknown-linux-gnu target to tier 2, and I believe that creating a group at this time would be helpful to the community.
r? @pietroalbini @rylev

Add LoongArch group

---

teams/clippy.toml

Clippy needs to work upstream with rustc for syncs, and in general is still a heavy compile phase. This would be useful for the clippy team.

Give dev-desktop perms to clippy

---

repos/rust-lang/triagebot.toml
teams/triagebot.toml

cc @ehuss @spastorino -- you've both done a bunch of work here, we'll need to discuss with infra making the subteam but I think regardless we'll grant access (just perhaps with a marker team). I don't expect the team to do much in the way of coordination (meetings etc).

Add triagebot team with access to triagebot repo

---

repos/rust-lang/leadership-council.toml

This adds a repository for the Leadership Council. The immediate use for this will be for storing public documents related to the council itself.

Add the leadership-council repo.

---

repos/rust-lang/leadership-council.toml

This should prevent things like accidentally pushing directly to main.
r? @ehuss

Protect main branch of leadership Council repo

---

teams/core.toml

With https://github.com/rust-lang/rfcs/pull/3392 merged, the leadership council has taken over for the core team. Ideally, we would just move the core team to the alumni section, but there are some legacy infrastructure concerns and questions that we need to figure out before retiring core (including but not limited to where should core email addresses route to). 
Until we get all of that straightened out, we'll move all remaining core team members who are not on the council to alumni, and we'll remove the permissions that can already be removed.
A big thank you to @badboy for their service on the core team!!

Somewhat retire the core team

---

repos/rust-lang/rustc-apfloat.toml

eddyb will be transferring their factored out rustc-apfloat crate, https://github.com/LykenSol/rustc_apfloat, into the rust-lang/ organization (see https://github.com/rust-lang/rust/issues/55993 for background).
This is an initial team configuration for us to get the crate up and running under rust-lang/ organization.
However, eddyb has expressed an explicit wish for the source code to be transferred (i.e. *moved*, not *copied*, ha ha), in order to ensure that e.g. stray links to the old repository are handled properly within github.
So, the process I'm planning here is:

config file for rustc-apfloat crate

---

repos/rust-lang/rustc_apfloat.toml

I'm not sure if it will cause any problems to do this renaming but currently both repos exist

Fix naming of rustc_apfloat repo

---

docs/toml-schema.md
src/data.rs
src/main.rs
src/permissions.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/inside-rust-reviewers.toml
teams/project-group-leads.toml
teams/wg-leads.toml

This PR allows extending team membership by the membership of another team. Concretely this PR changes the following:
* `Team::members`, `Data::active_members`, and `Permissions::allowed_people` now all return a `Result` since getting all members can fail if an included team does not exist.
* Added `Team::contains_person` to test whether a team contains a person as a member
* Made `wg-leads` a marker team instead of a working group
* Created a `project-group-leads` marker team
* Removed the use of the various special "include-*" options from all teams except for the special marker teams that those options exist for. All other teams that also want to include those members, can use `included-teams` instead.
And lastly, the entire point of this PR:
* Made the inside-rust-reviewers include …

Allow extending teams from other teams

---

people/asquared31415.toml
teams/cloud-compute.toml

@compiler-errors suggested I use the cloud desktops for working on rustc.  A lot of my work is on UI tests which are very resource intensive and benefit greatly from being able to be run in parallel.  Additionally, the only local machine I have is x86_64 which means that I cannot test the aarch64 tests at all.
cc @oli-obk

add asquared31415 to cloud compute

---

repos/rust-lang/bors-kindergarten.toml

This repo should serve for testing of the new bors bot.

Add bors-kindergarten repo

---

teams/wg-parallel-rustc.toml

@Zoxc is the original initiator and key contributor of parallel rustc front-end, and is currently helping the working group as well, which is very grateful!

add Zoxc to alumni of parallel rustc WG

---

teams/devtools.toml

This adds the docs-rs team to the `tools-all@rust-lang.org` mailing list. This is the only team missing from the list, and I assume it was an oversight.
cc @syphar FYI. This list gets almost no traffic, but I wanted to make sure everyone in devtools can be reached.
cc @Manishearth if you want to review.

Add docs-rs to the devtools team mailing list.

---

repos/rust-lang/style-team.toml

cc @rust-lang/style
This lets the team repository manage permissions and properties of the
style-team repository, including enabling triagebot (rustbot).

Add style team repository

---

teams/devtools.toml

This updates the devtools team membership to better reflect who is currently active.
* Remove Xanewok. They haven't been active for a while.
* Swap kinnison with rbtcollins (cc #1008)
* Add calebcartwright. They have been active with devtools activities, and also represent the rustfmt team.
cc @rust-lang/devtools @rbtcollins @calebcartwright

Update devtools team membership

---

src/schema.rs
src/validate.rs

This would allow us to create the team *rustdoc-contributors* (#1040).
Let me know if I should add a test anywhere.
Should we enforce a depth limit?
<details><summary>Outdated information</summary>
According to https://github.com/rust-lang/team/pull/1040#issuecomment-1672989957, nothing should be negatively affected except for the website. I've built its server locally with a patched `rust_team_data` package (part of this repo) and a patched `rust_team_data` static API (that contains the new team) and the only consequence is that *rustdoc-contributors* doesn't show up anywhere on the website (it doesn't crash the server or anything like that). Therefore, updating the website is not a hard blocker.
I've opened rust-lang/www.rust-lang.org#1854 proposing to add proper website support for …

Permit subteams to have subteams

---

people/graciegregory.toml
teams/community-survey.toml

This updates the membership of the working group to what I believe the current state is.
Current members: myself, @apiraino, @graciegregory, @Kobzol
Alumni: @nikomatsakis, @yaahc, @nrc 
Let me know if this isn't correct, and I can update this!

Update the survey working group membership

---

repos/rust-lang/project-stable-mir.toml

We have been using the issues in the repository to track the work distribution, and we would like to enable rustbot.
We have already added a triagebot.toml file to the repository. Is there anything else that needs to be done?

Add rustbot to project-stable-mir repository

---

teams/compiler-contributors.toml

@apiraino's contributions to prioritizing issues and putting together our weekly triage agendas have a huge impact on the compiler team. 
Congrats @apiraino and well earned! 🎉 
r? @davidtwco

Add apiraino to compiler contributors

---

teams/test-tools.toml

Setting up the new team as per https://github.com/rust-lang/rfcs/pull/3455
cc @rust-lang/devtools as the primary parent team
cc @epage @muscraft @thomcc @weihanglo
Also want to call out that in this proposal I opted to adjust the name of the team to be Test tools team. I don't feel too strongly, and am unsure if this is even permissible since we had a different name in the RFC. However, the more I looked at words in text, file names, etc. that had "Test" and "Testing" the more it felt like a "testing 1-2-3" or even a potential typo.
Lmk if this needs to be changed back to T-testing though, and/or if we'd like to do a quick bikeshed

add test tools team

---

teams/infra.toml

As [previously mentioned](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/team.20leadership/near/380328076), I'm stepping down from the role of lead of the infra team, staying as a member of the team and of infra-admins. The team discussed future leadership, and I'm happy to announce @shepmaster and @jdno will co-lead the team now!

Update leadership of the infra team

---

people/CohenArthur.toml
people/danielhenrymantilla.toml
teams/wg-macros.toml

This is adding a new team that is the wg-macros
as a followup step after the MCP get merged [1].
[1] https://github.com/rust-lang/compiler-team/issues/637

team: add a new wg for rust macros

---

teams/wg-polonius.toml

As described in the [initial t-types announcement/plans](https://blog.rust-lang.org/2023/01/20/types-announcement.html#the-types-team):
> Another relevant working group is the [polonius working group](https://rust-lang.github.io/compiler-team/working-groups/polonius/), which primarily works on the design and implementation of the [Polonius](https://github.com/rust-lang/polonius) borrow-checking library. While the working group itself will remain, it is now also under the purview of the types team.
This PR moves the WG under t-types rather than t-compiler. Note that the move is limited in what the team repo and website support (much like t-types' structure itself): [subteams currently can't have working groups](https://github.com/rust-lang/team/actions/runs/6122552119/job/16618573188#step:5 …

move wg-polonius to t-types

---

people/jonas-schievink.toml
teams/compiler-contributors.toml
teams/release.toml
teams/rust-analyzer.toml
teams/wg-embedded.toml

I have already left the Rust team earlier this year. This pull request additionally removes me from the "alumni", and deletes the file tying my usernames together.
I would also like to request that the Rust team strip all authorship information from my commits to the projects in the `rust-lang` organization.
I no longer want to be associated with the Rust project in any capacity and deeply regret ever getting involved in it.
The Rust project has repeatedly failed its own volunteers, sabotaged community projects, and suppressed public discussion, while its leadership hides behind "concerns" that are never elaborated on and shields the individuals responsible from consequences.
The cowardly handling of the recent RustConf keynote fiasko is merely the most recent example of this, and it is …

Remove my name from the project

---

teams/lang.toml

The lang team recently held its process to select the new co-lead, using the same process proposed by the compiler team. The result is that @tmandry has been nominated to serve as the new co-lead. To make it official, I'm going to conduct a T-lang FCP. Congratulations to @tmandry !

nominate tmandry as co-lead of the language design team

---

teams/rustdoc-contributors.toml
teams/rustdoc.toml

Fixes the link on rust-lang.org 404ing.
See https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Renaming.20this.20stream.20to.20t-rustdoc.3F and https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/stream.20events/near/391770881

Update rustdoc zulip stream name

---

repos/rust-lang/wg-macros.toml

This commit proposes to have a WG webpage for the macros team 
in order to have a way to put all the information about the wg.
cc @rust-lang/compiler @rust-lang/wg-macros

repo: propose to add a repo for store macro wg webpage

---

repos/rust-lang/project-stable-mir.toml

In https://github.com/rust-lang/project-stable-mir/pull/25 we realized we can't merge PRs anymore

Add bors to project-stable-mir

---

repos/rust-lang/rustup.toml
teams/rustup.toml

The permissions for the rust-lang/rust repository are out-of-date, and instead of manually updating them we want to manage the repository automatically.
Fixes https://github.com/rust-lang/infra-team/issues/80

Add rustup repository

---

teams/lang-ops.toml

This team is chartered to prepare meeting agendas, help with issue triage, schedule and document meetings, and generally perform the other "operations" that make the lang team function.
Currently its sole membership is TC but the hope is that it will grow!
cc @rust-lang/lang

create the *lang-ops* team

---

teams/compiler-contributors.toml

Thanks to @ecstatic-morse, @scalexm, @varkor and @Xanewok for all of your contributions! Please don't hesitate to let us know if you would like to move back into active contributor status.
r? @davidtwco

Move a few compiler-contributors to alumni status

---

repos/rust-lang/triagebot.toml

This upgrades the triagebot team's permission role from `write` to `maintain` so that they are able to merge PRs. GitHub's default branch protection behavior is to only allow people with the `maintain` role to merge PRs. The permission differences are:
* Edit a repository's description
* Enable wikis and restrict wiki editors
* Enable project boards
* Configure pull request merges
* Configure a publishing source for GitHub Pages
* Push to protected branches
* Create tags that match a tag protection rule
* Create and edit repository social cards
* Enable GitHub Discussions in a repository
None of which I think are all that important to restrict (at least for this particular repo).
We could change it so that sync-team automatically includes people with the "write" role to be allowed to …

Switch triagebot team to maintain role

---

teams/social-media.toml

We need an email address for the social media account(s). This adds the `social@rust-lang.org` mailing list.

Add `social-media`

---

repos/rust-lang/rust-forge.toml

I would like to set up the forge so that a broader set of people have permission to help merge PRs. My thinking is to set up auto-assignment via rustbot so that individual teams will be responsible for their respective areas. Additionally, I can help with overall management of the repo itself (like dealing with mdbook or blacksmith). I think giving a broad set of people permission to help and encourage participation, avoiding things getting stuck, and to avoid putting the review responsibility on a small number of people.
I don't know if this would need sign off from the council or not. I see this as mainly being under the purview of the infrastructure team (and we can formalize that if needed).
cc https://github.com/rust-lang/leadership-council/issues/47

Add forge repo permissions.

---

teams/project-edition-2024.toml

The leadership council has approved the formation of the edition 2024 project group with @bstrie and myself as leads. I have also provisionally included @m-ou-se, though I recognize she might not be able to devote much time.
There was a discussion previously about how to formally slot this group in the hierarchy, possibly putting it under the launching pad. However, since the launching pad team hasn't been created yet, this is just placed under the council directly.

Add Edition 2024 project group.

---

teams/crates-io-on-call.toml

As requested in Zulip[^1], @tshepang is being added to the crates-io-on-call team.
cc @Turbo87
[^1]: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/on-call.20rotation

Add tshepang to crates-io-on-call team

---

teams/project-stable-mir.toml

We want to give the stable-mir project the ability to r+ stable mir PRs in the compiler since that area is under their purview. 
r? @davidtwco

Give stable-mir r+ access for their code

---

teams/cloud-compute.toml
teams/libs.toml

~~I'd like to give myself dev-desktop permissions. I'm on several teams so hopefully this isn't a problem, even though none of them already have it (although it's a bit surprising that this is true for t-libs).~~ Edit: I've changed this to grant dev-desktop to t-libs broadly.
I haven't asked anywhere if this is okay, so let me know if I'm skipping some process.

Give t-libs dev-desktop permissions

---

people/JoelMarcey.toml
teams/spec.toml

This adds the new spec team. See https://github.com/rust-lang/blog.rust-lang.org/pull/1166

Add spec subteam.

---

teams/wg-embedded-riscv.toml

According to https://riscv.org/about/risc-v-branding-guidelines/
> The “RISC-V” trade name is a registered trademark of RISC-V International.  All uses of the name RISC-V must be consistent with these guidelines. The name must always be written in block letters with a hyphen between the C and V of RISC-V.

Update the RISC-V team name according to the guidelines

---

teams/cargo.toml

Was [doing this](https://github.com/rust-lang/rust/pull/117962#issuecomment-1816651066) and found that Cargo team doesn't have the permission.
It might not be necessary so feel free to close this PR.

Add `perf` `@rust-timer` bot permission for Cargo team

---

teams/docs-rs-reviewers.toml

related docs.rs PR is: https://github.com/rust-lang/docs.rs/pull/2283 
I want to automatically a github team as reviewer for pull requests, and not everyone in the docs.rs team regularly reviews.

add docs-rs-reviewers team for review assignment

---

src/schema.rs
src/validate.rs
teams/archive/docs.toml
teams/archive/ecosystem.toml
teams/archive/ides.toml
teams/archive/interim-leadership-chat.toml
teams/archive/production.toml
teams/archive/project-foundation.toml
teams/archive/wg-meta.toml
teams/archive/wg-net-async.toml
teams/archive/wg-net-embedded.toml
teams/archive/wg-net-web.toml
teams/archive/wg-net.toml
teams/archive/wg-nll.toml
teams/archive/wg-rustfix.toml
teams/archive/wg-traits.toml
teams/archive/wg-unsafe-code-guidelines.toml

Noticed while beginning to work on https://github.com/rust-lang/team/pull/1126#discussion_r1409043589. It does not seem useful to preserve a distinction between "current member of an archived team" vs "former member of an archived team". All members of an archived team are former members.

Disallow an archived team from having current members

---

config.toml
teams/infra-admins.toml

This allows infra-admins to glance at the state of the deprecated org without having to log into the owner bot account.

Add infra-admins to rust-lang-deprecated

---

teams/alumni.toml

Suggested in https://github.com/rust-lang/team/pull/1134#discussion_r1413512278. The alumni team is not temporary after all.

Update comment describing alumni team

---

src/validate.rs
tests/static-api/_expected/v1/people.json
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/alumni.json
tests/static-api/people/user-7.toml
tests/static-api/teams/alumni.toml

The alumni team used to allow explicit members as long as they were neither an active nor alumni of any other team.
Following #1134, explicit members of the alumni team are no longer allowed at all.

Simplify validation of alumni team

---

repos/rust-lang/edition-guide.toml

This adds the https://github.com/rust-lang/edition-guide/ repository to the team repository so that we can manage the permissions here.
I am not adding a branch protection yet, since I sometimes need to be able to manage the docs (and GitHub doesn't allow to self-approve). Ideally it would be nice to have a branch protection without a required approved review.
cc @rust-lang/project-edition-2024

Add edition-guide repo

---

teams/team-repo-admins.toml

See https://github.com/rust-lang/rust-forge/pull/707, https://github.com/rust-lang/leadership-council/issues/35 for context.
Needed to merge the forge PR (so we can link to the merged file).

Add team-admins github team

---

repos/rust-lang/team.toml

The team-repo-admins team was created to formalize who should have merge permissions to the team repo. See [rust-lang/team#1145] for details.
[rust-lang/team#1145]: https://github.com/rust-lang/team/pull/1145

Grant team-repo-admins merge permissions for team repo

---

src/validate.rs

Previously we required everyone included in Zulip user group to be a member of a team. This lifts that restriction.
This fixes the issues encountered in https://github.com/rust-lang/team/pull/1120 and https://github.com/rust-lang/team/pull/952

Allow people to only be extra people in a Zulip group

---

teams/community-localization.toml
teams/community-survey.toml
teams/community.toml

Citations:
**`community-localization`**
https://github.com/rust-lang/team/pull/22
**`community-survey`**
https://github.com/rust-lang/www.rust-lang.org/pull/271/commits/e34026e146c9de391988e69ec6302884118cacac, see src/data/teams/community/teams/survey.yml. Note for now I am only backfilling alumni who already have a profile in the people directory of this repo from some other team membership, i.e. not mgattozzi in this case. We can pursue those cases separately but I figure it would require pinging and getting explicit approval from such contributors to be added into a dataset / website they are not already in, as it's not free: for example they'd become obligated to update this data in the event of name changes.
**`community`**
https://github.com/rust-lang/prev.rust-lang.org/pull/155 + …

Add community team alumni

---

teams/archive/lang-shepherds.toml
teams/archive/reference.toml
teams/lang.toml
teams/style.toml

Citations:
**`lang-shepherds`**
https://github.com/rust-lang/prev.rust-lang.org/pull/823. There are 4 other former members of lang-shepherds: Centril, cramertj, joshtriplett, scottmcm. I have not included them in "lang-shepherds alumni" because they are current lang team members or alumni. The precedent in https://github.com/rust-lang/prev.rust-lang.org/pull/914, https://github.com/rust-lang/prev.rust-lang.org/pull/1072, https://github.com/rust-lang/prev.rust-lang.org/pull/1176 is that when a member of lang-shepherds joins the lang team, it atomically subsumes their lang-shepherds role. Lang-shepherds is not listed on the website (because it is an archived team) but if it were, it would not make sense to list a current lang team member under lang-shepherds saying _"We also want to thank …

Add lang alumni

---

Cargo.lock
Cargo.toml
src/check_synced.rs
src/data.rs
src/github.rs
src/main.rs
src/permissions.rs
src/schema.rs
src/static_api.rs
src/validate.rs
src/zulip.rs
tests/snapshot.rs

`failure` is risky to use in modern code because its formatting macros are not compatible with https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html.
```rust
fn main() {
if let Err(err) = do_main() {
eprintln!("{}", err);
}
}
fn do_main() -> Result<(), failure::Error> {
let person = "dtolnay";
failure::bail!("person {person}");
Ok(())
}
```
Output:
```console
person {person}
```

Replace deprecated `failure` crate with `anyhow`

---

Cargo.lock
Cargo.toml
rust_team_data/Cargo.toml
src/data.rs

The toml crate has a much improved parser based on toml_edit, which produces more accurate error messages.
**Before:**
```console
[ERROR rust_team] failed to parse teams/libs.toml
Caused by:
invalid type: map, expected a sequence for key `github` at line 53 column 1
```
**After:**
```console
[ERROR rust_team] failed to parse teams/libs.toml
Caused by:
TOML parse error at line 20, column 1
|
20 | [github]
| ^^^^^^^^
invalid type: map, expected a sequence
```

Update toml from 0.5 to 0.8

---

repos/rust-lang/blog.rust-lang.org.toml

I'm not sure who should have merge rights (CC @Mark-Simulacrum), so the team list is empty currently.

Add Rust blog repository to automation

---

teams/fuchsia.toml

Update fuchsia.toml to reflect team changes

---

people/burakemir.toml
teams/opsem.toml

Hello!
I am interested in following the discussions around Rust operational semantics, including the unsafe fragment, more closely.
- Burak

Add burakemir to opsem extra people

---

repos/rust-lang/docker-rust.toml
teams/docker.toml

Managing the https://github.com/rust-lang/docker-rust repo, and adding @Muscraft and me as the initial maintainers.

Manage rust-lang/docker-rust

---

config.toml
teams/crates-io.toml

The crates.io team hasn't been using bors for a while now, so there is no need for this unused permission.

bors: Remove `crates.io` repo

---

people/sirhcel.toml
teams/wg-embedded-libs.toml
teams/wg-embedded-linux.toml

Ref https://github.com/rust-embedded/wg/pull/707 https://github.com/rust-embedded/wg/pull/711 https://github.com/rust-embedded/wg/pull/724

Add new rust-embedded libs team, add sirhcel to rust-embedded Linux team

---

teams/crates-io-admins.toml

This is a marker team that defines the group of people that are granted admin access on crates.io. Once the PR is merged we can implement a regular background job on the crates.io side that syncs the team repo into the crates.io user database.
Related:
- https://github.com/rust-lang/crates.io/pull/7852
- https://github.com/rust-lang/crates.io/pull/7858

Add `crates-io-admins` team

---

teams/archive/project-edition-2021.toml

This group has been essentially replaced by project-edition-2024.

Archive project-edition-2021

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json

Before this PR, the default value was implicitly 0 if bors is used or 1 if bors isn't used. However, for some repositories it's enough to require PRs, but approvals are not needed. Setting `required-approvals = 0` will allow that (once it's implemented in `sync-team`).
r? @Mark-Simulacrum :)

Add a branch protection option to choose required approval count

---

repos/rust-lang/cargo-bisect-rustc.toml

Repo: https://github.com/rust-lang/cargo-bisect-rustc
Configuration extracted from GitHub:
```
name = "cargo-bisect-rustc"
description = "Bisects rustc, either nightlies or CI artifacts"
bots = []
[access.teams]
spastorino = "admin"
chrissimpkins = "write"
lcnr = "write"
jdno = "admin"
```

Add cargo-bisect-rustc repository under automation

---

Cargo.lock
Cargo.toml
docs/toml-schema.md
rust_team_data/src/v1.rs
src/main.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/spec.toml

I would like to render "Editor" below @JoelMarcey's entry in https://www.rust-lang.org/governance/teams/lang#spec, in the same location that others have "Team leader".
Source: https://blog.rust-lang.org/inside-rust/2023/11/15/spec-vision.html#specification-team
Output of `cargo run -- dump-website` for translations:
```console
...
governance-team-wg-triage-name = Triage working group
governance-team-wg-triage-description = Triaging repositories under the rust-lang organisation
governance-team-wg-wasm-name = WebAssembly (WASM) working group
governance-team-wg-wasm-description = Improving on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly
governance-role-spec-editor = Editor
```
Output of `cargo run -- static-api` under v1/teams/spec.json:
```json
{ …
```

Add support for custom roles in website, beyond "Team leader"

---

rust_team_data/src/v1.rs
src/static_api.rs

This catches a bug in #1154's `rust_team_data` change.
```console
$ cargo run -- static-api build
[INFO  rust_team::static_api] writing API object v1/teams/arm-maintainers.json...
[ERROR rust_team] failed to deserialize v1/teams/arm-maintainers.json
Caused by:
missing field `roles` at line 11 column 5
```

Add static-api round trip test

---

repos/rust-lang/thorin.toml

There's no reason [thorin](https://github.com/rust-lang/thorin) shouldn't be managed by the teams repository.

manage thorin using teams repo

---

rust_team_data/src/v1.rs
src/static_api.rs
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/alumni.json
tests/static-api/_expected/v1/teams/foo.json
tests/static-api/_expected/v1/teams/leaderless.json
tests/static-api/_expected/v1/teams/leads-permissions.json
tests/static-api/_expected/v1/teams/wg-test.json
tests/static-api/teams/wg-test.toml

In #1154, the static-api data (v1/teams.json) included only ids of roles, such as `"roles": ["spec-editor"]`. Separately the public-facing descriptions for the roles would be included in a ftl translation file produced by `dump-website`.
```
governance-role-spec-editor = Editor
```
This worked!
but has the downside that if some new role is introduced into the team repo **before** the translation for it lands in rust-lang/www.rust-lang.org in locales/en-US/teams.ftl, then the website would temporarily display the following ugly placeholder, until a commit such as https://github.com/rust-lang/www.rust-lang.org/pull/1821 syncs the ftl file.
There are 2 potential fixes:
1. Hide role from the website if localization is not available. This means roles would be added in rust-lang/team without …

Include en-US description of custom roles in static API

---

repos/rust-lang/homu.toml

Repo: https://github.com/rust-lang/homu
I guess that not requiring reviews is to make it easier to do emergency fixes when bors breaks?
Original configuration from GH:
```toml
name = "homu"
description = "A bot that integrates with GitHub and your favorite continuous integration service"
bots = []
[access.teams]
jdno = "admin"
ci-checks = []
```

Add homu repository under automation

---

teams/project-const-traits.toml

This PR adds a project group for the "const traits" initiative.
@fee1-dead and a few others have gathered around an effort to enable const traits in the language (rust-lang/rfcs#2632). The RFC never landed, but work has been under experimentation (https://github.com/rust-lang/rfcs/pull/2632#issuecomment-874924659), and has gained speed especially recently since all of the work was ripped out and reimplemented under the new `#![feature(effects)]`.
Adding this PG helps to acknowledge some of the people who work on this feature, and allows us to have a single ping group for important PRs, etc.
This PG is related to the keyword generics initiative (cc @rust-lang/initiative-keyword-generics) in that it's implementing a "const" effect, but I'd like for this to be under the stewardship of the …

Add project group for const traits initiative

---

teams/wg-embedded-cortex-a.toml
teams/wg-embedded-cortex-m.toml
teams/wg-embedded-cortex-r.toml

This whitespace is problematic because it ends up as line-ending whitespace in the <span>www</span>.rust-lang.org repo in locales/en-US/teams.ftl after running `dump-website`.
https://github.com/rust-lang/www.rust-lang.org/blob/c4222cef26489f0a3925349d20725dcb70a919f7/locales/en-US/teams.ftl#L188-L195
and various editors will object to that. One person will run `cargo run -- dump-website > ../www.rust-lang.org/locales/en-US/teams.ftl` and commit it, the next person will make some unrelated change and end up with spurious diffs on the lines with whitespace.

Delete trailing whitespace from wg-embedded subteam descriptions

---

repos/rust-lang/ena.toml

Repo: https://github.com/rust-lang/ena
```
name = "ena"
description = "An implementation of union-find / congruence-closure in Rust. Extracted from rustc for independent experimentation."
bots = []
[access.teams]
compiler = "pull"
compiler-contributors = "pull"
jdno = "admin"
```

Add ena repository under automation

---

repos/rust-lang/rustc-hash.toml

Repo: https://github.com/rust-lang/rustc-hash
```
name = "rustc-hash"
description = "Custom hash algorithm used by rustc (plus hashmap/set aliases): fast, deterministic, not secure"
bots = []
[access.teams]
jdno = "admin"
lcnr = "write"
```

Add rustc-hash repository under automation

---

repos/rust-lang/chalk.toml

Repo: https://github.com/rust-lang/chalk
```
name = "chalk"
description = "An implementation and definition of the Rust trait system using a PROLOG-like logic solver"
bots = []
[access.teams]
types = "write"
lang = "write"
aturon = "admin"
fabric-and-ink = "write"
rustbot = "maintain"
shepmaster = "admin"
tweerwag = "write"
scalexm = "admin"
withoutboats = "admin"
badboy …
```

Add chalk repository under automation

---

repos/rust-lang/ferris-says.toml

Repo: https://github.com/rust-lang/ferris-says
This is a very important repository that should also be properly managed by `team` :)
```
name = "ferris-says"
description = "A Rust flavored implementation of `cowsay`"
bots = []
[access.teams]
website = "write"
jdno = "admin"
Manishearth = "write"
```

Add ferris-says repository under automation

---

repos/rust-lang/book.toml

Repo: https://github.com/rust-lang/book
The current GitHub permissions (see below) don't really contain any reasonable team, so I'm not sure who to add here, since the docs team is archived. I saw @carols10cents being active, so I added access for her.
```
name = "book"
description = "The Rust Programming Language"
bots = []
[access.teams]
jdno = "admin"
frewsxcv = "write"
pattern = "main"
ci-checks = []
review-required = true
```

Add book repository under automation

---

teams/project-const-traits.toml

The project group *project const traits* would like to have a corresponding GitHub team to enable group pings (of the form [@]rust-lang/project-const-traits).
The initial PR for project-const-traits #1173 listed this as one motivation for the existence of this project group:
> Adding this PG […] allows us to have a single ping group for important PRs, etc.
As far as I understand, my patch would accomplish this goal.
cc @compiler-errors, @fee1-dead, @oli-obk

Create a GitHub team for project const traits

---

repos/rust-lang/miri.toml

Repo: https://github.com/rust-lang/miri
CC @RalfJung
```
name = "miri"
description = "An interpreter for Rust's mid-level intermediate representation"
bots = []
[access.teams]
miri = "write"
bots = "write"
solson = "write"
lcnr = "write"
jdno = "admin"
rust-lang-owner = …
```

Add miri repository under automation

---

repos/rust-lang/rust-forge.toml

As part of https://github.com/rust-lang/rust-forge/pull/715, we will be hosting project-team docs on the forge.

Add project-edition-2024 to forge

---

repos/rust-lang/calendar.toml

`T-cargo` uses the [calendar managed by the calendar repository](https://github.com/rust-lang/calendar/blob/62949e2748910a998d4bc15cd42fe3a3ad692bc0/cargo.toml), but does not have permission to edit the calendar. This adds `write` permissions for `T-cargo` as [suggested by this comment](https://github.com/rust-lang/team/pull/1180#discussion_r1446057760).

chore: Add T-cargo to calendar repo

---

repos/rust-lang/types-team.toml

Repo: https://github.com/rust-lang/types-team
CC @jackh726
```
name = "types-team"
description = "Home of the \"types team\", affiliated with the compiler and lang teams."
bots = []
[access.teams]
types = "write"
lang = "admin"
core = "admin"
lcnr = "admin"
joshtriplett = "admin"
jdno = "admin"
Kobzol = "admin"
scottmcm = "admin"
aliemjay = …
```

Add types-team repo under automation

---

docs/toml-schema.md

Apparently, it is not implemented in `sync-team` at the moment.

Remove mention of `access-level` from TOML schema docs

---

repos/rust-lang/rustc-demangle.toml

Repo: https://github.com/rust-lang/rustc-demangle
https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 suggests to put this under `compiler`. Maybe we should also give access to @alexcrichton?
I also added a branch protection.
```
name = "rustc-demangle"
description = "Rust symbol demangling"
bots = []
[access.teams]
apiraino = "write"
nnethercote = "write"
jdno = "admin"
WaffleLapkin = "write"
nikic = "write"
BoxyUwU = "write"
fmease = "write"
Nilstrieb = "write" …
```

Add rustc-demangle repository under automation

---

repos/rust-lang/thanks.toml

Repo: https://github.com/rust-lang/thanks
Added `t-infra` according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6.
```
name = "thanks"
description = "Celebrate Rust contributors."
bots = []
[access.teams]
website = "write"
Manishearth = "write"
jdno = "admin"
```

Add thanks repo under automation

---

docs/toml-schema.md

It is supposed to be an array, not an object.
Looks like the TOML docs rots fast, I wonder if we could somehow autogenerate it from the team data structures directly (e.g. by attaching the comments and defaults values to them using a proc macro).

Fix documentation of `[[github]]` in teams

---

repos/rust-lang/sync-team.toml

Repo: https://github.com/rust-lang/sync-team
```
name = "sync-team"
description = "Synchronize the team repository with the services we use"
bots = []
[access.teams]
jdno = "admin"
ci-checks = ["CI"]
review-required = true
```

Add sync-team repo under automation

---

repos/rust-lang/surveys.toml

Repo: https://github.com/rust-lang/surveys
```
name = "surveys"
description = "Repo for coordinating the creation, distribution, collection, and analysis of surveys for the Rust project. "
bots = []
[access.teams]
community-survey = "maintain"
apiraino = "maintain"
jdno = "admin"
Kobzol = "maintain"
```

Add surveys repo under automation

---

repos/rust-lang/this-week-in-rust.toml

Repo: https://github.com/rust-lang/this-week-in-rust
CC @nellshamrell
```
name = "this-week-in-rust"
description = "Data for this-week-in-rust.org"
bots = []
[access.teams]
twir-reviewers = "maintain"
mariannegoldin = "maintain"
ericseppanen = "maintain"
U007D = "maintain"
nellshamrell = "maintain"
extrawurst = "maintain"
bennyvasquez = "maintain"
cdmistman = "maintain"
jdno = "admin"
andrewpollack = "maintain"
ci-checks = []
```

Add this-week-in-rust repo under automation

---

teams/leadership-council.toml
teams/release.toml
teams/wg-triage.toml

This implements [RFC#3533](https://github.com/rust-lang/rfcs/pull/3533).
Concretely this means:
* Make Release a subteam of Infra
* Remove @rylev from Leadership Council
* While @Mark-Simulacrum was the Release representative on the Council, it was agreed that as part of this move @rylev would step down as Infra representative and @Mark-Simulacrum would take over as the Infra rep
There are a few follow ups that need to happen as a result of implementing RFC 3533 that cannot be addressed in this PR:
* The launching pad needs to be created so wg-triage can be placed underneath it. This is being worked on in https://github.com/rust-lang/team/pull/1206 cc @ehuss 
* https://github.com/rust-lang/team/pull/1182 needs to be updated to reflect the change in roles (i.e., the @rylev is no longer a …

Implement RFC#3533 Combining Infra and Release

---

repos/rust-lang/google-summer-of-code.toml

For storing the Rust GSoC (2024) project list.

Add new Google Summer of Code repository

---

teams/community-survey.toml

The e-mail is primarily designed to access online services (e.g. SurveyHero) under a shared account for now.

Add an e-mail account for community survey team

---

teams/leadership-council.toml

Add team affiliation for leadership council representatives

---

repos/rust-lang/team.toml

It shouldn't be needed anymore I think, and anyway `core` is now a subset of `team-repo-admins`.

Remove core access to the team repo

---

teams/all.toml
teams/alumni.toml
teams/infra-admins.toml
teams/leads.toml

This switches more "teams" to be "marker-teams", as these aren't really teams that exist by themselves.
From what I can tell, this should not affect the website, and I checked the static JSON and the changes look like what I expect. From what I can tell, sync-team does not look at the team kind, either, so I don't think it should be affected.

Switch more teams to marker teams.

---

teams/wg-compiler-performance.toml

It's been a while since I've had time to work specifically on compiler performance, so I think it's more accurate for me to remove myself from the active working group members.

Remove myself from wg-compiler-performance

---

teams/triagebot.toml

jackh726 expressed willingness to do triagebot reviews, and since there have been a bunch of PRs to review for some time, and spastorino has left the triagebot team recently, I figured that it might be good to expand the roster.
CC @jackh726 @Mark-Simulacrum

Add jackh726 to triagebot maintainers

---

teams/leads.toml
teams/wg-leads.toml

This removes the last remaining references to the Core team in active teams and replaced with references to the Leadership Council where appropriate. The Core team itself still remains and will be archived in a future PR and the core team is still referenced from archived teams.

Remove remaining references to core

---

repos/rust-lang/ar_archive_writer.toml

Repo: https://github.com/rust-lang/ar_archive_writer
CC @bjorn3
```
name = "ar_archive_writer"
description = "A writer for object file ar archives"
bots = []
[access.teams]
BoxyUwU = "write"
fee1-dead = "write"
tmiasko = "write"
TaKO8Ki = "write"
petrochenkov = "maintain"
b-naber = "write"
jdno = "admin"
compiler-errors = "maintain"
nikic = "write"
bjorn3 = "write"
jackh726 = "maintain" …
```

Add ar_archive_writer repo under automation

---

repos/rust-lang/async-book.toml

Repo: https://github.com/rust-lang/async-book
```
name = "async-book"
description = "Asynchronous Programming in Rust"
bots = []
[access.teams]
wg-async = "write"
nrc = "write"
jdno = "admin"
eholk = "write"
traviscross = "write"
tinaun = "write"
guswynn = "write"
Nemo157 = "write"
cramertj = "admin"
vincenzopalazzo = "write"
taiki-e = "write"
```

Add async-book repo under automation

---

repos/rust-lang/const-eval.toml

Repo: https://github.com/rust-lang/const-eval
```
name = "const-eval"
description = "home for proposals in and around compile-time function evaluation"
bots = []
[access.teams]
compiler = "pull"
lang = "pull"
jdno = "admin"
```

Add const-eval repo under automation

---

repos/rust-lang/glacier.toml

Repo: https://github.com/rust-lang/glacier
Assigned to `wg-triage` according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6.
```
name = "glacier"
description = "A big 'ol pile of ICE."
bots = []
[access.teams]
core = "admin"
wg-triage = "write"
Enselic = "write"
pitaj = "write"
joelpalmer = "write"
camelid = "write"
KittyBorgX = "write"
anden3 = "write"
JohnCSimon = "write"
crlf0710 = "write"
Muirrum = "write"
bstrie = "write"
jdno = "admin"
Alexendoo = "write"
alice-i-cecile = "write"
```

Add glacier repo under automation

---

repos/rust-lang/git2-rs.toml

Repo: https://github.com/rust-lang/git2-rs
Assigned to `cargo` according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6, but not sure about it.
CC @rust-lang/cargo
```
name = "git2-rs"
description = "libgit2 bindings for Rust"
bots = []
[access.teams]
joshtriplett = "admin"
jdno = "admin"
alexcrichton = "write"
ci-checks = ["Success gate"]
```

Add git2-rs repo under automation

---

repos/rust-lang/rustfmt.toml

Repo: https://github.com/rust-lang/rustfmt
```
name = "rustfmt"
description = "Format Rust code"
bots = []
[access.teams]
bots = "write"
rustfmt = "write"
ytmimi = "write"
calebcartwright = "admin"
nrc = "write"
jdno = "admin"
bors = "write"
ci-checks = [
"(x86_64-unknown-linux-gnu, nightly)",
"(x86_64-unknown-linux-gnu, stable)",
"(x86_64-apple-darwin, nightly)",
"(x86_64-apple-darwin, stable)",
"(x86_64-pc-windows-msvc, nightly)",
"(i686-pc-windows-msvc, nightly)",
"(i686-pc-windows-msvc, stable)", …
```

Add rustfmt repo under automation

---

repos/rust-lang/rust-by-example.toml

Repo: https://github.com/rust-lang/rust-by-example
It seems that `highfive` is no longer used by the repo, so I didn't keep it.
CC @marioidival
```
name = "rust-by-example"
description = "Learn Rust with examples (Live code editor included)"
bots = []
[access.teams]
core = "admin"
wg-rust-by-example = "write"
marioidival = "write"
jdno = "admin"
```

Add rust-by-example repo under automation

---

repos/rust-lang/mdBook.toml

Repo: https://github.com/rust-lang/mdBook
The `rust-mdbook-deploy` user looked.. intriguing, so I kept it there.
CC @ehuss
```
name = "mdBook"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
bots = []
[access.teams]
infra = "pull"
rust-mdbook-deploy = "write"
jdno = "admin"
ci-checks = ["Success gate"]
```

Add mdbook repo under automation

---

repos/rust-lang/hashbrown.toml

Repo: https://github.com/rust-lang/hashbrown
CC @Amanieu
```
name = "hashbrown"
description = "Rust port of Google's SwissTable hash map"
bots = []
[access.teams]
bots = "write"
libs = "write"
ChrisDenton = "write"
workingjubilee = "write"
SimonSapin = "write"
bors = "write"
sunfishcode = "write"
jdno = "admin"
cramertj = "write"
KodrAus = "write"
Amanieu = …
```

Add hashbrown repo under automation

---

repos/rust-lang/std-dev-guide.toml

Repo: https://github.com/rust-lang/std-dev-guide
I'm trying to add branch protections where they are missing, so I added one here. Let me know if I should remove it.
CC @m-ou-se
```
name = "std-dev-guide"
description = "Guide for standard library developers"
bots = []
[access.teams]
libs = "maintain"
wg-rustc-dev-guide = "write"
the8472 = "maintain"
cuviper = "maintain"
camelid = "write"
cramertj = "write"
tshepang = "write"
jdno = "admin"
thomcc = "maintain"
m-ou-se = "maintain" …
```

Add std-dev-guide repository under automation

---

repos/rust-lang/libc.toml

Merge qeues have been enabled in the [libc] repository, which require a status check to determine the success of each build.
[libc]: https://github.com/rust-lang/libc

Enable required status check in libc repo

---

repos/rust-lang/libs-team.toml

Repo: https://github.com/rust-lang/libs-team
```
name = "libs-team"
description = "The home of the library team"
bots = []
[access.teams]
bots = "write"
libs = "maintain"
infra = "maintain"
shepmaster = "maintain"
m-ou-se = "maintain"
kennytm = "maintain"
bors = "write"
Amanieu = "maintain"
the8472 = "maintain"
jdno = "admin"
thomcc = "maintain"
Kobzol = "maintain"
cuviper = "maintain"
```

Add libs-team repository under automation

---

repos/rust-lang/llvm-project.toml

Repo: https://github.com/rust-lang/llvm-project
I kept the branch protections, although I'm not sure if they are even needed on this repo.
CC @nikic
```
name = "llvm-project"
description = "Rust-specific fork of LLVM."
bots = []
[access.teams]
wg-llvm = "maintain"
core = "admin"
cuviper = "maintain"
jdno = "admin"
nikic = "maintain"
pattern = "rustc/*"
ci-checks = []
ci-checks = [] …
```

Add llvm-project repository under automation

---

repos/rust-lang/keyword-generics-initiative.toml

Repo: https://github.com/rust-lang/keyword-generics-initiative
```
name = "keyword-generics-initiative"
description = "Public repository for the Rust keyword generics initiative"
bots = []
[access.teams]
jdno = "admin"
```

Add keyword-generics-initiative repo under automation

---

repos/rust-lang/rust-playground.toml

Repo: https://github.com/rust-lang/rust-playground
The proposed configuration protects from direct pushes to `master` and requires PRs, but doesn't require PR approvals. Let me know if I should change it.
CC @shepmaster
```
name = "rust-playground"
description = "The Rust Playground"
bots = []
[access.teams]
shepmaster = "admin"
jdno = "admin"
Kobzol = "admin"
```

Add rust-playground repository under automation

---

repos/rust-lang/rust-log-analyzer.toml

Repo: https://github.com/rust-lang/rust-log-analyzer
```
name = "rust-log-analyzer"
description = "Analyzing Travis and Azure Pipelines logs to find encountered errors"
bots = []
[access.teams]
TimNN = "admin"
jdno = "admin"
```

Add rust-log-analyzer repository under automation

---

repos/rust-lang/portable-simd.toml

Repo: https://github.com/rust-lang/portable-simd
CC @calebzulawski, mainly about the branch protection.
```
name = "portable-simd"
description = "The testing ground for the future of portable SIMD in Rust"
bots = []
[access.teams]
libs = "write"
project-portable-simd = "write"
programmerjake = "write"
workingjubilee = "write"
cramertj = "write"
jdno = "admin"
SimonSapin = "write"
ChrisDenton = "write"
sunfishcode = "write"
miguelraz = "write"
joshtriplett = …
```

Add portable-simd repo under automation

---

repos/rust-lang/nomicon.toml

Repo: https://github.com/rust-lang/nomicon
The rustc-1-* branches looked obsolete, so I removed their branch protections.
```
name = "nomicon"
description = "The Dark Arts of Advanced and Unsafe Rust Programming"
bots = []
[access.teams]
lang = "pull"
lang-docs = "write"
core = "pull"
Gankra = "write"
frewsxcv = "write"
Havvy = "write"
jdno = "admin"
ci-checks = []
review-required = true
pattern = "rust-1.*"
ci-checks = …
```

Add nomicon repo under automation

---

repos/rust-lang/project-error-handling.toml

Repo: https://github.com/rust-lang/project-error-handling
```toml
name = "project-error-handling"
description = "Error handling project group"
bots = []
[access.teams]
libs = "write"
project-error-handling = "write"
jdno = "admin"
nagashi = "write"
mystor = "write"
seanchen1991 = "write"
JDuchniewicz = "write"
```

Add project-error-handling repository under automation

---

repos/rust-lang/rust-installer.toml

Repo: https://github.com/rust-lang/rust-installer
Assigned to `infra`, according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6.
```toml
name = "rust-installer"
description = "The Bourne shell installer used by Rust and Cargo"
bots = []
[access.teams]
core = "admin"
jdno = "admin"
ci-checks = []
review-required = true
```

Add rust-installer repository under automation

---

repos/rust-lang/rustc-rayon.toml

Repo: https://github.com/rust-lang/rustc-rayon
```toml
name = "rustc-rayon"
description = "Rayon: A data parallelism library for Rust"
bots = []
[access.teams]
release = "admin"
core = "admin"
jdno = "admin"
cuviper = "admin"
Dylan-DPC = "admin"
lcnr = "admin"
estebank = "admin"
```

Add rustc-rayon repository under automation

---

repos/rust-lang/miri-test-libstd.toml

Repo: https://github.com/rust-lang/miri-test-libstd
CC @RalfJung
```
name = "miri-test-libstd"
description = "Testing the Rust standard library with Miri, continuously"
bots = []
[access.teams]
miri = "write"
jdno = "admin"
ci-checks = ["Success"]
```

Add miri-test-libstd repository under automation

---

repos/rust-lang/relnotes.toml

Repo: https://github.com/rust-lang/relnotes
```
name = "relnotes"
description = "Generate release notes for \"The Rust Programming Language\""
bots = []
[access.teams]
jdno = "admin"
ci-checks = [
"build (macos-latest, beta)",
"build (macos-latest, nightly)",
"build (macos-latest, stable)",
"build (ubuntu-latest, nightly)",
"build (ubuntu-latest, beta)",
"build (ubuntu-latest, stable)",
"build (windows-latest, beta)",
"build (windows-latest, nightly)",
"build (windows-latest, stable)",
] …
```

Add relnotes repository under automation

---

teams/wg-bindgen.toml

Required for https://github.com/rust-lang/team/pull/1259.

Create a GitHub team for wg-bindgen

---

repos/rust-lang/rust-clippy.toml

Repo: https://github.com/rust-lang/rust-clippy
```
name = "rust-clippy"
description = "A bunch of lints to catch common mistakes and improve your Rust code. Book: https://doc.rust-lang.org/clippy/"
bots = []
[access.teams]
bors = "write"
clippy = "maintain"
jdno = "admin"
flip1995 = "maintain"
Manishearth = "maintain"
Alexendoo = "maintain"
xFrednet = "maintain"
dswij = "maintain"
blyxyas = "maintain"
giraffate = "maintain"
llogiq = "maintain"
Centri3 = "maintain"
matthiaskrgr = "maintain"
Jarcho = "maintain"
bors = "write" …
```

Add rust-clippy repository under automation

---

repos/rust-lang/reference.toml

Repo: https://github.com/rust-lang/reference
Assigned to `lang-docs` according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6.
```
name = "reference"
description = "The Rust Reference"
bots = []
[access.teams]
lang-docs = "write"
lang = "admin"
core = "admin"
QuietMisdreavus = "admin"
Havvy = "admin"
Gankra = "write"
GuillaumeGomez = "admin"
jdno = "admin"
joshtriplett = "admin"
scottmcm = "admin"
frewsxcv = "admin"
steveklabnik = "write" …
```

Add reference repository under automation

---

repos/rust-lang/portable-simd.toml

Requested [here](https://github.com/rust-lang/team/pull/1252#issuecomment-1904719496).
Removes the need for CI to pass, and also removes the requirement to have an approval on PRs.

Weaken branch protection on portable-simd

---

repos/rust-lang/release-team.toml

Repo: https://github.com/rust-lang/release-team
```
name = "release-team"
bots = []
[access.teams]
jdno = "admin"
```

Add release-team repository under automation

---

repos/rust-lang/rust-bindgen.toml

Repo: https://github.com/rust-lang/rust-bindgen
```
name = "rust-bindgen"
description = "Automatically generates Rust FFI bindings to C (and some C++) libraries."
bots = []
[access.teams]
amanjeev = "write"
jdno = "admin"
Manishearth = "admin"
kulp = "write"
pvdrz = "write"
scoopr = "write"
fitzgen = "admin"
emilio = "admin"
pattern = "main"
ci-checks = []
```

Add rust-bindgen repository under automation

---

repos/rust-lang/wg-async.toml

Repo: https://github.com/rust-lang/wg-async
The branch protection requires a PR, but not approvals.
CC @traviscross
```
name = "wg-async"
description = "Working group dedicated to improving the foundations of Async I/O in Rust"
bots = []
[access.teams]
libs = "write"
lang = "write"
wg-async = "write"
guswynn = "write"
jdno = "admin"
nrc = "write"
scottmcm …
```

Add wg-async repository under automation

---

repos/rust-lang/wg-debugging.toml

Repo: https://github.com/rust-lang/wg-debugging
```
name = "wg-debugging"
description = "Work on debugging Rust code, under the compiler team."
bots = []
[access.teams]
wg-debugging = "write"
compiler-errors = "maintain"
jackh726 = "maintain"
petrochenkov = "maintain"
estebank = "maintain"
matthewjasper = "maintain"
jdno = "admin"
```

Add wg-debugging repository under automation

---

repos/rust-lang/rustc_codegen_gcc.toml

Repo: https://github.com/rust-lang/rustc_codegen_gcc
CC @antoyo
```
name = "rustc_codegen_gcc"
description = "libgccjit AOT codegen for rustc"
bots = []
[access.teams]
estebank = "maintain"
petrochenkov = "maintain"
matthewjasper = "maintain"
jackh726 = "maintain"
compiler-errors = "maintain"
jdno = "admin"
antoyo = "write"
```

Add rustc_codegen_gcc repo under automation

---

repos/rust-lang/wg-grammar.toml

Repo: https://github.com/rust-lang/wg-grammar
```
name = "wg-grammar"
description = "Where the work of WG-grammar, aiming to provide a canonical grammar for Rust, resides"
bots = []
[access.teams]
wg-grammar = "admin"
CAD97 = "admin"
jdno = "admin"
```

Add wg-grammar repository under automation

---

repos/rust-lang/zulip_archive.toml

Repo: https://github.com/rust-lang/zulip_archive
```toml
name = "zulip_archive"
description = "A tool for archiving and displaying Zulip chat channels."
bots = []
[access.teams]
bors = "pull"
bots = "pull"
infra = "pull"
jdno = "admin"
```

Add zulip_archive repository under automation

---

repos/rust-lang/wg-cargo-std-aware.toml

Repo: https://github.com/rust-lang/wg-cargo-std-aware
CC @ehuss
```
name = "wg-cargo-std-aware"
description = "Repo for working on \"std aware cargo\""
bots = []
[access.teams]
cargo = "maintain"
Eh2406 = "maintain"
weihanglo = "maintain"
Muscraft = "maintain"
arlosi = "maintain"
ehuss = "maintain"
epage = "maintain"
jdno = "admin"
jamesmunns = "maintain"
```

Add wg-cargo-std-aware repository under automation

---

repos/rust-lang/promote-release.toml

Repo: https://github.com/rust-lang/promote-release
```toml
name = "promote-release"
description = "Tooling to publish Rust releases."
bots = []
[access.teams]
jdno = "admin"
ci-checks = [
"Local release (beta)",
"Local release (nightly)",
"Local release (stable)",
"Build Docker image",
"Test",
]
```

Add promote-release repository under automation

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/some_repo.json
tests/static-api/repos/test-org/some_repo.toml

This enables to allow only some teams to push/merge to specific branches, to make branch protection more fine-grained.
`sync-team` part of this change: https://github.com/rust-lang/sync-team/pull/66

Allow specifying push allowances for branch protection

---

people/alibektas.toml
people/davidbarsky.toml
repos/rust-lang/rust-analyzer.toml
teams/rust-analyzer-contributors.toml
teams/rust-analyzer.toml

We kind of have a use for this again now
@rust-lang/rust-analyzer

Re-introduce rust-analyzer-contributors

---

repos/rust-lang/measureme.toml

Use a conclusion success job to avoid enumerating all the CI jobs from `measureme`.

Rename measureme CI check name

---

repos/rust-lang/generate-manifest-list.toml

Repo: https://github.com/rust-lang/generate-manifest-list
```toml
name = "generate-manifest-list"
description = "Creates a list of manifests on static.rust-lang.org"
bots = []
[access.teams]
jdno = "admin"
```

Add generate-manifest-list repository under automation

---

teams/project-trait-system-refactor.toml

I've originally added myself with the intention of helping with the refactor and did a couple of small PRs but then ended involved in other things. Removing myself without even adding me to alumni properly reflect my relationship with the refactor :).

Remove spastorino from project-trait-system-refactor.toml

---

repos/rust-lang/regex.toml

Commit 55158aeb89463e1fc2d8e5b5321810cb70757fc3 introduced automation
for the regex repo but also enabled branch protection for `master`. The
regex repo has never used branch protection and it is low traffic enough
to be annoying.
While most changes go in through a PR, I do for example push directly to
master when cutting a release (which is done through my own automation
locally).

remove branch protections from regex repo

---

repos/rust-lang/compiler-builtins.toml

Requested by Amanieu, to enable CI checks on the `master` branch.
Blocked on https://github.com/rust-lang/compiler-builtins/pull/569.

Add branch protection for compiler-builtins

---

repos/rust-lang/stdarch.toml

Related PR: https://github.com/rust-lang/stdarch/pull/1519 (this should only be merged after that PR).
We have discussed this with @Amanieu.

Add a CI check for `stdarch`

---

people/upsuper.toml
repos/rust-lang/areweasyncyet.rs.toml

Repo: https://github.com/rust-lang/areweasyncyet.rs
It seems that `upsuper` is maintaining this repo.
```toml
name = "areweasyncyet.rs"
description = "Are we async yet?"
bots = []
[access.teams]
jdno = "admin"
upsuper = "write"
```

Add areweasyncyet.rs repository under automation

---

README.md
src/main.rs
src/schema.rs

Proposed by @rylev [here](https://github.com/rust-lang/team/pull/1271#issuecomment-1905699241).
Allows us to see how many individual accesses there are (we want to eventually get rid of these).

Add command for dumping users with individual access

---

repos/rust-lang/wg-allocators.toml

Repo: https://github.com/rust-lang/wg-allocators
```
name = "wg-allocators"
description = "Home of the Allocators working group: Paving a path for a standard set of allocator traits to be used in collections!"
bots = []
[access.teams]
TimDiekmann = "admin"
SimonSapin = "admin"
ErichDonGubler = "admin"
jdno = "admin"
```

Add wg-allocators repository under automation

---

repos/rust-lang/rustc-pr-tracking.toml

Repo: https://github.com/rust-lang/rustc-pr-tracking
Configuration extracted from GitHub:
```
name = "rustc-pr-tracking"
description = "Statistics about PRs on the rustc repository."
bots = []
[access.teams]
jdno = "admin"
```

Add rustc-pr-tracking repository under automation

---

repos/rust-lang/libc.toml

Same as https://github.com/rust-lang/team/pull/1289 but for the libc-0.2 branch.

Do not require approvals on libc 0.2 branch

---

repos/rust-lang/sync-team.toml
teams/infra-admins.toml

Let's take https://github.com/rust-lang/team/pull/1282 for a test drive.

Only allow infra-admins to merge into `sync-team`

---

repos/rust-lang/generic-associated-types-initiative.toml

Repo: https://github.com/rust-lang/generic-associated-types-initiative
```toml
name = "generic-associated-types-initiative"
description = "Generic Associated Types lang team initiative"
bots = []
[access.teams]
lang = "maintain"
initiative-generic-associated-types = "write"
nikomatsakis = "maintain"
tmandry = "maintain"
scottmcm = "maintain"
jdno = "admin"
```

Add generic-associated-types-initiative repository under automation

---

repos/rust-lang/project-thir-unsafeck.toml

Repo: https://github.com/rust-lang/project-thir-unsafeck
```toml
name = "project-thir-unsafeck"
description = "Tracking the project to refactor the unsafe check to operate on THIR"
bots = []
[access.teams]
compiler-contributors = "admin"
project-thir-unsafeck = "write"
RalfJung = "admin"
tmiasko = "admin"
b-naber = "admin"
the8472 = "admin"
durin42 = "admin"
fee1-dead = "admin"
chenyukang = "admin"
estebank = "admin"
est31 = "admin"
Nilstrieb = "admin"
spastorino = …
```

Add project-thir-unsafeck repository under automation

---

repos/rust-lang/project-portable-simd.toml

Repo: https://github.com/rust-lang/project-portable-simd
```toml
name = "project-portable-simd"
description = "Portable SIMD project group"
bots = []
[access.teams]
libs = "write"
jdno = "admin"
```

Add project-portable-simd repository under automation

---

repos/rust-lang/impl-trait-initiative.toml

Repo: https://github.com/rust-lang/impl-trait-initiative
```toml
name = "impl-trait-initiative"
description = "Impl trait lang team initiative"
bots = []
[access.teams]
initiative-impl-trait = "write"
lang = "maintain"
tmandry = "maintain"
jdno = "admin"
nikomatsakis = "maintain"
scottmcm = "maintain"
```

Add impl-trait-initiative repository under automation

---

repos/rust-lang/moderation-team.toml

Repo: https://github.com/rust-lang/moderation-team
```toml
name = "moderation-team"
description = "Home of the Rust Moderation team."
bots = []
[access.teams]
mods = "write"
jdno = "admin"
technetos = "write"
```

Add moderation-team repository under automation

---

repos/rust-lang/pin-utils.toml

Repo: https://github.com/rust-lang/pin-utils
```toml
name = "pin-utils"
description = "Utilities for pinning"
bots = []
[access.teams]
wg-async = "write"
eholk = "write"
taiki-e = "write"
vincenzopalazzo = "write"
traviscross = "write"
aturon = "write"
nrc = "write"
jdno = "admin"
guswynn = "write"
```

Add pin-utils repository under automation

---

rust_team_data/src/v1.rs
src/static_api.rs
tests/static-api/_expected/v1/permissions/bors.crater.review.json
tests/static-api/_expected/v1/permissions/bors.crater.try.json
tests/static-api/_expected/v1/permissions/bors.crates_io.review.json
tests/static-api/_expected/v1/permissions/bors.crates_io.try.json
tests/static-api/_expected/v1/permissions/crater.json

This PR is similar to https://github.com/rust-lang/team/pull/1196, but adds the new fields to the v1 API instead of introducing a new API version.
---
The v1 permissions API can be misleading in that the order of the `github_users` does not match the order of the `github_ids` (see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/team.20repo.20integration/near/412320079).
This change introduces a new `people` field on the `permissions` API which uses a list of objects instead of an object with multiple single-field lists. This allows us to easily show both GitHub login and ID of a person in the logs.
```json
{
"people": [
{
"name": "Aaron Hill",
"github": "Aaron1011",
"github_id": 1408859,
"discord_id": null
},
{
"name": "Ed Page",
"github": "epage",
"github_id": …
```

Add `people` field to the `permissions` API

---

repos/rust-lang/project-const-generics.toml

Repo: https://github.com/rust-lang/project-const-generics
```toml
name = "project-const-generics"
bots = []
[access.teams]
project-const-generics = "maintain"
nikomatsakis = "maintain"
jdno = "admin"
varkor = "maintain"
BoxyUwU = "maintain"
```

Add project-const-generics repository under automation

---

repos/rust-lang/project-group-template.toml

Repo: https://github.com/rust-lang/project-group-template
Assigned to `leadership-council` according to https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 (essentially replaces `core`).
```toml
name = "project-group-template"
description = "Template for creating Project Groups"
bots = []
[access.teams]
core = "write"
lang = "write"
jdno = "admin"
XAMPPRocky = "admin"
```

Add project-group-template repository under automation

---

repos/rust-lang/project-inline-asm.toml

Repo: https://github.com/rust-lang/project-inline-asm
```toml
name = "project-inline-asm"
description = "Home for the Inline Assembly project group"
bots = []
[access.teams]
lang = "write"
lcnr = "write"
jdno = "admin" …
```

Add project-inline-asm repository under automation

---

repos/rust-lang/mdBook.toml

https://github.com/rust-lang/team/pull/1246 added mdbook to the team repo, but I did not notice that it removed @Dylan-DPC's permissions. This restores those permissions.
I was intending to create a team for this, but I will need to write an RFC first.

Fix mdbook permissions

---

repos/rust-lang/rfcbot-rs.toml

Repo: https://github.com/rust-lang/rfcbot-rs
```toml
name = "rfcbot-rs"
description = "Coordinates asynchronous decision making on Rust repositories. Status of tracked issues and PRs can be viewed at https://rfcbot.rs."
bots = []
[access.teams]
aturon = "write"
jdno = "admin"
anp = "write"
```

Add rfcbot-rs repository under automation

---

repos/rust-lang/rust-dbg-ext.toml

Repo: https://github.com/rust-lang/rust-dbg-ext
```toml
name = "rust-dbg-ext"
bots = []
[access.teams]
initiative-async-crashdump-debugging = "maintain"
jdno = "admin"
```

Add rust-dbg-ext repository under automation

---

repos/rust-lang/rust-lang.github.io.toml

Repo: https://github.com/rust-lang/rust-lang.github.io
```toml
name = "rust-lang.github.io"
description = "GitHub Pages redirects"
bots = []
[access.teams]
jdno = "admin"
```

Add rust-lang.github.io repository under automation

---

repos/rust-lang/rust-mode.toml

Repo: https://github.com/rust-lang/rust-mode
Maybe the `emacs` team should be a subteam of `devtools`?
```toml
name = "rust-mode"
description = "Emacs configuration for Rust"
bots = []
[access.teams]
emacs = "write"
core = "admin"
jimblandy = "write"
MicahChalmer = "write"
psibi = "write"
jdno = "admin"
tromey = "write"
brotzeit = "write"
```

Add rust-mode repository under automation

---

repos/rust-lang/rust-repos.toml

Repo: https://github.com/rust-lang/rust-repos
```toml
name = "rust-repos"
description = "Dataset of Rust source code repositories"
bots = []
[access.teams]
jdno = "admin"
```

Add rust-repos repository under automation

---

repos/rust-lang/rustup-components-history.toml

Repo: https://github.com/rust-lang/rustup-components-history
```toml
name = "rustup-components-history"
description = "Rustup package status history"
bots = []
[access.teams]
jdno = "admin"
mexus = "write"
```

Add rustup-components-history repository under automation

---

repos/rust-lang/api-guidelines.toml

Repo: https://github.com/rust-lang/api-guidelines
CC @dtolnay
```toml
name = "api-guidelines"
description = "Rust API guidelines"
bots = []
[access.teams]
libs = "maintain"
cuviper = "maintain"
m-ou-se = "maintain"
Amanieu = "maintain"
thomcc = "maintain"
jdno = "admin"
the8472 = "maintain"
```

Add api-guidelines repository under automation

---

repos/rust-lang/jobserver-rs.toml

Repo: https://github.com/rust-lang/jobserver-rs
```toml
name = "jobserver-rs"
bots = []
[access.teams]
cargo = "write"
weihanglo = "write"
Muscraft = "write"
arlosi = "write"
epage = "write"
jdno = "admin"
lcnr = "write"
Eh2406 = "write"
alexcrichton = "write"
wesleywiser …
```

Add jobserver-rs repository under automation

---

repos/rust-lang/rustup.toml

The rustup repository has enabled GitHub's merge queue feature, which requires a status check to determine the health of each build. The respective job has already been configured, but not enabled as a required status check.
cc @rami3l

Enable required status checks for rustup

---

src/validate.rs
teams/community.toml
teams/docker.toml
teams/launching-pad.toml
teams/twir.toml
teams/web-presence.toml
teams/wg-async.toml
teams/wg-cli.toml
teams/wg-embedded.toml
teams/wg-gamedev.toml
teams/wg-rust-by-example.toml
teams/wg-secure-code.toml
teams/wg-security-response.toml
teams/wg-triage.toml
teams/wg-wasm.toml

This adds the launching-pad team, and connects all of its subteams into it. This should help with tracking the team membership and their status and connections.
cc @jonathanpallant

Add launching-pad team.

---

rust_team_data/src/v1.rs
src/github.rs
src/main.rs
src/schema.rs
src/zulip.rs

I don't think github (zulip, discord) IDs are platform dependant.

Don't use `usize`s for user ids

---

repos/rust-lang/rustlings.toml

Repo: https://github.com/rust-lang/rustlings
CC @shadows-withal
Not sure if there should be a separate team for this?
```toml
name = "rustlings"
description = ":crab: Small exercises to get you used to reading and writing Rust code!"
bots = []
[access.teams]
jdno = "admin"
shadows-withal = "admin"
AbdouSeck = "write"
jrvidal = "write"
carols10cents = "write"
```

Add rustlings repository under automation

---

repos/rust-lang/packed_simd.toml

Repo: https://github.com/rust-lang/packed_simd
CC @workingjubilee regarding the permissions.
```toml
name = "packed_simd"
description = "Portable Packed SIMD Vectors for Rust standard library"
bots = []
[access.teams]
libs = "write"
project-portable-simd = "write"
jdno = "admin"
miguelraz = "write"
sunfishcode = "write"
calebzulawski = "write"
SimonSapin = "write"
KodrAus = "write"
workingjubilee = "write"
GabrielMajeri = "write"
programmerjake = …
```

Add packed_simd repository under automation

---

repos/rust-lang/crater.toml

Repo: https://github.com/rust-lang/crater
Not sure if `highfive` is needed. Also, the CI check is weird, I haven't found any job named `homu` in the CI workflows. But it's not used anyway when `bors` is enabled on the repo (AFAIK).
```toml
name = "crater"
description = "Run experiments across parts of the Rust ecosystem!"
bots = []
[access.teams]
bots = "write"
bors = "write"
jdno = "admin"
ci-checks = ["homu"] …
```

Add crater repository under automation

---

repos/rust-lang/gha-runner.toml

Repo: https://github.com/rust-lang/gha-runner
```toml
name = "gha-runner"
description = "Custom fork of the GitHub Actions runner"
bots = []
[access.teams]
jdno = "admin"
```

Add gha-runner repository under automation

---

repos/rust-lang/gha-self-hosted.toml

Repo: https://github.com/rust-lang/gha-self-hosted
```toml
name = "gha-self-hosted"
description = "GitHub Actions self-hosted runners infrastructure"
bots = []
[access.teams]
jdno = "admin"
```

Add gha-self-hosted repository under automation

---

repos/rust-lang/cc-rs.toml

Since the crate only has a single active maintainer, it doesn't make sense to require separate approval for PRs.
cc @NobodyXu

Remove required approvals for cc-rs

---

rust_team_data/src/v1.rs
src/data.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/repos/archive/test-org/archived_repo.toml

Archived repos are in `repos/archive`. Currently there is no validation that the repo contains no team access, I can add it if you want.

Add support for repo archiving

---

tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json

Not sure why this changed, but https://github.com/rust-lang/team/pull/1357 is failing on this.

Bless test output.

---

people/eth3lbert.toml
teams/crates-io.toml

We just discussed in the crates.io meeting to invite @eth3lbert to the team and they accepted. This PR officially adds them to the team and should hopefully sync the GitHub/Zulip/etc. permissions accordingly.
r? @rust-lang/team-repo-admins 
/cc @rust-lang/crates-io

crates.io: Add `eth3lbert` to the team

---

teams/style.toml

Jane is stepping down from t-style
Her contributions, both style design and procedural work involved in launching a new team, were invaluable and we're incredibly grateful :pray: 
You'll be missed @yaahc and if you ever find yourself with available bandwidth again we'd love to have you back :heart:

Jane stepping down from Style Team

---

src/main.rs
src/zulip.rs

Show `zulip_id` if present.
In addition, if ZULIP_USER and ZULIP_TOKEN are set, try to look up the user's name (as shown in Zulip itself). This is useful for finding people whose Zulip name differs from their GitHub name.

Show Zulip details in 'show-person'.

---

repos/rust-lang/project-exploit-mitigations.toml

This removes what appears to be something that was left behind when previous core entries were removed.

Remove remaining reference to core team.

---

people/LukeMathWalker.toml
people/adriantombu.toml
people/marcoow.toml
teams/arewewebyet.toml

As discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/.60arewewebyet.60.20repo), the current maintainers of https://github.com/rust-lang/arewewebyet would appreciate help with the project.
This PR adds four more people as maintainers to the team (and thus indirectly to the repository):
- @adriantombu
- @LukeMathWalker
- @marcoow
- and myself (@Turbo87)
r? @rust-lang/team-repo-admins 
/cc @ibraheemdev @giraffate

arewewebyet: Add new maintainers

---

people/antoyo.toml
teams/wg-gcc-backend.toml

As suggested [here](https://github.com/rust-lang/team/pull/1371#discussion_r1519874386) and [there](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/meeting.202024-03-11/near/425934306), I'm creating a team for rustc_codegen_gcc.
This team will manage the existing rustc_codegen_gcc repo as well as the 2 new repos that were recently moved to the rust-lang organization [in this PR](https://github.com/rust-lang/team/pull/1371).

Add gcc-backend team

---

rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/_expected/v1/repos/some_repo.json

This will enable `sync-team` to enable this option on GH. It is not exposed to users directly, it is auto-derived from the presence of `bors`.

Add `auto_merge` option to repositories

---

repos/archive/rust-lang/all-hands-2020.toml

Repo: https://github.com/rust-lang/all-hands-2020
This repo is not actually archived yet, but I think that it should be uncontroversial to archive it, which should test the new archiving sync functionality.
```toml
name = "all-hands-2020"
description = "Website for the Rust All Hands 2020"
bots = []
[access.teams]
jdno = "admin"
XAMPPRocky = "admin"
```

Add `all-hands-2020` under automation (archived)

---

repos/rust-lang/rustc_codegen_gcc.toml

With https://github.com/rust-lang/team/pull/1372 merged, the repo permissions for the rustc_codegen_gcc repo should now be able to go under the team.
cc @rust-lang/wg-gcc-backend

Switch rustc_codegen_gcc to team access

---

repos/rust-lang/book.toml

With https://github.com/rust-lang/team/pull/1213 merged, the repo permissions for the book repo should now be able to go under the team.
cc @rust-lang/book

Switch book repo to team access

---

src/schema.rs

This removes an unused struct `DiscordTeam`. It was added in https://github.com/rust-lang/team/pull/538, but it is not clear why as it is never used.  There is a similar `TeamDiscord`, so perhaps it was just a mistake.

Remove unused DiscordTeam

---

repos/archive/rust-lang/zsh-config.toml

This PR adds the first archived managed repo, so that we have something to test for https://github.com/rust-lang/sync-team/pull/71.
This repo is actually already archived, so the sync should be a no-op.
Repo: https://github.com/rust-lang/zsh-config
```
name = "zsh-config"
description = "zsh configuration for Rust"
bots = []
[access.teams]
core = "admin"
jdno = "admin"
```

Add `zsh-config` under automation (archived)

---

repos/rust-lang/simpleinfra.toml

This will also allow using auto-merge rather than waiting for the checks to pass.

Require CI to pass in simpleinfra

---

teams/project-keyword-generics.toml

Adds @traviscross to the keyword generics initiative who has been active in the initiative for a while. That should enable pings on Zulip and Github to work. Thanks!

Add TC to keyword generics initiative

---

repos/rust-lang/stacker.toml

Repo: https://github.com/rust-lang/stacker
Added under `compiler`, based on https://github.com/rust-lang/stacker and a discussion with @nagisa.
```toml
name = "stacker"
description = "Manual segmented stacks for Rust"
bots = []
[access.teams]
lcnr = "admin"
jdno = "admin"
estebank = "admin"
```

Add `stacker` under automation

---

repos/rust-lang/async-crashdump-debugging-initiative.toml

Repo: https://github.com/rust-lang/async-crashdump-debugging-initiative
Confirmed with @mw that this is still active.
```toml
name = "async-crashdump-debugging-initiative"
bots = []
[access.teams]
initiative-async-crashdump-debugging = "maintain"
jdno = "admin"
```

Add `async-crashdump-debugging-initiative` under automation

---

repos/rust-lang/odht.toml

Repo: https://github.com/rust-lang/odht
Confirmed with @michaelwoerister that this is still maintained by `t-compiler`.
```toml
name = "odht"
description = "An on-disk hash table implementation"
bots = []
[access.teams]
Nadrieril = "write"
eholk = "write"
BoxyUwU = "write"
estebank = "maintain"
apiraino = "write"
jdno = "admin"
b-naber = "write"
lqd = "write"
flodiebold = "write"
TaKO8Ki = "write" …
```

Add `odht` under automation

---

repos/rust-lang/monitorbot.toml

Repo: https://github.com/rust-lang/monitorbot
```toml
name = "monitorbot"
description = "Monitoring of external API services Rust infrastructure relies upon"
bots = []
[access.teams]
jdno = "admin"
```

Add `monitorbot` under automation

---

repos/rust-lang/rust-artwork.toml

Repo: https://github.com/rust-lang/rust-artwork
Since this hasn't been touched in years, I think it's fine to leave it without any access currently (?). I wouldn't archive it though, as it the content itself it probably still relevant.
CC @nikomatsakis
```toml
name = "rust-artwork"
description = "Official artwork for the Rust project."
bots = []
[access.teams]
core = "pull"
jdno = "admin"
```

Add `rust-artwork` under automation

---

rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs

Adds a new Renovate bot entry. This bot works through a GitHub app, I'll implement syncing for GH apps in `sync-team` as a follow-up step.
Previous discussion: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Add.20GitHub.20Apps.20in.20team.20repo

Add RenovateBot

---

repos/rust-lang/pontoon.toml

Repo: https://github.com/rust-lang/pontoon
Maybe we will want to archive this soon (https://github.com/rust-lang/infra-team/issues/91), but in any case it should be managed by `team` (unless we want to delete it completely).
```toml
name = "pontoon"
description = "Localization platform used by Rust"
bots = []
[access.teams]
community = "triage"
bors = "write"
bots = "write"
Manishearth = "triage"
technetos = "triage"
jdno = "admin"
XAMPPRocky = "write"
JohnTitor = "triage"
sebasmagri = "triage"
nellshamrell = "triage"
bors = "write"
rust-timer = …
```

Add `pontoon` under automation

---

repos/rust-lang/datafrog.toml

Repo: https://github.com/rust-lang/datafrog
CC @lqd, looks good?
```toml
name = "datafrog"
description = "A lightweight Datalog engine in Rust"
bots = []
[access.teams]
core = "admin"
wg-polonius = "write"
lcnr = "admin"
ecstatic-morse = "write"
lqd = "write"
shepmaster = "admin"
amandasystems = "write"
Kobzol = "admin"
estebank = …
```

Add `datafrog` under automation

---

repos/rust-lang/rustlings.toml
teams/rustlings.toml

I want to add a co-maintainer to Rustlings (which will be done in a later step), so I'm converting the single person repo permission into a team permission. This is not a formal team or anything, just a convenience to let multiple people have the same permission, hence why the team itself is very minimal.

feat: convert rustlings membership to a team

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/compiler.toml
teams/crates-io.toml
teams/devtools.toml
teams/infra.toml
teams/lang.toml
teams/launching-pad.toml
teams/libs.toml
teams/mods.toml
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/alumni.json
tests/static-api/_expected/v1/teams/foo.json
tests/static-api/_expected/v1/teams/leaderless.json
tests/static-api/_expected/v1/teams/leadership-council.json
tests/static-api/_expected/v1/teams/leads-permissions.json
tests/static-api/_expected/v1/teams/wg-test.json
tests/static-api/teams/alumni.toml
tests/static-api/teams/foo.toml
tests/static-api/teams/leaderless.toml
tests/static-api/teams/leadership-council.toml
tests/static-api/teams/leads-permissions.toml
tests/static-api/teams/wg-test.toml

This changes it so that Teams, Working Groups, and Project Groups set the `subteam-of` field. Marker teams do not require it.
The reason is to ensure that teams are connected, and to make it a little easier to connect the top-level teams to the leadership-council.

Require subteam-of to be specified.

---

repos/rust-lang/crates.io.toml

Repo: https://github.com/rust-lang/crates.io
Here we can see a case where both bors and the `crates-io` team had an explicit permission to push to `master`:
```toml
allowed-merge-teams = [
"bors",
"crates-io",
]
```
which we can now automate (`bors` is added to these teams automatically, that's why it's missing in the PR).
However, `master` didn't require a PR before. I thought that our automation always requires a PR for each protected branch, but now that I think of it, if we set `allowed-merge-teams`, which sets `pushActorIds`, and also `restrictsPushes`, then maybe this allows only pushes and not PRs? (which is how bors works?).
```toml
name = "crates.io"
description = "The Rust package registry"
bots = []
[access.teams]
bots = "write"
core = …
```

Add crates.io repository under automation

---

repos/rust-lang/annotate-snippets-rs.toml
repos/rust-lang/blog.rust-lang.org.toml
repos/rust-lang/cargo.toml
repos/rust-lang/rfcs.toml
repos/rust-lang/rustup.toml

This PR adds Renovate bot to all managed repositories that currently use it (source: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Repos.20that.20use.20renovatebot/near/427884837).
We need to merge this before https://github.com/rust-lang/sync-team/pull/75 is merged, otherwise `sync-team` would uninstall the bot from the repositories.

Add renovate bot to managed repositories that use it

---

people/mo8it.toml
teams/rustlings.toml

Adding @mo8it to co-maintain Rustlings :tada: 
Sidenote: I assume this change will automatically invite them to the `rust-lang` org? Or does that need to be done manually by someone with permissions?

feat: add mo8it to rustlings team

---

people/jswrenn.toml
src/validate.rs
teams/wg-safe-transmute.toml

Make @jswrenn the lead and retire @rylev from the working group.
This also adds an email for @jswrenn and improves the error message when a required email address is missing. 
r? @rust-lang/team-repo-admins

Promote jswrenn to lead of wg-safe-transmute, and retire rylev

---

repos/rust-lang/llvm-project.toml

To restore to something that more closely resembles the state before https://github.com/rust-lang/team/pull/1208. Merging new changes from upstream release branches into our fork doesn't really benefit from going through a PR or review, especially for work-in-progress upgrade branches.
I would have preferred to keep the "no force push and branch deletion" part of the branch protection, but it looks like disabling the PR requirement is not supported.

Drop branch protections on llvm-project

---

people/J-ZhengLi.toml
people/m-rph.toml
repos/rust-lang/rust-clippy.toml
teams/clippy-contributors.toml

This PR adds the new *Clippy-Contributors* team which has been proposed in rust-lang/rust-clippy#12481 and was accepted on Zulip yesterday! :tada:
As part of this PR, I also want to welcome the four initial heroes, who will start be part of this team:
* @GuillaumeGomez
* @J-ZhengLi
* @m-rph
* @pitaj
Thank you, for all the work you already put into Clippy. We're happy to have you! :heart:
---
cc: rust-lang/clippy
r? @flip1995 & @Manishearth

Add the new *Clippy-Contributors* team 🎉

---

repos/rust-lang/nomicon.toml

It should be upper-cased: https://github.com/rust-lang/nomicon/blob/6bc2415218d4dd0cb01433d8320f5ccf79c343a1/.github/workflows/main.yml#L6

Correct nomicon CI name

---

teams/ospp.toml

Registration for [OSPP](https://summer-ospp.ac.cn/) requires a public email address for the project.

Add mailing list for ospp@rust-lang.org

---

repos/archive/rust-lang/governance.toml
repos/archive/rust-lang/libbacktrace.toml
repos/archive/rust-lang/mirror-google-fuchsia-zircon.toml

**These repositories are not yet archived!**
Repositories were selected based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and usage statistics.
- https://github.com/rust-lang/governance
<details>
```toml
name = "governance"
description = "The home for Rust's governance documentation, such as team charters."
bots = []
[access.teams]
yaahc = "admin"
jdno = "admin"
```
</details>
- https://github.com/rust-lang/libbacktrace
<details>
```toml
name = "libbacktrace"
description = "A C library that may be linked into a C/C++ program …
```

Add a batch of 3 repositories for archival #2

---

repos/rust-lang/leadership-council.toml
teams/council-librarians.toml

This is to help @ehuss with the maintenance of https://github.com/rust-lang/leadership-council

Add council-librarians team for working on the leadership council repo

---

repos/rust-lang/project-deref-patterns.toml

Repo: https://github.com/rust-lang/project-deref-patterns
Based on a discussion [here](https://github.com/rust-lang/team/pull/1388#issuecomment-2002085244).
```toml
name = "project-deref-patterns"
bots = []
[access.teams]
chorman0773 = "admin"
jdno = "admin"
nrc = "admin"
```

Add `project-deref-patterns` under automation

---

repos/rust-lang/rust.vim.toml

Repo: https://github.com/rust-lang/rust.vim
This doesn't seem to be [actively maintained](https://github.com/rust-lang/rust.vim/issues/502) at the moment, although people seem to be still using it. Maybe we should archive it to make it clear that it's unmaintained?
```toml
name = "rust.vim"
description = "Vim configuration for Rust."
bots = []
[access.teams]
core = "admin"
vim = "write"
jdno = "admin"
chris-morgan = "write"
da-x = "write"
```

Add `rust.vim` under automation

---

repos/archive/rust-lang/project-thir-unsafeck.toml
teams/archive/project-thir-unsafeck.toml
teams/project-thir-unsafeck.toml

THIR unsafeck is now stable since 1.77 (https://github.com/rust-lang/rust/pull/117673/) and MIR unsafeck has since been removed (https://github.com/rust-lang/rust/pull/123322) :tada: I think we should therefore archive the working group.
It was also outdated. I added @LeSeulArtichaut to alumni, which afaict was not possible when they left the project in https://github.com/rust-lang/team/pull/621. I also added @matthewjasper as a member as they've been doing most of the work towards actually getting it stabilized.
Unsure what to do with the afaict dead zulip stream (https://rust-lang.zulipchat.com/#narrow/stream/278509-project-thir-unsafeck). Ideally it should be archived and locked.
cc @nikomatsakis

update and archive project-thir-unsafeck

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/_expected/v1/repos/some_repo.json

This PR adds a `private-non-synced` field to the TOML schema. It should serve for documentation purposes to mark private repositories, but it actually won't be managed by automation (`sync-team`), because the action of making a repository private is destructive.

Add the possibility to mark a repository as private

---

repos/archive/rust-lang/docker-rust-nightly.toml

Repo: https://github.com/rust-lang/docker-rust-nightly
I copied the permissions from the `docker-rust` repo.
```
name = "docker-rust-nightly"
bots = []
[access.teams]
infra = "pull"
rust-highfive = "admin"
jdno = "admin"
sfackler = "admin"
```

Add docker-rust-nightly repository under automation (archived)

---

repos/archive/rust-lang/wg-grammar.toml
teams/archive/wg-grammar.toml

wg-grammar has not met in several years, so I think it is time to go ahead and retire it. I don't foresee it starting up again. Also, I'm presuming that the spec team will be picking up this work in some form.
cc @rust-lang/wg-grammar 
cc @rust-lang/spec

Retire wg-grammar

---

repos/rust-lang/rustc-reading-club.toml

Repo: https://github.com/rust-lang/rustc-reading-club
```toml
name = "rustc-reading-club"
description = "Rust Code Reading Clubs"
bots = []
[access.teams]
wg-rustc-reading-club = "maintain"
matthewjasper = "maintain"
estebank = "maintain"
jackh726 = "maintain"
petrochenkov = "maintain"
doc-jones = "maintain"
jdno = "admin"
compiler-errors = "maintain"
nikomatsakis = …
```

Add `rustc-reading-club` under automation

---

teams/project-edition-2024.toml

In the lang design meeting on 2024-04-10 (with Eric Huss and Mara present), there formed a consensus that I would take on responsibility for the project management of getting the Rust 2024 edition released.
We understand that bstrie is stepping away from this effort, and we thank him for all the good work he's done to this point.
Correspondingly, in this commit, we add me (TC) to the Rust 2024 edition project as a member and a lead, and we remove bstrie.
cc @ehuss @m-ou-se @bstrie

Join and lead the Rust 2024 edition project

---

repos/rust-lang/rustwide.toml

Context: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/getting.20changes.20into.20rustwide.20.2F.20helping.20with.20maintenance.3F

Give access to rustwide to docs.rs maintainers

---

teams/crates-io.toml
teams/devtools.toml
teams/leadership-council.toml

This implements [RFC#3595], which entails:
- Moving the crates.io team to be a subteam of devtools
- Removing @carols10cents from Leadership Council
[RFC#3595]: https://github.com/rust-lang/rfcs/pull/3595
Bye council! Have fun! 👋🏻

Implement RFC#3595 Moving crates.io under devtools

---

people/hkratz.toml
people/inflation.toml
people/nvzqz.toml
teams/apple.toml

We discussed today [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/I'd.20like.20to.20contribute.20more.20.28to.20Apple-specific.20stuff.29/near/434259421) that it might make sense to expand the scope of this team to include the other Apple platforms, namely iOS, tvOS, watchOS and visionOS.
Pinging current members of the team; @hkratz, @inflation, @shepmaster, @thomcc, @nvzqz.
Are you fine with the expanded scope of the team, and being on the ping list for `@rustbot ping apple`?
Additionally, I've introduced the `apple` Zulip ping group, does this make sense, and are you fine with being in that ping group? (if not, I'll add you to the `excluded-people`).
(Note that this is not officially affiliated with Apple, it's just the name that makes the most sense). …

Rename `macos` team to `apple`, and add `apple` Zulip group

---

repos/rust-lang/rustc-demangle.toml

Mentioned [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.22test.22.20job.20not.20completing).

Fix branch protection of `rustc-demangle`

---

repos/rust-lang/rust-project-goals.toml

I opted to just give a bunch of teams access rather than creating a new WG given that (right now) it'd just be me.

manage rust-project-goals in teams repository

---

teams/libs-contributors.toml

From this comment, I'm wondering if I should have bors privileges: https://github.com/rust-lang/rust/pull/121269#issuecomment-1951374615
I don't think it makes sense to add bors permissions to the project-portable-simd team so adding myself to @rust-lang/libs-contributors might be correct?  Feel free to suggest any alternatives, and I'm not offended if this doesn't go anywhere.  Thanks!

Add calebzulawski to libs-contributors

---

people/Oneirical.toml
teams/gsoc-contributors.toml

Adds a `gsoc-contributors` team with access to dev desktops. Eventually we should add all the GSoC participants, but for now it would be great if we could unblock people that need access to dev desktops.
CC @Oneirical if you want me to modify your details or name (we can also do that later).

Add `gsoc-contributors` team

---

repos/rust-lang/crates.io-infra.toml

Repo: https://github.com/rust-lang/crates.io-infra
This is a **private** repository.
I'm not sure if it should be archived or not, the linked website doesn't seem to work.
CC @pietroalbini
```toml
name = "crates.io-infra"
description = "is ur crates.io running?"
bots = []
[access.teams]
infra = "pull"
crates-io-on-call = "write"
crates-io = "write"
hi-rustin = "write"
mdtro = "write"
carols10cents = "write"
Xylakant = "write"
tshepang = "write"
justahero = "write"
jtgeibel = "write"
Turbo87 = "write"
LawnGnome = "write"
listochkin = "write"
jdno = "admin"
```

Add `crates.io-infra` repository under automation (private)

---

repos/rust-lang/pentest-2019.toml

Repo: https://github.com/rust-lang/pentest-2019
This is a **private** repository.
```toml
name = "pentest-2019"
description = "Primarily security-related bug tracking"
bots = []
[access.teams]
core = "admin"
jdno = "admin"
sgrif = "write"
rust - lang - owner = "admin"
QuietMisdreavus = "write"
```

Add `pentest-2019` repository under automation (private)

---

repos/rust-lang/surveys-private.toml

Repo: https://github.com/rust-lang/surveys-private
This is a **private** repository.
```toml
name = "surveys-private"
description = "A private repository for survey data that is only accessible to the survey working group (and admins)"
bots = []
[access.teams]
community-survey = "maintain"
Kobzol = "maintain"
apiraino = "maintain"
jdno = "admin"
```

Add `surveys-private` repository under automation (private)

---

repos/rust-lang/nomicon.toml
repos/rust-lang/reference.toml

The lang team previously had permissions on the reference, but that was removed in https://github.com/rust-lang/team/pull/1253, which was an oversight on my part. This adds it back, as well to the nomicon since it is spiritually similar, though I don't expect much participation.
cc @rust-lang/lang-docs @rust-lang/lang

Add lang team to reference and nomicon repos

---

teams/rust-for-linux.toml

So that we can ping the RfL maintainers.

Add a Rust for Linux marker team

---

people/dingxiangfei2009.toml
people/metaspace.toml
people/wedsonaf.toml
people/y86-dev.toml
teams/rust-for-linux.toml

The original PR (#1457) was meant as a starting point, so fill the ping group now.
This includes the full Rust for Linux core team, plus other knowledgeable contributors on RFL, Rust and/or the unstable features we use.
Thanks everyone!
Cc: @alex
Cc: @bjorn3
Cc: @Darksonn
Cc: @dingxiangfei2009
Cc: @fbq
Cc: @metaspace
Cc: @nbdd0121
Cc: @tgross35
Cc: @wedsonaf
Cc: @y86-dev

Fill the Rust for Linux ping group

---

Cargo.toml
rust_team_data/Cargo.toml
rust_team_data/LICENSE-APACHE
rust_team_data/LICENSE-MIT

We have put two license files in the repo root,
but never declared them in Cargo.toml.
This PR fills in the `workspace.package.license` field,
so that every workspace members can just inherit from it.
This was found during the course of vendoring rustc-perf in rust-lang/rust: <https://github.com/rust-lang/rust/pull/125465#issuecomment-2130745904>.

feat: add missing license

---

repos/rust-lang/rustc-stable-hash.toml

This PR add/create the `rustc-stable-hash` repository, so that we can extract `rustc` stable hashing algorithm into it's own crate and use it in other projects (like Cargo).
cc @davidtwco @WaffleLapkin @weihanglo

Add `rustc-stable-hash` repo

---

repos/rust-lang/backtrace-rs.toml
repos/rust-lang/flate2-rs.toml

As part of [RFC 2872](https://rust-lang.github.io/rfcs/2872-github-access-policy.html), this removes a few individuals from repository access.
This removes @alexcrichton's individual access to backtrace-rs and flate2-rs. For example, in https://github.com/rust-lang/flate2-rs/pull/325#issuecomment-1329548584 he has mentioned handing maintenance off.
This also removes `brson`'s access to flate2-rs, since I don't think he has ever been directly involved in that project, and has generally not been involved in rust-lang projects for many years.
cc #749

Remove alex's individual repo access.

---

README.md
docs/toml-schema.md

This updates the documentation on GitHub access to incorporate [RFC 2872](https://rust-lang.github.io/rfcs/2872-github-access-policy.html).
I decided to break the schema docs into sections, which makes it a little easier to write explanatory content instead of using TOML comments.

Update GitHub repository access docs.

---

repos/rust-lang/docs.rs.toml

with the current state of the team I need to be able to merge PRs without approval.

remove required approvals from docs.rs repo

---

teams/wg-wasm.toml

I used to be part of the Rust Wasm WG, but no longer am. It seems likely I was missed by https://github.com/rust-lang/team/issues/1125. Thanks!

Add yosh as a wasm wg alumnus

---

teams/project-const-generics.toml

@BoxyUwU has recently started to do a lot of work on const-generics again and is currently taking over pretty much all of the responsibilities of the lead.
This PR therefore adjusts the organizational structure to match reality and promotes her as the new lead, moving @lcnr to co-lead and @nikomatsakis to an ordinary member.
r? @nikomatsakis cc @rust-lang/project-const-generics

project const generics: BoxyUwU as lead

---

teams/rustdoc-frontend.toml

https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.202024-06-10/near/438892399

rustdoc: reorg to frontend subteam for UI/UX and main team

---

repos/rust-lang/reference.toml

This gives the spec team permissions for the reference repository.
cc @rust-lang/spec

Give the spec team write-access to the reference.

---

people/BartMassey.toml
people/hdoordt.toml
teams/wg-embedded-resources.toml

This PR adds two new members, @hdoordt and @bartmassey, and moves Andre to the alumni section.
This matches our current team enrollment: https://github.com/rust-embedded/wg?tab=readme-ov-file#the-resources-team

Update WG-Embedded Resources subteam with current members

---

repos/rust-lang/edition-guide.toml

The nightly copy is updated more frequently, so it provides a more current version.

Switch edition-guide homepage link to nightly

---

people/chorman0773.toml
repos/rust-lang/reference.toml
repos/rust-lang/spec.toml
teams/spec-contributors.toml

In our meeting on 2024-07-11, the spec team decided to create a `spec-contributors` team and to add Connor Horman to it given his new role as a contractor hired by the Rust Foundation to do work on the specification.
cc @ehuss @JoelMarcey @pnkfelix @m-ou-se @chorman0773

Add `spec-contributors` team

---

teams/project-const-generics.toml

While their work on const generics has been invaluable, they haven't been active recently. Mirroring #1074, let's move them to alumni status to accurately reflect the status quo.
Thank you for your work @varkor and you're welcome to join again if/once you decide to contribute again!
r? @BoxyUwU

move varkor to Project Const Generics alumni

---

teams/compiler-contributors.toml

As discussed on the T-compiler mailing list, alumni can just be readded without waiting for team consensus

Add Alex Crichton as compiler contributor

---

teams/types.toml

@aliemjay has not been online recently and we were not able to contact them zulip. Given that we're unable to reach them, @jackh726 and I decided to remove them from the FCP rotation for now. We hope they are doing well and remain thankful for their existing contributions to the Types Team.
They are still a member of the team and are able to register concerns as blocking. This change can be reverted once they are active again.
r? @jackh726 cc @rust-lang/types

exclude inactive member from Types Team FCPs

---

repos/rust-lang/reference.toml

More CI jobs are being added in https://github.com/rust-lang/reference/pull/1542. To make it easier to manage, I'm switching it to a summary job which will have a different name.

Update CI job name for the reference.

---

repos/rust-lang/rustfmt.toml

The rustfmt repo doesn't have bors enabled, the rustfmt team only consists of 2 people, myself and Yacin (who's on vacation for the next couple weeks), and we've got a branch protection policy that requires a review.
I've got some sequential work for the rustfmt 2024 items that's predicated on getting [some things](https://github.com/rust-lang/rustfmt/pull/6253) merged, which means I'm completely blocked at the moment. I previously had the ability to override this as an admin, but based on some [discussion in Zulip] my understanding is that the repo permissions were changed and the way to "override" this now is to temporarily disable the review requirement.
[discussion in Zulip]: https://rust-lang.zulipchat.com/#narrow/stream/357797-t-rustfmt/topic/new.20syntax.20support/near/446195934

grant ability to merge rustfmt PRs

---

README.md
people/lqd.toml

This adds my zulip id so that [project goal pings](https://rust-lang.zulipchat.com/#narrow/stream/435869-project-goals/topic/Scalable.20Polonius.20support.20on.20nightly.20.28goals.23118.29/near/454329533) work on zulip.
I've also updated the instructions to get the zulip id, as there's a new step to do since this was written.

add my zulip id for automated pings

---

teams/crates-io-on-call.toml

Veykril is being added to the on-call rotation for crates.io.
cc @pietroalbini @Veykril

Add Veykril to crates-io-on-call team

---

repos/rust-lang/nomicon.toml

In https://github.com/rust-lang/nomicon/pull/459 we are switching to merge queue, which includes a "consolidation" job.

Update nomicon ci job name

---

src/validate.rs

When reading this error from CI, now it's clear that the username changed in GitHub (not in Zulip for example)

chore: improve validation error message

---

repos/archive/rust-lang/crates.io-infra.toml

This PR:
- moves the file in the correct directory
- removes team access, as requested in https://github.com/rust-lang/team/pull/1521#issuecomment-2296688402

fix: archive repo correctly

---

repos/rust-lang/cmake-rs.toml
repos/rust-lang/libm.toml

Requires:
- https://github.com/rust-lang/cmake-rs/pull/218
- https://github.com/rust-lang/libm/pull/299
Unfortunately I can't merge either of those since https://github.com/rust-lang/team/pull/1524, so I think somebody else needs to approve them before this can merge.

Update branch protections for `cmake-rs` and `libm`

---

repos/rust-lang/rustc_codegen_c.toml
teams/codegen-c-maintainers.toml

One of the OSPP projects this year is a C codegen backend. Create a repository where this will be developed, modeled off the codegen_cranelift repo file.
r? @Kobzol since I think you are in the loop with this

Create a `rustc_codegen_c` repository

---

repos/rust-lang/blog.rust-lang.org.toml

According to @Manishearth, the website team is supposed to be able to merge PRs in the blog repo.
Relevant discussion on Zulip:
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Who.20is.20in.20charge.20for.20the.20Rust.20blog.3F/near/465217012

Add website team as maintainer of the blog

---

teams/crates-io.toml

@JohnTitor quoting from our email thread last year:
> I think it's fine to remove me and I'm happy to become an alumni.
If you changed your mind, let me know, otherwise: welcome to the land of unlimited power without any responsibilities :D
btw the reason for doing this now is that we're often struggling lately to have enough FCP checkboxes ticked on crates.io RFCs, and the fewer inactive team members we have, the easier it becomes to reach the necessary numbers :)

crates-io: Alumnize JohnTitor

---

repos/rust-lang/rfcs.toml

RFCs already go through the FCP flow where (almost) all team members need to check their approval checkbox. Requiring an additional GitHub-based PR approval seems like an unnecessary burden to get the RFC merged once the FCP period has concluded.
This PR sets number of required GitHub-based approvals (back?) to zero, which AFAIU matches that value that had been used in the past for this repository.
Related:
- https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rfcs.20repo.20review.20requirement

repos/rfcs: Remove approvals requirement

---

src/data.rs

Rust has recently started warning about the missing lifetime here (via https://github.com/rust-lang/rust/pull/129207).
```
warning: elided lifetime has a name
--> src/data.rs:154:31
|
151 |     pub(crate) fn subteams_of<'a>(
|                               -- lifetime `'a` declared here
...
154 |     ) -> impl Iterator<Item = &Team> + 'a {
|                               ^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```

Fix elided-named-lifetimes

---

repos/rust-lang/blog.rust-lang.org.toml

Add missing `rustbot` bot to the [blog.rust-lang.org repo](https://github.com/rust-lang/blog.rust-lang.org) config. The repo already contains a [triagebot.toml](https://github.com/rust-lang/blog.rust-lang.org/blob/master/triagebot.toml) config (from 4 years ago, so it probably worked in the past).
This change is mainly motivated by https://github.com/rust-lang/triagebot/pull/1839, which I was expecting to work given the existing config.

Add missing rustbot to the blog repository

---

repos/rust-lang/chalk.toml

The [chalk](https://github.com/rust-lang/chalk/) repository used an automated process to cut releases, but Jack told me the branch protection added when initially putting chalk under `team/repos` prevents this from working (for example, as seen in https://github.com/rust-lang/chalk/issues/814). 
So this PR removes the branch protection to help with future releases, in particular for `rust-analyzer` to use.
Have a safe flight home @jackh726 <3.

remove branch protection for `chalk`repository

---

repos/rust-lang/relnotes.toml

This is a purely internal repo, which doesn't even deploy to any infrastructure. Drop review requirements for the time being.

Remove review requirement for relnotes tooling

---

teams/mods.toml

I assume this means we can start using `@T-mods` on Zulip and it will ping the current members of the mods team.
r? @rust-lang/mods

teams/mods: Add `T-mods` Zulip group

---

people/jcs090218.toml
teams/emacs.toml

as discussed in https://github.com/rust-lang/rust-mode/issues/557 the emacs rust-mode package was seeked additional maintainers, and jcs090218 has volunteered to help.

add jcs090218 to team emacs

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/_expected/v1/repos/some_repo.json

This PR adds a `pr-required = <true/false>` option to branch protections. There are some repositories that use branch protections, but that do not require a PR.
I also refactored the branch protection mode to make the data representation clearer/make it impossible to represent invalid states (such as PR not required, but a required approval count is set). This is a compatibility break for the v1 data format, but branch protections are only [read](https://github.com/search?type=code&auto_enroll=true&q=org%3Arust-lang+required_approvals) by `sync-team` anyway, so it shouldn't be a big deal.
An interesting thing is that it does not actually make sense to require any CI status checks if a PR is not required, because we do not enable anyone to bypass the branch protections. Because if you set …

Add the option to not require a PR for protected branches

---

repos/rust-lang/crates.io-index.toml

Repo: https://github.com/rust-lang/crates.io-index
```toml
name = "crates.io-index"
description = "Registry index for crates.io"
bots = []
[access.teams]
crates-io = "write"
crates-io-on-call = "write"
jdno = "admin"
Xylakant = "write"
tshepang = "write"
MarcoIeni = "admin"
justahero = "write"
Turbo87 = "write"
Veykril = "write"
jtgeibel = "write"
mdtro = "write"
LawnGnome = "write"
eth3lbert = "write"
listochkin = "write"
Rustin170506 = "write"
carols10cents = "write"
```

Add crates.io-index repository under automation

---

repos/rust-lang/crates.io.toml

Related:
- https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/transferring.20issues.20not.20possible
- https://github.com/rust-lang/crates.io/pull/9557
r? @rust-lang/infra

crates.io: Enable `rustbot`

---

repos/rust-lang/llvm-project.toml

This essentially reverts rust-lang/team#1346, now that we have the ability to specify that PRs are not required for protected branches.

Restore branch protections for `llvm-project`

---

teams/leadership-council.toml

The lang team has chosen @traviscross and the moderation team has chosen @oli-obk for the September 2024 elections.
https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/council.20selection.202024
https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/September.202024.20Council.20Selections/near/473020980

Add TC and oli to the leadership council

---

teams/rustdoc-frontend.toml

Rustdoc frontend was created so that rustdoc people who didn't work on the HTML output didn't need to block FCP's to that. However, they're still pinged when @rust-lang/rustdoc-frontend is pinged, because their still part of the github team.
CC @rust-lang/rustdoc, if you want pings for @rust-lang/rustdoc-frontend after this, you should add yourself (or speak up here if you think this is a bad idea).
[zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/We.E2.80.99re.20all.20on.20T-rustdoc-frontend.3F.3F)

Don't include rustdoc members in rustdoc-frontend

---

repos/rust-lang/infra-smoke-tests.toml

The infra-smoke-tests[^1] repository is an internal tool by the infra-team to implement smoke tests for its cloud-based infrastructure.
[^1]: https://github.com/rust-lang/infra-smoke-tests

Add infra-smoke-tests repository

---

repos/rust-lang/rustdoc-types.toml

Part of implementing RFC [3505](https://rust-lang.github.io/rfcs/3673-rustdoc-types-maintainers.html)
CC @rust-lang/rustdoc

Add rustdoc-types repo under automation

---

people/hoodmane.toml
people/juntyr.toml
teams/emscripten.toml
teams/wasi.toml
teams/wasm.toml

The MCP for creating WASM, WASI, and Emscripten [notification groups](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) (https://github.com/rust-lang/compiler-team/issues/794) was accepted. This PR creates the notification group with the initial group members.
(note to self: this is part two of the steps in https://forge.rust-lang.org/compiler/notification-groups.html#notification-groups)
@alexcrichton Are you alright with being an initial member in the WASM and WASI groups?
@hoodmane Do you want to be part of the Emscripten group? If so, what details should I add for you?
cc @jieyouxu

Add wasm | wasi | emscripten notification groups

---

repos/rust-lang/hashbrown.toml

This should be accompanied by configuring a merge queue for `hashbrown`. Accompanying PR: https://github.com/rust-lang/hashbrown/pull/575.

Remove bors from `hashbrown`

---

repos/rust-lang/chalk.toml

It shouldn't really be needed on this repo.
Accompanying PR: https://github.com/rust-lang/chalk/pull/818
`wg-traits` also had bors merge rights for chalk, but that WG has been archived, so I don't think that we need to deal with it further.

Remove bors from chalk

---

repos/rust-lang/miri.toml

Accompanying PR: https://github.com/rust-lang/miri/pull/3981

Remove bors from miri

---

people/BurntSushi.toml
people/Diggsey.toml
people/JohnTitor.toml
people/Manishearth.toml
people/Xanewok.toml
people/alexheretic.toml
people/gnzlbg.toml
people/ibabushkin.toml
people/japaric.toml
people/matklad.toml
people/nrc.toml
teams/archive/wg-traits.toml
teams/compiler.toml
teams/crate-maintainers.toml
teams/libs-api.toml
teams/libs.toml
teams/miri.toml
teams/types.toml

This PR removes bors review/try permissions for repositories that are no longer managed by bors.

Remove legacy bors permissions

---

repos/rust-lang/rust-clippy.toml
teams/clippy.toml

Accompanying PR: https://github.com/rust-lang/rust-clippy/pull/13587

Switch clippy from bors to merge-queue

---

repos/rust-lang/rust-clippy.toml
teams/clippy.toml

Reverts rust-lang/team#1589
We need to first configure the repo.

Revert "Switch clippy from bors to merge-queue"

---

repos/rust-lang/calendar.toml

The calendar repository is used to maintain the calendar events for various teams.
For some teams, it's important that the friction for adding or updating calendar events be low, as otherwise team members start looking for or using alternate calendaring solutions.  Keeping this friction as low as possible is probably more important, in this case, than the benefits that we're getting from requiring PRs as part of the branch protection.  So let's remove that requirement.
The other option here would be to instead add `required-approvals = 0` to the branch protection.  This would require creating PRs but would avoid the need for a separate reviewer.
This is an option, but it would still increase the friction a bit, and it therefore seems net-better to just remove the need to create PRs.  Many …

Remove requirement to create PRs from calendar repo

---

teams/clippy-contributors.toml
teams/clippy.toml

This moves @giraffate and @m-rph to their respective Clippy alumni teams.
---
I believe, I speak for the team, when I say:
Thank you for the work you've done! If you ever want to come back, just reach out, we'd be happy to have you!
---
r? @flip1995 || @Manishearth

Graduate @giraffate and @m-rph to Clippy/Contributor alumni

---

repos/rust-lang/crater.toml
teams/infra.toml

Accompanying PR: https://github.com/rust-lang/crater/pull/746

Switch crater from bors to merge-queue

---

repos/rust-lang/rustc-dev-guide.toml

When a subject matter expert writes some docs, there's no point in blocking them. They should just merge their stuff, we can always fix it later. If someone does want a review for their PR, they can always get it still.
discussed this with @BoxyUwU and @jieyouxu, @rust-lang/wg-rustc-dev-guide

Set dev guide approvals to 0

---

repos/rust-lang/edition-guide.toml

In https://github.com/rust-lang/edition-guide/pull/333 we are switching to merge queue, which includes a "consolidation" job.

Update edition-guide branch protection

---

repos/rust-lang/rust-clippy.toml
teams/clippy.toml

Accompanying PR: https://github.com/rust-lang/rust-clippy/pull/13587
I forgot to mark https://github.com/rust-lang/team/pull/1589 as a draft, so it was accidentally merged (and later reverted in https://github.com/rust-lang/team/pull/1591). This should not be merged until we configure the clippy repo properly.

Switch clippy from bors to merge queue

---

people/Mark-Simulacrum.toml
people/steveklabnik.toml
repos/rust-lang/cargo.toml
teams/cargo.toml

Accompanying PR: https://github.com/rust-lang/cargo/pull/14718
**Merge should be synchronized with an infra-admin switching the repo to merge queues!**

Switch cargo from bors to merge-queue

---

teams/compiler.toml

It is preferred that the membership of this Zulip ping group be managed in an ad-hoc way, some members do not attend, and some members prefer not to be pinged so they get notified about subsequent direct pings, etc.

update membership for t-compiler/meeting

---

teams/fuchsia.toml

This is so they can update the Fuchsia pin (e.g. https://github.com/rust-lang/rust/pull/132294, which is only practical because of my status as compiler team member). For the same reason this was done for the Rust for Linux team in #1512.
cc @erickt @P1n3appl3

Give try permissions to Fuchsia team

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/_expected/v1/repos/some_repo.json

Instead of just assuming that when bors (homu) is enabled for a repository, all its branches will be automatically managed by it, this PR adds an opt-in mechanism to use bors/homu for specific branch protections.

Add `merge-bots` configuration per branch protection

---

repos/rust-lang/cc-rs.toml

@madsmtm  has been contributing to cc-rs for a while and is knowledgeable about compilation on macOS and rust compiler internals.
@madsmtm  has consented to become a maintainer of cc-rs, as the maintainer of cc-rs I believe Mads is capable of and well-fit to become maintainer of cc-rs

Add madsmtm as maintainer of cc-rs

---

teams/project-const-generics.toml

Already spoke with lcnr and they agree'd with adding errs to the group :3 
@compiler-errors  has done a lot of work implementing and reviewing const generic PRs, and has also been invaluable to consult with about various decisions and parts of the compiler when working on const generics stuff :3

Add compiler-errors to project-const-generics

---

teams/foundation-board-project-directors.toml
teams/project-directors.toml

So that:
- Project Directors can post to Inside Rust as "on behalf of the Project Directors team"
- We can have an email address for people to contact all of us
- ~~We can be listed on rust-lang.org~~ I don't think this is true now that I've changed the team to be type marker-team
I've probably forgotten something that should be set in the toml or that needs to be done when adding a new team. Please let me know and I'm happy to fix! ❤️

Define a team for Project Directors on the Foundation board

---

repos/rust-lang/rustc-dev-guide.toml

T-bootstrap maintains the build system, it makes no sense why bootstrap doesn't have write acccess (unless this is covered by T-infra...?)
cc @spastorino and @onur-ozkan
I guess also cc @rust-lang/bootstrap for FYI.

Allow T-bootstrap to have write access to rustc-dev-guide repo

---

repos/rust-lang/crater.toml

This restores the previous state pre-merge-queues, where most PRs were self-approved via bors.

Drop required approvals for Crater

---

repos/rust-lang/compiler-team.toml

Add `rfcbot` to the list of bots to the compiler-team reposiroty so that the bot can edit labels.
cf. https://www.github.com/rust-lang/compiler-team/issues/785#issuecomment-2544090585

Add `rfcbot` to compiler-team repo

---

teams/lang-advisors.toml

In recognition of @Nadrieril's ongoing contributions to the lang team we've invited him to join lang-advisors. Welcome, Nadrieril!
cc @rust-lang/lang @rust-lang/lang-advisors @nikomatsakis

Add Nadrieril to lang-advisors

---

repos/rust-lang/crates.io-index-archive.toml

Repo: https://github.com/rust-lang/crates.io-index-archive
I modeled the PR after https://github.com/rust-lang/team/pull/1306.
Not sure if the admin access is needed, but probably doesn't hurt in this backup repo
CC @Turbo87
```
name = "crates.io-index-archive"
description = "Archive of the crates.io-index commit history after squashes"
bots = []
[access.teams]
crates-io = "admin"
MarcoIeni = "admin"
jtgeibel = "admin"
jdno = "admin"
mdtro = "admin"
Turbo87 = "admin"
Rustin170506 = "admin"
eth3lbert = "admin"
LawnGnome = "admin"
pattern = "snapshot-*" …
```

Add crates.io-index-archive repository under automation

---

repos/rust-lang/staging.crates.io-index.toml

Repo: https://github.com/rust-lang/staging.crates.io-index
Modeled after https://github.com/rust-lang/team/pull/1306.
CC @Turbo87
```
name = "staging.crates.io-index"
description = "Registry index for staging.crates.io"
bots = []
[access.teams]
crates-io = "write"
crates-io-on-call = "write"
jdno = "admin"
tshepang = "write"
carols10cents = "write"
Xylakant = "write"
LawnGnome = "write"
eth3lbert = "write"
listochkin = "write"
Rustin170506 = "write"
jtgeibel = "write"
Turbo87 = "write"
mdtro = "write"
MarcoIeni = "admin"
justahero = "write"
Veykril = "write" …
```

Add staging.crates.io-index repository under automation

---

repos/rust-lang/www.rust-lang.org.toml

Repo: https://github.com/rust-lang/www.rust-lang.org
CC @dtolnay @Manishearth
```
name = "www.rust-lang.org"
description = "The home of the Rust website"
bots = []
[access.teams]
website = "write"
MarcoIeni = "admin"
senekor = "write"
rust-pontoon-trial = "write"
Manishearth = "write"
jdno = "admin"
pattern = "deploy"
restrict-pushes = true
allowed-merge-teams = ["website"]
pattern = "try"
```

Add www.rust-lang.org repository under automation

---

teams/relnotes-interest-group.toml

Tracking issue: https://github.com/rust-lang/rust/issues/133334
This ping group is intended for contributors who would like to get pinged on release notes PRs (PR modifying `RELEASES.md` and the release blog post), intended to help double-check release notes. As @BoxyUwU [said](https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/Please.20CC.20lang/near/483592257):
> If we're going to do this I'd probably prefer having new ping group or something rather than pinging lang directly. This isn't really lang teams area so it's mostly just a "here are some people interested in knowing the release is happening" ping at which point why not do something that other people can use if they want to take an early look at the release posts
For more context, see …

Create `relnotes-interest-group` ping group

---

repos/rust-lang/glob.toml

CI now has a `success` job that we can protect on, which should make auto-merge possible.

Add branch protection to `glob`

---

repos/rust-lang/rustc-dev-guide.toml

Needed because of the force-push of rustc-dev-guide (https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Force-pushing.20to.20rustc-dev-guide).

Add branch protection for the `master-old` branch in `rustc-dev-guide`

---

repos/rust-lang/git2-rs.toml

I would like to enable this bot on the git2 repo.

Enable rustbot on the git2 repo

---

config.toml
teams/infra.toml

So that `sync-team` is not required to access it. It should be unused anyway.

Remove mentions of the bors-rs organization

---

repos/rust-lang/rustc_codegen_gcc.toml

As discussed on [zulip](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Enable.20auto-merge.20PR.20for.20rustc_codegen_gcc). Hopefully this should be enough. :)
cc @tgross35

Enable auto-merge feature on rustc_codegen_gcc repository

---

teams/wg-async.toml

We're working to move things out from under the launching-pad team to more appropriate places.  It makes the most sense for the async working group to be adopted as a subteam of lang, so let's do that.
Note that there are ongoing discussions of how we on lang might want to further refactor this working group.  This PR doesn't seek to resolve those.  It just puts the working group in our domain.  We can later adjust as we deem proper.
See:
- https://github.com/rust-lang/leadership-council/issues/137
cc @nikomatsakis @tmandry @eholk @yoshuawuyts @compiler-errors @jamesmunns

Adopt wg-async as a subteam (WG) of lang

---

teams/book.toml

We're working to move things out from under the launching-pad team to more appropriate places.  It makes the most sense for the book team to be adopted as a subteam of lang-docs, so let's do that.
See:
- https://github.com/rust-lang/leadership-council/issues/123
cc @ehuss @chriskrycho @carols10cents @jamesmunns

Adopt the book team as a subteam of lang-docs

---

repos/rust-lang/rust-by-example.toml
teams/rust-by-example.toml

We're working to move things out from under the launching-pad team to more appropriate places.  It makes the most sense for the rust-by-example working group to be adopted as a subteam of lang-docs, so let's do that.
Note that, in doing this, we'll make it a proper subteam rather than a working group.
See:
- https://github.com/rust-lang/leadership-council/issues/139
cc @ehuss @marioidival @jamesmunns

Adopt rust-by-example as a subteam of lang-docs

---

teams/types-fcp.toml
teams/types.toml

As discussed in today's T-types meeting. This mirrors the structure the compiler team uses.

Add types-fcp team and remove exclusion list from types team

---

repos/rust-lang/rustc_codegen_gcc.toml

The job name should be `build` and not `success`.

Use the build job name instead of success in ci-checks for rustc_codegen_gcc

---

config.toml
teams/crates-io.toml

The https://github.com/conduit-rust project has been deprecated.
We are removing the org from this repository to simplify some automations in sync-team.
For more details, see the [thread](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/sync-team.20dry.20run.20workflow/near/497647101) in zulip.

Remove `conduit-rust` org from this repository

---

teams/launching-pad.toml

This adds a dedicated website page for the launching pad. See https://github.com/rust-lang/www.rust-lang.org/pull/2105 for more information.

Add a website page for the launching pad

---

teams/triagebot.toml

@apiraino has been making a lot of improvements to triagebot lately (not to mention that he is kind of a human form of a triagebot himself). I would like to help with reviewing his work, and also to improve triagebot mostly in the area of tests (https://github.com/rust-lang/triagebot/pull/1892).

Extend the triagebot team

---

repos/archive/rust-lang/core-team.toml
teams/archive/core.toml

This archives the core team and the core-team repo.
I am not aware of any infrastructure still depending on this. If there is, it would be good to know so it can be resolved.
None of the mailing list aliases look like they are particularly important to keep around. I do not see `legal@crates.io` used anywere, and I assume Mark and Ryan have not been getting any significant email as of recently. If anyone really cares, I'm fine with moving them to council instead.

Archive the core team

---

people/dakr.toml
teams/rust-for-linux.toml

Danilo has recently joined the Rust for Linux core team, thus add him to the ping group.
Cc: @dakr

Rust for Linux: add Danilo

---

people/wedsonaf.toml
teams/rust-for-linux.toml

Wedson does not work on Rust for Linux anymore, thus remove him from the ping group.
Cc: @wedsonaf

Rust for Linux: remove Wedson

---

people/hkBst.toml
teams/cloud-compute.toml

Eagerly adding @hkBst so once they need it they have access instead of needing to wait through another team PR cycle. This was discussed in the compiler team and had a few approvals and no disagreements. For context see https://github.com/rust-lang/rust/pull/136931#issuecomment-2658498224
The others are either already team members (@WaffleLapkin), or are not contributing anymore

Remove unused cloud compute entries and add hkBst

---

teams/gsoc-contributors.toml

Contributors may potentially work on performance, or on other things
that benefit from try access. We trust gsoc-contributors to not abuse
this access.

Grant try and perf access to gsoc-contributors

---

teams/rustfmt.toml

These review permissions will only be used for rustfmt subtree syncs and the occasional in-tree rustfmt PR.

Add review permissions for rustfmt team members

---

repos/rust-lang/chalk.toml

This is the easiest way to allow the auto releases.

Remove chalk branch protection

---

teams/hiring.toml

Sometimes we need to give people a place to email us about open positions.  Let's create a marker team for this.  The members of the marker team will be those people currently interested in seeing the resumes coming in the door.
This is related to:
- https://github.com/rust-lang/leadership-council/issues/161
- https://github.com/rust-lang/leadership-council/issues/151

Add email alias for hiring

---

.github/workflows/dry-run.yml
.github/workflows/main.yml

This PR adds a dry run CI workflow that runs after every push to a PR. On a PR push, a GitHub artifact with its rendered JSON API is uploaded. When the PR workflow finishes successfully, the dry run workflow will run on `main` (in a privileged context). It downloads `sync-team`, downloads the built JSON API from the PR, passes it to `sync-team` and gathers its dry run output.
It then hides all previous bot comments on that PR and posts a new [comment](https://github.com/Kobzol/team/pull/1#issuecomment-2668621163) that prints the output of the dry run.
Using this workflow, we should be able to quickly and easily observe what changes would happen after a given team PR is merged.
Blocked on
(Very painfully) debugged at https://github.com/Kobzol/team/pull/1#issuecomment-2668621163.

Add dry run workflow for testing the applied changes

---

.github/workflows/dry-run.yml
.github/workflows/main.yml

GitHub strikes again.. We need to get the PR number into the dry-run workflow somehow. This seemed like the simplest possibility (https://github.com/orgs/community/discussions/25220).

Fix dry run workflow for PR from forks

---

.github/workflows/dry-run.yml

sync-team outputs everything through logs to stderr.

Redirect stderr to file in dry-run workflow

---

.github/workflows/dry-run.yml

So that we can debug [errors](https://github.com/rust-lang/team/actions/runs/13705594955/job/38329976933).

Also print sync-team output to CI logs

---

repos/rust-lang/sync-team.toml

We're encountering a weird situation in sync-team:
1) sync-team thinks that the allowed push actors of `sync-team` is empty
2) Therefore, it tries to set it to `infra-admins`, according to the configuration set in the [team](https://github.com/rust-lang/team/blob/master/repos/rust-lang/sync-team.toml#L12) repo. This succeeds.
3) However, on the next sync it still thinks it is empty. And in the GitHub UI, there is not an `infra-admins` team set in the allowed push actors, but it contains "organization admins".
I'm not sure if sync-team is somehow configured specially for this (?). Maybe @Mark-Simulacrum or @pietroalbini will know.
This PR tries to explicitly add infra-admins as a team with admin permissions for the sync-team repo, to test if it will fix this issue.

Add infra-admins explicitly to sync-team

---

docs/toml-schema.md
src/validate.rs

It seems that teams mentioned in this array have to also have explicit access to the repository, otherwise configuration of the allowed merge teams will not work in `sync-team`.

Add validation for `allowed-merge-teams`

---

teams/docs-rs-reviewers.toml
teams/docs-rs.toml

This is a sad news but they didn't contribute in a long time, so I think it's time for us to let them go.
Thanks a lot for your contributions!
Please note though that if you ever want to contribute again on docs.rs, you're more than welcome and if it happens, you'll be fast-tracked back on the team. :)
cc @syphar @Nemo157 @Byron

Move Nemo157 and Byron into docs.rs alumnis

---

teams/social-media.toml

This moves the social-media team underneath the launching pad. This is done for a few reasons:
* Stay consistent with other communication and cross-team teams like website, twir, and edition.
* Remove the only direct subteam of the council.
* Prepare for (possibly) adding teams to the website governance.
cc @rust-lang/leadership-council

Move social-media to launching-pad

---

docs/toml-schema.md
rust_team_data/src/v1.rs
src/data.rs
src/schema.rs
src/static_api.rs
src/validate.rs
teams/compiler.toml
tests/static-api/_expected/v1/zulip-streams.json
tests/static-api/teams/foo.toml

See rust-lang/sync-team#92 for the other half of this.
t-compiler want to use our private Zulip stream for some communications but we've held off on doing this as the membership of that stream is manually managed, that is inconvenient and we sometimes forget. In testing this patch, I found the stream membership was still out-of-sync!
I've tested this locally with the sync-team changes locally and absent the untested parts noted in that PR's description, it all works.
I've deliberately avoided adding an exhaustive schema for the streams, just their name as that's all that is necessary to adjust the membership, and that's all that the compiler team needs.
There's a reasonable amount of duplication with the types and functions for Zulip user groups, but we'll likely extend these types to …

sync zulip stream membership

---

teams/mentors.toml
teams/mentorship.toml

To facilitate getting out a blog post, we added the mentorship team (previously chartered under the name "internship team") under the name "mentorship-programs".  Let's now make some edits to set this up more "properly" (in my view, of course).
First, let's rename it to just "mentorship".  Probably I understand the hesitancy to claim such a broad mandate by calling it that rather than "mentorship-programs", but it just seems unlikely to me that we'd ever have both a "mentorship-programs" team and a "mentorship" team, so we should just use the shorter name.  (My guess is that if we ever wanted some other kind of mentorship, it's more likely that this team would expand its mandate than that we'd add a second team.)  If that really makes us uncomfortable, then probably I'd suggest going back …

Set up mentorship team "properly"

---

.github/CODEOWNERS
.github/workflows/main.yml
src/ci.rs
src/main.rs

This PR contains the first step towards merging the `team` and `sync-team` repositories. It adds a `.github/CODEOWNERS` file that checks that changes to secure files and directories have to be approved by the `infra-admins` team.
Instead of hardcoding the contents of the file, I created a command that generates the file dynamically, and another command that checks that the file is up-to-date. The contents are generated based on the contents of `infra-admins.toml`. Currently, the `CODEOWNERS` file expands the names of infra-admins, an alternative is to use the `@rust-lang/infra-admins` team instead. I'm not sure which approach is more secure/better.
This PR doesn't really change the behavior of this repo in any way. As a follow-up, we should modify the branch protection of this repository …

Add CODEOWNERS

---

docs/threat-model.md

Wrote down a basic threat model for this repository. Note that it describes how it would look like after we merge `team` and `sync-team`, not the current state.
I also updated CODEOWNERS to add additional files that could affect the build.

Add basic threat model

---

teams/leadership-council.toml

I am leaving the Leadership Council and @cuviper is taking my place as the Compiler Team representative. This PR makes that official in the team repo.

Rotate eholk out of Leadership Council and rotate cuviper in

---

teams/wg-compiler-performance.toml

@Zoxc has been doing a lot of great work on compiler performance recently. And this will also help them continue to do that more easily with access to `try`, the perfbot, and the >= 32 cores dev desktop machines.

add zoxc to wg-compiler-performance

---

.github/workflows/dry-run.yml
sync-team/Cargo.toml

First incremental step towards merging the code.

Use local `sync-team` code for performing dry runs

---

teams/docker.toml

This enacts the consensus I think we reached in https://github.com/rust-lang/leadership-council/issues/124. It moves the docker team to infra, and makes @Muscraft the lead.
cc @rust-lang/infra @rust-lang/docker @rust-lang/leadership-council 
Closes https://github.com/rust-lang/leadership-council/issues/124

Move docker team to infra

---

repos/rust-lang/rustc-dev-guide.toml

There's quite a bit of rustdoc docs that also live inside rustc-dev-guide, and T-rustdoc{,-frontend} maintainers really ought to be able to make changes / approve changes to them.
cc @rust-lang/rustdoc
r? @JohnTitor @spastorino

Make T-rustdoc{,-frontend} members have write access to rustc-dev-guide

---

.github/workflows/main.yml

Rather than using the bespoke script, which shouldn't be needed anymore. If this works, the `GITHUB_DEPLOY_KEY` secret can be removed from this repository.
I wanted to land this separately from https://github.com/rust-lang/team/pull/1715 to make sure that it works and to avoid too many changes in that PR. If this deployment works here, it should also work in the merge queue, without us having to reconfigure any terraform settings.

Upload GitHub Pages using the standard action

---

.github/workflows/main.yml

Once we start deploying sync-team from this repo, we really should be using merge queues (ideally configured in a way where they never test more than one PR at the same time). This PR switches to merge queues, and also starts preparing some CI hardening that will be required for the GitHub deploys.

Switch to merge queues

---

repos/rust-lang/enzyme.toml

Currently our submodule for Enzyme in `rust-lang/rust` points to an external repository outside of our organization.  As we do for LLVM, it would be useful for us to maintain a Rust-specific soft fork of Enzyme within `rust-lang/`.  Let's create a repository for this.
In particular, this would unblock some work being held up by CI issues on the upstream project, and it'd allow us to make some changes that might better facilitate upstreaming of this work into LLVM.
Probably we should also create a `wg-enzyme` or whatnot team that could maintain this.  Alternatively or in addition, we could formalize `wg-autodiff`, for which we have a Zulip stream but no entry here. But let's handle that separately.  For the moment, we just give access to the normal teams that would be likely to need to …

Add repo for Rust-specific soft fork of Enzyme

---

docs/toml-schema.md
src/validate.rs
teams/book.toml
teams/codegen-c-maintainers.toml
teams/community.toml
teams/compiler-fcp.toml
teams/docker.toml
teams/docs-rs-reviewers.toml
teams/infra-bors.toml
teams/mentors.toml
teams/project-const-traits.toml
teams/release-publishers.toml
teams/rustlings.toml
teams/social-media.toml
teams/twir-reviewers.toml
teams/twir.toml
teams/types-fcp.toml
teams/web-presence.toml
teams/website.toml
tests/static-api/_expected/v1/teams.json
tests/static-api/_expected/v1/teams/leaderless.json
tests/static-api/_expected/v1/teams/leadership-council.json
tests/static-api/_expected/v1/teams/leads-permissions.json
tests/static-api/_expected/v1/teams/wg-test.json
tests/static-api/teams/leaderless.toml
tests/static-api/teams/leadership-council.toml
tests/static-api/teams/leads-permissions.toml
tests/static-api/teams/wg-test.toml

This updates all teams that do not have website entries to add them.
This also requires that new teams to be included on the website.
The intention here is to help make sure information about Rust's governance is available and publicly transparent.
cc @rust-lang/leadership-council This affects almost all of you via subteams you represent.

Add all teams to the website

---

.github/workflows/main.yml
sync-team/Cargo.lock

This prepares the move from AWS to GitHub for performing the actual sync.

Run sync-team in merge queue

---

sync-team/src/github/api/mod.rs
sync-team/src/github/api/read.rs
sync-team/src/github/tests/mod.rs
sync-team/src/github/tests/test_utils.rs
sync-team/src/utils.rs

Backports https://github.com/rust-lang/sync-team/pull/131 and https://github.com/rust-lang/sync-team/pull/132 from the sync-team repo.

Backport sync team changes

---

people/apasel422.toml
people/arielb1.toml
people/bluss.toml
people/fitzgen.toml
people/japaric.toml
people/ljedrz.toml
people/nox.toml
people/sanxiyn.toml
people/tromey.toml

We should not grant bors permissions to individuals anymore. It seems that everyone from the list is not active in reviewing anymore, and most of them are no longer active in contributing either.
- apasel422 - Last PR [2018](https://github.com/rust-lang/rust/pulls?q=is%3Apr+apasel422+is%3Aclosed)
- arielb1 - Last PR [2022](https://github.com/rust-lang/rust/pulls?q=is%3Apr+arielb1+is%3Aclosed+)
- bluss - Last PR [2020](https://github.com/rust-lang/rust/pulls?q=is%3Apr+author%3Abluss+is%3Aclosed+)
- fitzgen - Last PR [2024](https://github.com/rust-lang/rust/pulls?q=is%3Apr+author%3Afitzgen+is%3Aclosed+), most 2019 and older
- japaic - Last assigned PR [2020](https://github.com/rust-lang/rust/pulls?q=is%3Apr+assignee%3Ajaparic+is%3Aclosed+)
- ljedrz - Last PR …

Remove individual bors permissions

---

repos/rust-lang/crates.io-index-archive.toml
repos/rust-lang/sync-team.toml
repos/rust-lang/www.rust-lang.org.toml
src/validate.rs
tests/static-api/_expected/v1/repos.json
tests/static-api/_expected/v1/repos/archived_repo.json
tests/static-api/_expected/v1/repos/some_repo.json
tests/static-api/repos/archive/test-org/archived_repo.toml
tests/static-api/repos/test-org/some_repo.toml

This PR removes all remaining `admin` permissions and adds a validation check that they are not used anywhere. I didn't remove them fully from the codebase yet, as I'd like to first see for some time if there is really no use-case for it.
In the future, we could in theory allow admin permissions, but require admin approval for PRs that assign them.

Forbid admin permissions

---

repos/rust-lang/aws-runners-test.toml

Repository: https://github.com/rust-lang/aws-runners-test
```toml
name = "aws-runners-test"
bots = []
[access.teams]
infra-admins = "admin"
jdno = "admin"
```

Add aws-runners-test repository under automation

---

.github/workflows/dry-run.yml

The name of the binary is `rust-team`, not `team` :facepalm:

Fix name of binary in dry-run CI workflow

---

.github/CODEOWNERS
README.md
src/ci.rs

I wonder if we should allow `*.md` in `CODEOWNERS` to not require infra admin approval for Markdown changes :)
Allowed that in this PR.

Fix sync-team link in README

---

.github/workflows/dry-run.yml

This should make it easier to test code changes using the dry-run functionality. Only `mods`, `team-repo-admins` and `infra-admins` have `write+` permissions, so only they are able to create branches on this repository.
Even if someone figured out a way to get through it, dry-run runs only with a read-only token, so the possible damage would be limited.

Run dry-run with code from PR if it is not from a fork

---

sync-team/src/github/api/mod.rs
sync-team/src/github/api/read.rs
sync-team/src/github/mod.rs
sync-team/src/github/tests/test_utils.rs

Dry-run for the rust-lang/rust repo currently [fails](https://github.com/rust-lang/team/pull/1463), because the read-only GitHub App tokens used for dry-runs cannot read branch protections of this repository, because they use GitHub App push allowances.
This PR adds a hacky workaround to ignore that error. The `uses_pat` function isn't super nice, but alternatives seemed worse:
- If we just ignored all errors returned from the `branch_protections` function for `rust-lang/rust` in the `diff_branch_protections` function, we could miss actual errors when a PAT is used. That would be bad.
- If we wanted to examine the specific error returned by `branch_protections` without asking if the API uses a PAT, we'd either need to examine its string contents, or create some new enum error variant only …

Work around missing permissions for rust-lang/rust branch protections

---

rust_team_data/src/v1.rs
src/schema.rs
src/static_api.rs
sync-team/src/github/mod.rs

The [dry-run](https://github.com/rust-lang/team/actions/runs/14170134329/job/39691899954) on https://github.com/rust-lang/team/pull/1463 showed that we will need to include these bots.
(It's so great to have the option to modify both team and sync-team in the same PR :heart:)

Add bots needed for rust-lang/rust

---

config.toml

These repos no longer use bors (neither the old one nor the new one). Homu no longer loads any other repo than `rust`, so removing the (empty) JSON bors permission files from the rendered output should hopefully be fine.

Remove unused bors repos from permission allowlist

---

.github/CODEOWNERS
repos/rust-lang/rust.toml
src/ci.rs

Repository: https://github.com/rust-lang/rust
```toml
name = "rust"
description = "Empowering everyone to build reliable and efficient software."
bots = []
[access.teams]
cargo = "write"
project-stable-mir = "write"
rustdoc = "write"
rustfmt = "pull"
rfcbot = "write"
opsem = "write"
clippy = "write"
style = "write"
wg-prioritization = "triage"
wg-triage = "write"
project-exploit-mitigations = "write"
mods = "write"
types = "write"
wg-rustc-dev-guide = "pull"
lang = "write"
libs = "write"
bootstrap = "write"
core = "admin"
lang-ops = "write"
bors = "write"
BurntSushi …
```

Add rust repository under automation

---

.github/workflows/main.yml
sync-team/src/github/mod.rs

To help observe the progress better when real synces are being performed. Currently, we are staring at an empty screen for ~3 minutes.

Add debug logging of team and repo diffs during actual sync

---

.github/workflows/dry-run.yml
.github/workflows/main.yml
Cargo.lock
Cargo.toml
README.md
src/main.rs
sync-team/src/team_api.rs

Before, `sync-team` performed sync against the live service. Now it runs against the local `team` checkout by default. This PR also makes it easier to run `sync-team` on the local checkout data (as that is probably a common use-case, if you use it locally), without having to prebuild the JSON data directory first.

Make it possible to run sync-team against local data

---

.github/workflows/main.yml

This reverts commit 4c2bdca7b86cf427e88370a034a53ea9de83eed7 (https://github.com/rust-lang/team/pull/1752), reversing changes made to 1388cc0ef318223dbafdd8f8122de0b729d9c581.
While the debug log is indeed nice for observing progress, it can also leak some information that might not be public (private Zulip stream membership), and it also drowns the actually performed changes. So I think it's not worth it after all.
I only reverted the CI change, because having the debug log of diffing teams/repos can still be useful for observing progress locally.

Revert "Merge pull request #1752 from Kobzol/debug-log"

---

people/baumanj.toml
people/ernestkissiedu.toml
people/timClicks.toml
repos/rust-lang/project-vision-doc.toml
teams/project-vision-doc-2025.toml

[Context](https://rust-lang.zulipchat.com/#narrow/channel/486265-vision-doc-2025/topic/vision.20doc.20plan/near/505781528); [this hackmd contains charter, expectations, and other info](https://hackmd.io/@rust-vision-doc/SyfqOGGhye).
cc @jackh726 
To author the Rust 2025 Vision RFC. See the [Project Goal](https://rust-lang.github.io/rust-project-goals/2025h1/rust-vision-doc.html) for more details.
Initial leads, charged with generally running the group and determining members and membership expectations.
* nikomatsakis
* jackh726
The expectation of a team member is that you will be an active participant in gathering and analyzing data. This means that you'll setup and drive at least 2 or 3 interviews and discussions during April -- can of course be way more! There are no pre-defined focus …

Project team for the Rust Vision Doc 2025 effort

---

repos/rust-lang/literal-escaper.toml

Needed for https://github.com/rust-lang/rust/pull/136355 which was reverted in https://github.com/rust-lang/rust/pull/138661 because the rustc-dev component needs it.
As discussed on [zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Sharing.20the.20literal-escaper.20crate/with/506941204), the best solution seems to be to make it published on crates.io.
r? @davidtwco

Add literal-escaper repository permissions

---

people/PartiallyUntyped.toml
repos/rust-lang/ci-mirrors.toml
teams/clippy-contributors.toml

The repo will host some tooling to automatically manage https://ci-mirrors.rust-lang.org

Create ci-mirrors repo

---

teams/style.toml

@traviscross has long been part of t-style meetings and discussions, both from a t-langops perspective helping to facilitate the meeting logistics, and as a full contributor discussing syntax and styling considerations.
You've been a functional member of the time for quite a while, time to make it formal as well. Welcome (officially) to the team!
cc @rust-lang/style

add TC to style team

---

teams/spec.toml

The spec team has, by unanimous agreement, invited Josh to join the team, and we're thrilled that he has accepted and will be picking up the mantle of helping to push forward our specification efforts.
cc @rust-lang/spec @rust-lang/lang

Add Josh to T-spec

---

repos/archive/rust-dev-tools/rls-analysis.toml
repos/archive/rust-dev-tools/rls-blacklist.toml
repos/archive/rust-dev-tools/rls-data.toml
repos/archive/rust-dev-tools/rls-rustc.toml
repos/archive/rust-dev-tools/rls-span.toml

- [rls-analysis](https://github.com/rust-dev-tools/rls-analysis)
```toml
org = "rust-dev-tools"
name = "rls-analysis"
description = "Core functionality for handling rustc's save-analysis data"
bots = []
[access.teams]
nrc = "admin"
Manishearth = "admin"
killercup = "admin"
Xanewok = "admin"
```
</details>
- [rls-blacklist](https://github.com/rust-dev-tools/rls-blacklist)
```toml
org = "rust-dev-tools"
name = "rls-blacklist"
description = "Blacklist of crates for the RLS to skip"
bots = []
[access.teams] …
```

Backport archived rust-dev-tools repos

---

repos/archive/rust-lang-deprecated/error-chain.toml
repos/archive/rust-lang-deprecated/failure.toml
repos/archive/rust-lang-deprecated/gyp.toml
repos/archive/rust-lang-deprecated/hexfloat.toml
repos/archive/rust-lang-deprecated/libuv.toml

- [error-chain](https://github.com/rust-lang-deprecated/error-chain)
```toml
org = "rust-lang-deprecated"
name = "error-chain"
description = "Error boilerplate for Rust"
bots = []
[access.teams]
jdno = "admin"
```
</details>
- [failure](https://github.com/rust-lang-deprecated/failure)
```toml
org = "rust-lang-deprecated"
name = "failure"
description = "Error management"
bots = []
[access.teams]
jdno = "admin"
``` …

Backport archived rust-lang-deprecated repos (batch 1)

---

repos/archive/rust-lang-deprecated/rust-buildbot.toml
repos/archive/rust-lang-deprecated/rust-packaging.toml
repos/archive/rust-lang-deprecated/rustc-benchmarks.toml
repos/archive/rust-lang-deprecated/rustc-serialize.toml
repos/archive/rust-lang-deprecated/rustup.sh.toml
repos/archive/rust-lang-deprecated/tempdir.toml
repos/archive/rust-lang-deprecated/url.toml

- [rust-buildbot](https://github.com/rust-lang-deprecated/rust-buildbot)
```toml
org = "rust-lang-deprecated"
name = "rust-buildbot"
description = "Buildbot configs for the Rust project"
bots = []
[access.teams]
jdno = "admin"
```
</details>
- [rust-packaging](https://github.com/rust-lang-deprecated/rust-packaging)
```toml
org = "rust-lang-deprecated"
name = "rust-packaging"
description = "Packaging for Rust + Cargo in multiple formats"
bots = …
```

Backport archived rust-lang-deprecated repos (batch 2)

---

repos/archive/rust-lang/libm.toml
repos/rust-lang/compiler-builtins.toml

Since https://github.com/rust-lang/compiler-builtins/pull/822, libm is now part of the compiler-builtins repository. Archive rust-lang/libm and update the description for compiler-builtins here.

Archive rust-lang/libm, update compiler-builtins

---

repos/rust-lang/reference.toml

cf. https://github.com/rust-lang/reference/pull/1792#issuecomment-2824692734 where the bot wasn't able to add the label because it doesn't have the rights to do so.

Add `rfcbot` to the bots used in the reference repo

---

repos/rust-lang/rustc_codegen_cranelift.toml
repos/rust-lang/rustc_codegen_gcc.toml

This is going to be useful for enabling [`[no-mentions]`](https://forge.rust-lang.org/triagebot/no-mentions.html) and [`[issue-links]`](https://forge.rust-lang.org/triagebot/issue-links.html) in both repository.
Which we should anyway to before enabling them in rust-lang/rust as otherwise subtree sync risk being flagged with warnings.
cc @bjorn3 @GuillaumeGomez @antoyo

Enable rustbot in `rustc_codegen_cranelift`&`rustc_codegen_gcc`

---

repos/rust-lang/libtest-next.toml

This was moved under rust-lang before T-testing-devex was aware of the crate ownership policy.
This is an experiment that we see being viable for long term support but we are unsure if we'd want to do that within the project or not. Considering the burden to Expatriate a package once published, we are moving the repo out of rust-lang so we can publish them and have the flexibility of having it maintained outside the project or later inside the project without having to abandon the name.
See
[zulip](https://rust-lang.zulipchat.com/#narrow/channel/404371-t-testing-devex/topic/crate.20ownership/near/513724212) for the discussion and decision.

Remove rust-lang/libtest-next

---

repos/rust-lang/fls.toml

Transferred the FLS repo from `ferrocene/specification` to `rust-lang/fls`. This will have the same permissions and access levels as the reference. cc @rust-lang/spec

Track the FLS repo

---

teams/foundation-board-project-directors.toml
teams/inside-rust-reviewers.toml

I think we can trust directors to post on the blog, so lets give them permissions to do that so they don't need to bug anyone else to do it.
To accommodate the addition of permissions, this promotes it from a marker team to a team in the launching pad (which we are planning to rebrand as a home for cross-cutting teams). There's no expectation that this would change anything in practice, and the membership is still chosen by the council.
cc @rust-lang/leadership-council @carols10cents @JakobDegen @rylev @scottmcm @spastorino

Move directors to launching pad, give them blog permissions

---

teams/compiler-ops.toml

With this first step I'd like to formalize the existence and work of a T-compiler operation group.
This group will prepare meetings agenda, do issue triaging and prioritization, scheduling and documenting meetings.
It will replace the current Prioritization Working Group inside T-compiler.
r? @davidtwco

Add T-compiler ops team

---

teams/cloud-compute.toml

Currently, I am getting the cloud dev desktop permission from the ``gsoc-contributors`` team. But since I will be moved to alumni eventually, @oli-obk recommended me to open a PR to add myself to the ``cloud-compute`` team. 
Reason of requesting for permission: currently working on an experimental feature in rustc ([draft pr here](https://github.com/rust-lang/rust/pull/140399/files)).
cc @Kobzol for gsoc related matter

Add myself to ``cloud-compute``

---

README.md
src/api/zulip.rs
src/main.rs
src/validate.rs

I had to add a bunch of users recently (new GSoC contributors), and it was quite painful to lookup their Zulip IDs manually. This PR adds a flag to the `add-person` command to automate this (if possible).

Allow automatically fetching Zulip ID for newly added users

---

teams/rustlings.toml

The (I assume temporary) description talks about a site, when in fact Rustlings is mostly something you download onto your computer (although we do have a website).

Update Rustlings team summary

---

repos/rust-lang/rust-log-analyzer.toml

Also added a required CI check while we're at it, but didn't require approvals.

Add branch protection to rust-log-analyzer

---

people/KMJ-007.toml
teams/gsoc-contributors.toml

We were asked by Manuel Drehwald to add Karan Janthe to our GSoC contributors team, so that they can access the dev desktops. They are working on a LLVM GSoC project which is related to Rust.
I created a pseudo `guest` role to mark this distinction.
CC @jackh726 @ZuseZ4

Add Karan Janthe to `gsoc-contributors`

---

people/cassaundra.toml
people/tautschnig.toml
teams/mentors.toml

I kept the mentors from GSoC 2024 (ytmimi and Jack), but we could also move them to Alumni, I don't think it matters that much.

Add GSoC 2025 mentors to the `mentors` team

---

teams/gsoc-contributors.toml

Since https://github.com/rust-lang/www.rust-lang.org/pull/2152, we show even marker teams with a `[website]` entry in the Governance section of the Rust website. This PR adds a website section for GSoC contributors, so that we can acknowledge their participation within the Project.
There's a small weirdness in that we now have the "external" LLVM contributor with the `guest` role, but I think that's fine. We could also rename the "guest" role to something like "LLVM GSoC contributor", so that the label displayed on the website makes a bit more sense.

Add website entry for GSoC contributors

---

teams/gsoc-contributors.toml

I realized that we need to do this in order for the contributors to actually appear on the website. It's a bit of a hack, but I guess that currently any team that doesn't have a parent is in fact a child of the launching pad anyway.

Add `gsoc-contributors` as a subteam of `launching-pad`

---

repos/rust-lang/gha-self-hosted.toml

As discussed at the All Hands, let's unarchive the gha-self-hosted repo, so that we can bring it to a working state again and do some benchmarks on it. We're not sure yet whether we actually want to start using it again though.

Unarchive gha-self-hosted

---

people/Darksonn.toml
teams/wg-triage.toml

This is so that I have the ability to modify tracking issues and add new links or tags to them. Using wg-triage for this was suggested to me by @jyn514.

Add Darksonn to wg-triage.toml

---

teams/docs-rs.toml

I hope podman is enough, 
this would make development much faster when testing the docs.rs build process, 
and also rustwide tests / changes.

add dev desktop access to docs.rs team members

---

teams/wg-rustc-dev-guide.toml

As discussed in https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Frustc-dev-guide/topic/Future.20of.20this.20wg/with/520076018 we are rotating leadership as first step.
We are evaluating what to do mid/long term with this working group.

Rotate dev guide leadership

---

Cargo.lock

See https://github.com/steffengy/schannel-rs/issues/106.
Resolves the issue I saw in https://github.com/rust-lang/team/pull/1838.

Bumps schannel to a version that isn't buggy.

---

repos/rust-lang/rust-forge.toml

Suggested by @ehuss in https://github.com/rust-lang/rust-forge/pull/852#issuecomment-2898439546.
Hopefully I correctly understood what they meant.
r? @ehuss

Add rustdoc team to rust-forge and triagebot maintenance

---

.github/workflows/dry-run.yml

[gh pr comment](https://cli.github.com/manual/gh_pr_comment) now takes `--create-if-none` option, so we can avoid this complicated dance.

Simplify comment implementation in dry-run

---

teams/wg-rustc-dev-guide.toml

i want to do a bunch of work around stability, the unstable-book, and forge. we don't really have a team for any of that, but rustc-dev-guide seems close enough.
can someone confirm that this will *not* give me r+ for rust-lang/rust? i don't want that access.

add jyn514 back to rustc-dev-guide

---

repos/archive/rust-dev-tools/gdb.toml
repos/rust-dev-tools/cargo-src.toml
repos/rust-dev-tools/dev-tools-team.toml

- [cargo-src](https://github.com/rust-dev-tools/cargo-src)
```toml
org = "rust-dev-tools"
name = "cargo-src"
description = "Semantic code navigation for Rust"
bots = []
[access.teams]
devtools = "maintain"
calebcartwright = "maintain"
Manishearth = "admin"
ehuss = "maintain"
GuillaumeGomez = "maintain"
killercup = "admin"
nrc = "admin"
rbtcollins = "maintain"
```
</details>
- [dev-tools-team](https://github.com/rust-dev-tools/dev-tools-team)
```toml
org = "rust-dev-tools"
name = "dev-tools-team"
description = "resources for the …
```

Backport rust-dev-tools repos (batch 1)

---

repos/rust-lang/a-mir-formality.toml

Remove homu from `a-mir-formality`

---

repos/archive/rust-lang-nursery/portability-wg.toml
repos/archive/rust-lang-nursery/rustc-seme-regions.toml
repos/archive/rust-lang-nursery/wg-verification.toml
repos/rust-lang-nursery/lazy-static.rs.toml

- [lazy-static.rs](https://github.com/rust-lang-nursery/lazy-static.rs)
```toml
org = "rust-lang-nursery"
name = "lazy-static.rs"
description = "A small macro for defining lazy evaluated static variables in Rust."
bots = []
[access.teams]
libs = "admin"
aidanhs = "admin"
sfackler = "admin"
huonw = "admin"
jdno = "admin"
Amanieu = "admin"
aturon = "admin"
joshtriplett = "admin"
thomcc = "admin"
dtolnay = "admin"
KodrAus = "admin"
nikomatsakis-admin = "admin"
steveklabnik = "admin"
nrc = "admin"
m-ou-se = "admin" …
```

Backport rust-lang-nursery repos (batch 2)

---

repos/archive/rust-lang-nursery/cli-wg.toml
repos/archive/rust-lang-nursery/futures-api-docs.toml

I noticed in the dry-run results of https://github.com/rust-lang/team/pull/1797 that two homepages were removed, I missed that. I think that my backporting scripts skipped some homepages. It didn't seem to happen in the other recently merged PRs, only here.

Add back two removed homepages

---

people/quad.toml
repos/rust-analyzer/expect-test.toml
teams/expect-test.toml

After https://github.com/rust-lang/team/pull/1805, @quad no longer access to maintain the `expect-test` repository. In [#t-compiler/rust-analyzer > Rust-analyzer org repository access and status @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/Rust-analyzer.20org.20repository.20access.20and.20status/near/521110084), we have discussed how to resolve this situation, and the outcome was to create a `expect-test` team that would be responsible only for this repository.
We can do this in two ways, I suppose:
- Create a marker team (which is what this PR does)
- Create the team as a subteam of `rust-analyzer` (?), and add a website entry for it
The second approach seemed a bit heavyweight for a tiny team designed to maintain a single small Rust …

Add `expect-test` team

---

repos/rust-lang/compiler-team-prioritization.toml
repos/rust-lang/compiler-team.toml
repos/rust-lang/rust.toml
teams/archive/wg-prioritization.toml

Announced on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/227806-t-compiler.2Fops/topic/Winding.20down.20WG-prioritization/near/519889258).

Archive WG-prioritization

---

people/Jamesbarford.toml
people/panstromek.toml
teams/wg-compiler-performance.toml

We would like to invite @panstromek and @jamesbarford to the compiler performance working area. I asked both privately and they agreed to join.
panstromek has been doing great work with the performance triage, and James is now working on the [multiple-machine benchmarking](https://rust-lang.github.io/rust-project-goals/2025h1/perf-improvements.html) Rust Project Goal, which should make the latency of getting perf. results much shorter, and enable us to benchmark more things (including ARM machines).
Welcome! :tada:
CC @rust-lang/wg-compiler-performance

Add panstromek and James Barford into the compiler performance working area

---

Cargo.lock
Cargo.toml
src/api/github.rs
sync-team/Cargo.toml

And remove unused `tempfile` dependency. This brings the dependency count down from 236 to 227.

Unify dependency versions between team and sync-team

---

people/BennoLossin.toml
teams/goal-owners.toml
teams/rust-for-linux.toml

A GitHub user just renamed themself, so I am updating our team repository to unblock further patches.
cc: FIY @bennolossin

Rename y86-dev to BennoLossin

---

repos/rust-lang/crates-io-auth-action.toml

[Trusted publishing](https://rust-lang.github.io/rfcs/3691-trusted-publishing-cratesio.html) is working on crates.io staging.
I worked on an [action](https://github.com/marcoieni/trusted-publishing-action-draft) to allow users to use trusted publishing on GitHub Actions.
In this PR, I create the repo for the action. After the repo has been created, I will push my code in that repo.
After the repo is created, I will edit this file again to add branch protections and maybe give infra team write access, but we need to make sure that only infra admins can push tags to that repo.
After my code is merged, I'm happy to receive PRs to change what you don't like about the action 👍
Regarding the license of the repo, is it enough to copy these files in the repo:
- …

add trusted publishing action repo

---

repos/rust-lang/josh-sync.toml

This repository will host Rust code and GitHub Actions workflows for synchronizing Josh subtrees from/into rust-lang/rust.

Add `josh-sync` repository

---

repos/archive/rust-lang/generate-manifest-list.toml

The tool and the GitHub Actions cron running on it is not needed anymore, as `manifests.txt` is now updated by the release process.

Archive `rust-lang/generate-manifest-list`

---

teams/lang-advisors.toml

By unanimous agreement, the lang team is pleased to recognize and welcome Eric Huss as a lang advisor.
---
One of the standards that we've used for deciding on lang advisors is to ask, "if the person were to flag something, how concerned should we be?"
Whenever @ehuss flags something for us, it always gets my attention, and he's, by my accounting, always correct it's something we should review, and fairly often, it's something of significance that we've all missed.
His work on the Reference makes him a key partner for us as we increasingly turn our lang attention toward carefully specifying our language.  He's the lead of the Cargo team, he's a valuable member of the Council, his support was invaluable in making Rust 2024 a success, and I've come to realize that, in a quiet way, he's a …

Add Eric Huss as a lang advisor

---

repos/rust-lang/josh-sync.toml

CC @marcoieni :innocent:
https://github.com/rust-lang/josh-sync/blob/main/.github/workflows/test.yml#L7

Require tests to pass on `josh-sync`

---

repos/rust-lang/crates_io_og_image.toml

We want to extract https://github.com/rust-lang/crates.io/tree/main/crates/crates_io_og_image into a dedicated repo so that it can be versioned and published independently for usage in docs.rs too.
r? @rust-lang/team-repo-admins @rust-lang/infra @rust-lang/crates-io @rust-lang/docs-rs

Add `crates_io_og_image` repository

---

src/validate.rs

Using `required-approvals = 0` should not prevent us from using `pr-required = false`.

validate: Fix `pr-required = false` validation for `required-approvals = 0`

---

repos/rust-lang/crates_io_og_image.toml

This allows us to push release commits directly to `main` without having to go through pull requests for no real reason.

crates_io_og_image: Remove PR requirement

---

people/folkertdev.toml
people/sayantn.toml
repos/rust-lang/stdarch.toml
teams/libs-contributors.toml

This also adds gives libs-contributors merge permissions for stdarch since it is essentially a part of the standard library.

Add sayantn and folkertdev as maintainers for stdarch

---

repos/rust-lang/rustc-perf.toml

The CI didn't block on compile benchmarks failing, which is annoying (https://github.com/rust-lang/rustc-perf/pull/2176).

Add more blocking CI checks to rustc-perf

---

repos/rust-lang/rustc-perf.toml

Yet again I did this [wrong](https://github.com/rust-lang/rustc-perf/pull/2202). I really wish it was possible to use a `*` asterisk here.. :laughing:

Fix rustc-perf CI checks

---

repos/rust-lang/rustdoc-types.toml

We want to have him to post reminders that most PR's to this repo should be filed to rust-lang/rust instead.
[Zulip Discussion](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/Triagebot.20for.20rust-lang.2Frustdoc-types/with/522207551)

Add triagebot to rust-lang/rustdoc-types.

---

.github/CODEOWNERS
teams/team-repo-admins.toml

As discussed in [#council > team repo review bandwidth](https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/team.20repo.20review.20bandwidth/with/530571296), I'd like to help with the team-repo-admins side's review bandwidth (at least with the more "obvious" changes under <https://forge.rust-lang.org/infra/team-maintenance.html> to hopefully make those changes take less time to be reviewed).
**This will need a FCP by Council (and/or existing `team-repo-admins`)?**
I ran `cargo run ci generate-codeowners` locally for `CODEOWNERS` change.
cc @ehuss (as you suggested [here](https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/team.20repo.20review.20bandwidth/near/530568050))
cc @rust-lang/team-repo-admins

Add `jieyouxu` to `team-repo-admins`

---

people/bennyvasquez.toml
teams/twir-reviewers.toml

Follow-up to #1932 which only removed members to instead move to alumni, as suggested in https://github.com/rust-lang/team/pull/1932#issuecomment-3166296450.

Recognize TWIR reviewers alumni

---

teams/project-const-generics.toml
teams/wg-mir-opt.toml

I'm not active in mir-opts or const generics and don't often have much to add to issues that these groups are pinged on, I can still be pinged individually when that's not the case, but this will cut down on my notification load.

remove davidtwco from some groups

---

teams/lang-docs.toml

This updates the lang-docs membership to better reflect the current state. TC has been helping with the organizational side of lang-docs, and helping across all of the projects.
I'd like to express a huge appreciation to Gankra, Havvy, and matthewjasper for their contributions, and they are always welcome to come back.
cc @rust-lang/lang-docs

Update lang-docs membership

---

people/LoriLorusso.toml
people/MerrimanInd.toml
people/cldershem.toml
repos/rust-lang/content-team.toml
repos/rust-lang/rust-forge.toml
teams/content.toml

The council chartered the Rust Content Team via an FCP that completed 2025-08-18.  Let's add the team.
- https://github.com/rust-lang/leadership-council/issues/206
cc @PLeVasseur @tomassedovic @MerrimanInd @cldershem @LoriLorusso

Add content team

---

repos/rust-lang/surveys-private.toml
repos/rust-lang/surveys.toml
teams/community.toml
teams/survey.toml

And make launching-pad its parent.
As per https://github.com/rust-lang/leadership-council/issues/133.

Rename community survey team to survey team

---

teams/archive/community-ctcft.toml
teams/archive/core.toml
teams/archive/ecosystem.toml
teams/archive/interim-leadership-chat.toml

Companion to https://github.com/rust-lang/www.rust-lang.org/pull/2202, to provide a proper name and description to a few archived teams.

Add a few website descriptions to archived teams

---

teams/rustc-dev-guide.toml

@Noratrieb regularly reviews PRs, so adding to the team as recognition of that fact
cc @BoxyUwU

rustc-dev-guide: make Noratrieb member

---

teams/rustc-dev-guide.toml

A very belated addition, @Kobzol does a lot to help improve things for the team
cc @BoxyUwU

rustc-dev-guide team: add Kobzol

---

repos/rust-lang/rustc-dev-guide.toml

In coordination with https://github.com/rust-lang/rustc-dev-guide/pull/2570.

Change branch protection of rustc-dev-guide to `main`

---

teams/compiler-fcp.toml
teams/compiler.toml
teams/project-const-generics.toml
teams/project-const-traits.toml
teams/project-trait-system-refactor.toml
teams/types-fcp.toml
teams/wg-async.toml
teams/wg-diagnostics.toml

I'm not planning on contributing to Rust very much in the short-to-medium-term due to changes in my job situation.
I'm removing myself from FCPs from T-compiler and T-types just so I don't end up blocking FCPs, and I'm removing myself from a bunch of random project groups at the same time just to tidy stuff up. I'm remaining on T-compiler and T-types for the time being though.

Remove compiler-errors from FCPs, working groups

---

teams/lang-ops.toml

Due to his consistent and valuable work in supporting the operations of the lang team, the lang-ops team is pleased to welcome Tomas.
cc @tomassedovic @rust-lang/lang @rust-lang/lang-ops

Add Tomas to lang-ops

---

teams/foundation-board-project-directors.toml

Welcome @davidtwco, @nikomatsakis and @jackh726! And thank you @JakobDegen, @scottmcm and @spastorino for your work on the Project Director board!
https://rust-lang.zulipchat.com/#narrow/channel/335408-foundation/topic/Project.20Director.20Elections.202025/with/543390976

Update Project directors based on 2025 election results
